;;; -*- Mode: LISP; Package: MKRP; Syntax: Common-lisp -*-
(* IN AN ASSOCIATIVE SYSTEM WITH AN IDENTITY ELEMENT)
(* IF THE SQUARE OF EVERY ELEMENT IS THE IDENTITY,)
(* THE SYSTEM IS COMMUTATIVE)
(ALL X P (X E X))
(ALL X P (E X X))
(ALL X P (X X E))
(ALL U,V,W,X,Y,Z P (X Y U) AND P (Y Z V) AND P (U Z W) IMPL P (X V W))
(ALL U,V,W,X,Y,Z P (X Y U) AND P (Y Z V) AND P (X V W) IMPL P (U Z W))

(ALL X,Y,Z P (X Y Z) IMPL P (Y X Z))