;;; -*- Mode: LISP; Package: MKRP; Syntax: Common-lisp -*-
(* PROBLEM 49)
(*)
(* ONE DAY ALICE MET THE LION.)
(* HE MADE TWO FOLLOWING STATEMENTS :)
(*)
(* I LIED YESTERDAY.)
(* I WILL LIE AGAIN TOMORROW.)
(*)
(* ON WHAT DAYS OF THE WEEK IS THIS POSSIBLE?)
(*)
(*)
(* FORMALIZING THE PROBLEM IN FIRST ORDER LOGIC)
(*)
(all x mo(x) impl ll(x))
(all x tu(x) impl ll(x))
(all x we(x) impl ll(x))
(all x th(x) impl not ll(x))
(all x fr(x) impl not ll(x))
(all x sa(x) impl not ll(x))
(all x su(x) impl not ll(x))
(*)
(all x mo(x) impl not lu(x))
(all x tu(x) impl not lu(x))
(all x we(x) impl not lu(x))
(all x th(x) impl lu(x))
(all x fr(x) impl lu(x))
(all x sa(x) impl lu(x))
(all x su(x) impl not lu(x))
(*)
(ALL X MO (YESTERDAY (X)) EQV TU (X))
(ALL X TU (YESTERDAY (X)) EQV WE (X))
(ALL X WE (YESTERDAY (X)) EQV TH (X))
(ALL X TH (YESTERDAY (X)) EQV FR (X))
(ALL X FR (YESTERDAY (X)) EQV SA (X))
(ALL X SA (YESTERDAY (X)) EQV SU (X))
(ALL X SU (YESTERDAY (X)) EQV MO (X))
(*)
(all x lu(x) impl day(x))
(all x ll(x) impl day(x))
(*)
(ALL X MO (X) IMPL day (X))
(ALL X TU (X) IMPL day (X))
(ALL X WE (X) IMPL day (X))
(ALL X TH (X) IMPL day (X))
(ALL X FR (X) IMPL day (X))
(ALL X SA (X) IMPL day (X))
(ALL X SU (X) IMPL day (X))
(* The predicate la has the following meaning:)
(* LA (X Y Z) IS TRUE, IFF X STATES AT DAY Y , THAT HE LIES ON DAY Z)
(*)
(all x,y (day(x) and day(y)) impl ((lu(x) and la(unicorn x y)) impl not lu(y)))
(all x,y (day(x) and day(y)) impl ((not lu(x) and la(unicorn x y)) impl lu(y)))
(all x,y (day(x) and day(y)) impl ((not lu(x) and not la(unicorn x y)) impl not lu(y)))
(all x,y (day(x) and day(y)) impl ((lu(x) and not la(unicorn x y)) impl lu(y)))
(*)
(all x,y (day(x) and day(y)) impl ((ll(x) and la(lion x y)) impl not ll(y)))
(all x,y (day(x) and day(y)) impl ((not ll(x) and la(lion x y)) impl ll(y)))
(all x,y (day(x) and day(y)) impl ((not ll(x) and not la(lion x y)) impl not ll(y)))
(all x,y (day(x) and day(y)) impl ((ll(x) and not la(lion x y)) impl ll(y)))
(*)
(*)
(MO (MONDAY))
(TU (TUESDAY))
(WE (WEDNESDAY))
(TH (THURSDAY))
(FR (FRIDAY))
(SA (SATURDAY))
(SU (SUNDAY))
(*)

(ex x day(x) and la(unicorn x yesterday(x)) and la(lion x yesterday(x)))