;;; -*- Mode: Lisp; Syntax: Common-lisp; Package: MKRP -*-)
(* ************************************************)
(* DEFINITIONEN DER MENGENLEHRE)
(SORT SET:ANY)
(SORT ELEMENT:SET)
(TYPE EL (ELEMENT SET))
(* DEFINITION 1.3: KARTESISCHES PRODUKT)
(TYPE CARTES (SET SET) :SET)
(TYPE PAIR (ELEMENT ELEMENT) :ELEMENT)
(* DEFINITION 1.7: FUNKTION)
(SORT SYMB.OF.FUNCTION:ANY)
(TYPE MAPPING (SYMB.OF.FUNCTION SET SET))
(TYPE MAPPING.S (SYMB.OF.FUNCTION SET SET))
(TYPE S:SET)
(SORT EL.OF.S:ELEMENT)
(TYPE APPLY (SYMB.OF.FUNCTION ELEMENT) :ELEMENT)
(ALL F:SYMB.OF.FUNCTION ALL Y:SET MAPPING.S (F S Y) EQV (ALL A:EL.OF.S EL (APPLY (F A) Y)))
(ALL F:SYMB.OF.FUNCTION ALL X,Y:SET MAPPING (F X Y) EQV (ALL A:ELEMENT EL (A X) IMPL EL (APPLY (F A) Y)))
(* DEFINITION 1.8: SURJEKTIV)
(TYPE SURJECTIVE (SYMB.OF.FUNCTION SET SET))
(ALL F:SYMB.OF.FUNCTION ALL X, 
     Y:SET SURJECTIVE (F X Y)
     EQV 
     MAPPING (F X Y) AND (ALL B:ELEMENT EL (B Y) IMPL (EX A:ELEMENT EL (A X) AND APPLY (F A) = B)))
(TYPE SURJECTIVE.S (SYMB.OF.FUNCTION SET SET))
(ALL F:SYMB.OF.FUNCTION ALL Y:SET 
     SURJECTIVE.S (F S Y) EQV MAPPING.S (F S Y) AND (ALL B:ELEMENT EL (B Y) IMPL (EX A:EL.OF.S APPLY (F A) = B)))
(* ************************************************************************)
(* DEFINITIONEN VON RELATIONEN AUF EINER FESTEN MENGE S)
(SORT REL:SET)
(* DEFINITION 2.8: AEQUIVALENZRELATION)
(SORT EQU.RELATION:REL)
(* DEFINITION 2.13: DIE VON EINER ABBILDUNG PHI VON S NACH U INDUZIERTE AEQUIVALENZRELATION)
(TYPE IND.EQU (SYMB.OF.FUNCTION SET) :EQU.RELATION)
(ALL PHI:SYMB.OF.FUNCTION ALL U:SET 
     MAPPING.S (PHI S U)
     IMPL 
     ALL A:ELEMENT 
     EL (A IND.EQU (PHI U)) EQV (EX B,C:EL.OF.S A = PAIR (B C) AND APPLY (PHI B) = APPLY (PHI C)))

(ALL PHI1,PHI2,GR.PHI:SYMB.OF.FUNCTION ALL U,V:SET 
     SURJECTIVE.S (PHI1 S U)
     AND 
     SURJECTIVE.S (PHI2 S V)
     AND 
     MAPPING (GR.PHI U V)
     AND 
     (ALL S:EL.OF.S APPLY (GR.PHI APPLY (PHI1 S)) = APPLY (PHI2 S))
     IMPL 
     SURJECTIVE (GR.PHI U V))
