;;; -*- Package: MKRP; Mode: LISP; Syntax: Common-lisp -*-


(SORT MENGE,ELEMENT:ANY)	
(TYPE W(MENGE) :MENGE)	
(TYPE APPLYA(MENGE ELEMENT) :ELEMENT)	
(TYPE INV(MENGE) :MENGE)	
(* ISOMORPHIE VON TEILMENGEN *)
(ALL A1,B1,PHI:MENGE (ALL A,B:MENGE  ALL X,Y:ELEMENT  
			  ISOMORPH(PHI A B) AND ME(A1 A) AND ME(B1 B) AND EL(X A1) AND EL(Y B1)
			  IMPL EL(APPLYA(PHI X) B1) AND EL(APPLYA(INV(PHI) Y) A1))
     IMPL ISOMORPH(PHI A1 B1))
(* LEMMA 2.6.LR.1.1 *)
(ALL A,B,PHI:MENGE ISOMORPH(PHI W(A) W(B)) IMPL(ALL X:ELEMENT EL(X A) IMPL EL(APPLYA(PHI X) B)))	
(* LEMMA 2.6.LR.1.2 *)
(ALL A,B,PHI:MENGE ISOMORPH(PHI W(A) W(B)) IMPL(ALL X:ELEMENT EL(X B) IMPL EL(APPLYA(INV(PHI) X) A)))
(* EIGENSCHAFT VON W(X) *)
(ALL X:MENGE ME(X W(X)))
 
(ALL X,Y,PHI:MENGE ISOMORPH(PHI W(X) W(Y)) IMPL(EX PSI:MENGE ISOMORPH(PSI X Y)))
 
 
