;;; -*- Package: MKRP; Mode: LISP; Syntax: Common-lisp -*-  



(SORT MENGE,INDEX,VERKN,ELEMENT:ANY)
(TYPE 1:INDEX)
(TYPE KLUHG (MENGE MENGE VERKN) :MENGE)
(TYPE EHG (MENGE VERKN INDEX) :MENGE)
(TYPE V (MENGE MENGE) :MENGE)
(TYPE APPLY (VERKN ELEMENT ELEMENT) :ELEMENT)
(TYPE PLUS (INDEX INDEX) :INDEX)
(ALL N:INDEX KLEINERGLEICH (1 N))
(ALL A,B:MENGE  ALL X,Y:ELEMENT  ALL PHI:VERKN  
     EL (X KLUHG (A B PHI)) AND EL (Y KLUHG (A B PHI))
     IMPL  
     EL (APPLY (PHI X Y) KLUHG (A B PHI)))
(ALL A,B:MENGE  ALL N,NSTRICH:INDEX  ALL PHI:VERKN  ALL X:ELEMENT  
     KLEINERGLEICH (NSTRICH N) AND EL (X EHG (V (A B) PHI NSTRICH))
     IMPL  
     EL (X KLUHG (A B PHI)))
(ALL PHI:VERKN  ALL X,Y,Z:ELEMENT  ALL E:MENGE  ALL N:INDEX  
     EL (X EHG (E PHI PLUS (N 1))) AND X = APPLY (PHI Y Z)
     IMPL  
     EL (Y EHG (E PHI N)) AND EL (Z EHG (E PHI 1)))
(ALL X:ELEMENT  EX Y,Z:ELEMENT  ALL PHI:VERKN  ALL N:INDEX  )
(ALL E:MENGE  
     EL (X EHG (E PHI PLUS (N 1))) IMPL X = APPLY (PHI Y Z))

(ALL NSTRICH,N:INDEX  ALL X:ELEMENT  ALL A,B:MENGE  ALL PHI:VERKN  
     KLEINERGLEICH (NSTRICH N)
     AND  
     EL (X EHG (V (A B) PHI PLUS (NSTRICH 1)))
     IMPL  
     EL (X KLUHG (A B PHI)))