;;; -*- Package: MKRP; Base: 10; Mode: LISP; Syntax: Common-lisp -*-

(CONSTRUCTION  "Unix" "15-AUG,1991 10:02" 
              ("Edit:     Axioms and Theorems edited: 15-AUG,1991 10:02 "
               ))

(AXIOMS.INFIX    ((ALL U F (I (U) U) = E)
                  (ALL V F (V E) = V)
                  (ALL |X,Y| S (X) AND S (Y) IMPL S (F (I (Y) X)))))

(THEOREMS.INFIX ((ALL Z S (Z) IMPL S (I (Z)))))

(AXIOMS.PREFIX   ((ALL 3 (+ 2 ((6 (4 3) 3) 5) NIL))
                  (ALL 7 (+ 2 ((6 7 5) 7) NIL))
                  (ALL 9 (ALL 8 (IMPL (AND (+ 10 (8) NIL) (+ 10 (9) NIL)) (+ 10 ((6 (4 9) 8)) NIL))))))

(THEOREMS.PREFIX ((ALL 11 (IMPL (+ 10 (11) NIL) (+ 10 ((4 11)) NIL)))))

(OPTIONS (TWO_RULES)
          (TWO_RULES.MAXLEVEL . 1)
          (TWO_SUPPRESS.NORULES)
          (RED.I_CLAUSE.MULTIPLE.LITERALS . T)
          (RED.I_CLAUSE.PURITY . P)
          (RED.I_CLAUSE.TAUTOLOGY . T)
          (RED.I_CLAUSE.TAUTOLOGY.RECHECK . PARTIAL)
          (RED.I_CLAUSE.SUBSUMPTION . T)
          (RED.I_CLAUSE.SUBSUMPTION.RECHECK . PARTIAL)
          (RED.I_CLAUSE.REPL.FACTORING . T)
          (RED.I_CLAUSE.REPL.FACTORING.RECHECK . T)
          (RED.I_CLAUSE.REPL.RESOLUTION . SIMPLE)
          (RED.I_CLAUSE.REPL.RESOLUTION.RECHECK . T)
          (RED.I_CLAUSE.REWRITING . DEM)
          (RED.I_LINK.INCOMPATIBILITY . T)
          (RED.I_LINK.TAUTOLOGY . REMOVE-INHIBIT)
          (RED.I_LINK.TAUTOLOGY.RECHECK)
          (RED.I_LINK.SUBSUMPTION . REMOVE-INHIBIT)
          (RED.I_LINK.SUBSUMPTION.RECHECK)
          (RED.D_CLAUSE.MULTIPLE.LITERALS . T)
          (RED.D_CLAUSE.PURITY . P)
          (RED.D_CLAUSE.TAUTOLOGY . REMOVE-INHIBIT)
          (RED.D_CLAUSE.TAUTOLOGY.RECHECK)
          (RED.D_CLAUSE.SUBSUMPTION.FORWARD . REMOVE-INHIBIT)
          (RED.D_CLAUSE.SUBSUMPTION.BACKWARD . REMOVE)
          (RED.D_CLAUSE.SUBSUMPTION.RECHECK)
          (RED.D_CLAUSE.REPL.FACTORING . T)
          (RED.D_CLAUSE.REPL.FACTORING.RECHECK . T)
          (RED.D_CLAUSE.REPL.RESOLUTION . SIMPLE)
          (RED.D_CLAUSE.REPL.RESOLUTION.RECHECK . T)
          (RED.D_CLAUSE.REWRITING . DEM)
          (RED.D_LINK.INCOMPATIBILITY . T)
          (RED.D_LINK.TAUTOLOGY . REMOVE-INHIBIT)
          (RED.D_LINK.TAUTOLOGY.RECHECK)
          (RED.D_LINK.SUBSUMPTION . REMOVE-INHIBIT)
          (RED.D_LINK.SUBSUMPTION.RECHECK)
          (FAC_INITIAL)
          (FAC_EACH.STEP)
          (STR_RESOLUTION . SET-OF-SUPPORT)
          (STR_PAR-RES . 10)
          (STR_LINK.DEPTH)
          (STR_TERM.DEPTH)
          (STR_FINITE.DOMAIN . T)
          (STR_SORT.LITERALS)
          (TERM_UNITS . T)
          (TERM_ITERATIONS . 0)
          (TERM_SET.OF.SUPPORT)
          (TERM_BREADTH.FIRST)
          (ER_PARAMODULATION . HEURISTIC-COMPLETION)
          (ER_COMPLETION . UNFAILING)
          (ER_CP.REDUCTION . T)
          (ER_ORDERING . LEXICOGRAPHIC-RECURSIVE-PATH)
          (ER_OPERATOR.ORDERING * - + 0 1)
          (ER_KNUTH.BENDIX.WEIGHT (+ 1) (* 1) (- 0) (0 1) (1 1))
          (ER_POLYNOMIAL.VARIABLES X Y Z U V W)
          (ER_POLYNOMIAL.WEIGHT (+ (+ X (* 2 Y))) (* (+ X (* X Y))) (- (+ (* 2 X) -1)) (0 2) (1 2))
          (ER_LINK.DEPTH.WEIGHT . 0)
          (ER_UNIT.FOCUS . 0)
          (ER_UNIT.FOCUS.WEIGHT . 1)
          (ER_EQUATION.FOCUS . 2)
          (ER_NARROW.DEPTH . 0)
          (ER_NARROW.NEXT . DEPTH)
          (ER_NARROW.TEST NORM C DELTA SL N)
          (ER_NARROW.LIMIT.FACTOR . 0)
          (ER_COMPILE)
          (GEN_SPLITTING . 0)
          (GEN_PRESIMPLIFICATION . T)
          (GEN_MIN.EXPRESSION.LENGTH.FOR.FILE)
          (GEN_MIN.EXPRESSION.SIZE.FOR.FILE)
          (GEN_MANUAL.CONTROL)
          (GEN_MAXIMUM.STEPS)
          (GEN_GRAPH.SAVING)
          (GEN_SAVE.FILE . SAVEDEFAULT)
          (GEN_LISP.GARBAGE.COLLECTION)
          (GEN_COMMON.LISP . T)
          (TR_PREPROCESSING)
          (TR_STEP.MODE . LR)
          (TR_DUMP)
          (TR_CLAUSE.MODE . I)
          (TR_LINK.MODE . I)
          (TR_TRACE.FILE)
          (TR_TERMINAL . T)
          (PR_LATEX)
          (PR_INFIX.FORM . T)
          (PR_PREFIX.FORM)
          (PR_OPTIONS)
          (PR_AXIOM.CLAUSES . T)
          (PR_SYMBOLS)
          (PR_DIRECT.PROOF . T)
          (PR_VARIABLE.PRINT.NAMES X Y Z U V W XX YY ZZ UU VV WW XXX YYY ZZZ UUU VVV WWW)
          (PR_STATISTICS)
          (PR_PROTOCOL . T)
          (PR_LEFT.MARGIN . 3)
          (PR_RIGHT.MARGIN . 117)
          (PR_LINELENGTH . 114)
          (PR_LITERALS)
         )

(LINK.COLOURS (R RIW RD S SI SIW SID T TI TIW P PIW PD RIWD))

(AXIOMS (START.TIME 8630000)
        (PARTIAL   (CLAUSE 14 R.= AXIOM ((12 . ANY)) ((+ 2 (12 12)) ))(CLAUSE 16 A1 AXIOM ((3 . ANY)) ((+ 2 ((6 (4 3) 3) 5)) )))
        (PARTIAL   (CLAUSE 20 A2 AXIOM ((7 . ANY)) ((+ 2 ((6 7 5) 7)) )))
        (PARTIAL   (CLAUSE 26 A3 AXIOM ((9 . ANY)(8 . ANY))
                         ((- 10 (8)) (- 10 (9)) (+ 10 ((6 (4 9) 8))) )))
        (END.TIME 9670000)
        (FINAL 14 16 20 26)
        (SYMBOLS 
                 (LET (NEW.ADDRESS)
          (LIST (CONS   10 (DT-PREDICATE.CREATE "S" '(ANY)))
                         (PROG1 (CONS    2 (SETQ NEW.ADDRESS (DT-PREDICATE.CREATE "=" '(ANY ANY))))
                                (DT-PREDICATE.ADD.ATTRIBUTES NEW.ADDRESS '(DEFINED SYMMETRIC REFLEXIVE SYMMETRIC REFLEXIVE)))
                         (PROG1 (CONS    1 (SETQ NEW.ADDRESS (DT-PREDICATE.CREATE "FALSE" 'NIL)))
                                (DT-PREDICATE.ADD.ATTRIBUTES NEW.ADDRESS '(DEFINED)))
                         (PROG1 (CONS    0 (SETQ NEW.ADDRESS (DT-PREDICATE.CREATE "TRUE" 'NIL)))
                                (DT-PREDICATE.ADD.ATTRIBUTES NEW.ADDRESS '(DEFINED)))
                         (CONS    5 (DT-CONSTANT.CREATE "e" 'ANY))
                         (CONS    6 (DT-FUNCTION.CREATE "f" 'ANY '(ANY ANY) 'NIL))
                         (CONS    4 (DT-FUNCTION.CREATE "i" 'ANY '(ANY) 'NIL)))))
        (RESULT))

(THEOREMS (SPLITPART.IDENTIFIER 1)
          (START.TIME 9720000)
          (PARTIAL   (CLAUSE 11 T4 THEOREM () ((+ 10 (33)) )))
          (PARTIAL   (CLAUSE 36 T5 THEOREM () ((- 10 ((4 33))) )))
          (INITIAL   (CLAUSE 14 R.= AXIOM ((12 . ANY)) ((+ 2 (12 12)) ))
(CLAUSE 16 A1 AXIOM ((3 . ANY)) ((+ 2 ((6 (4 3) 3) 5)) ))
(CLAUSE 20 A2 AXIOM ((7 . ANY)) ((+ 2 ((6 7 5) 7)) ))
(CLAUSE 26 A3 AXIOM ((9 . ANY)(8 . ANY))
                           ((- 10 (8)) (- 10 (9)) (+ 10 ((6 (4 9) 8))) ))
(CLAUSE 11 T4 THEOREM () ((+ 10 (33)) ))
(CLAUSE 36 T5 THEOREM () ((- 10 ((4 33))) )) )
          (END.TIME 10650000)
          (FINAL 14 16 20 26 11 36)
          (SYMBOLS 
                   (LET (NEW.ADDRESS)
          (LIST (CONS   10 (DT-PREDICATE.CREATE "S" '(ANY)))
                           (PROG1 (CONS    2 (SETQ NEW.ADDRESS (DT-PREDICATE.CREATE "=" '(ANY ANY))))
                                  (DT-PREDICATE.ADD.ATTRIBUTES NEW.ADDRESS '(DEFINED SYMMETRIC REFLEXIVE SYMMETRIC REFLEXIVE)))
                           (PROG1 (CONS    1 (SETQ NEW.ADDRESS (DT-PREDICATE.CREATE "FALSE" 'NIL)))
                                  (DT-PREDICATE.ADD.ATTRIBUTES NEW.ADDRESS '(DEFINED)))
                           (PROG1 (CONS    0 (SETQ NEW.ADDRESS (DT-PREDICATE.CREATE "TRUE" 'NIL)))
                                  (DT-PREDICATE.ADD.ATTRIBUTES NEW.ADDRESS '(DEFINED)))
                           (CONS   33 (DT-CONSTANT.CREATE "c_1" 'ANY))
                           (CONS    5 (DT-CONSTANT.CREATE "e" 'ANY))
                           (CONS    6 (DT-FUNCTION.CREATE "f" 'ANY '(ANY ANY) 'NIL))
                           (CONS    4 (DT-FUNCTION.CREATE "i" 'ANY '(ANY) 'NIL)))))
          (RESULT))
(indices ((36 7) (11 6) (26 3 4 5) (20 2) (16 1) (14 NIL)))

(SPLITPARTS "Unix" "15-AUG,1991 10:02" NIL)

(OPTIONS (TWO_RULES)
          (TWO_RULES.MAXLEVEL . 1)
          (TWO_SUPPRESS.NORULES)
          (RED.I_CLAUSE.MULTIPLE.LITERALS . T)
          (RED.I_CLAUSE.PURITY . P)
          (RED.I_CLAUSE.TAUTOLOGY . T)
          (RED.I_CLAUSE.TAUTOLOGY.RECHECK . PARTIAL)
          (RED.I_CLAUSE.SUBSUMPTION . T)
          (RED.I_CLAUSE.SUBSUMPTION.RECHECK . PARTIAL)
          (RED.I_CLAUSE.REPL.FACTORING . T)
          (RED.I_CLAUSE.REPL.FACTORING.RECHECK . T)
          (RED.I_CLAUSE.REPL.RESOLUTION . SIMPLE)
          (RED.I_CLAUSE.REPL.RESOLUTION.RECHECK . T)
          (RED.I_CLAUSE.REWRITING . DEM)
          (RED.I_LINK.INCOMPATIBILITY . T)
          (RED.I_LINK.TAUTOLOGY . REMOVE-INHIBIT)
          (RED.I_LINK.TAUTOLOGY.RECHECK)
          (RED.I_LINK.SUBSUMPTION . REMOVE-INHIBIT)
          (RED.I_LINK.SUBSUMPTION.RECHECK)
          (RED.D_CLAUSE.MULTIPLE.LITERALS . T)
          (RED.D_CLAUSE.PURITY . P)
          (RED.D_CLAUSE.TAUTOLOGY . REMOVE-INHIBIT)
          (RED.D_CLAUSE.TAUTOLOGY.RECHECK)
          (RED.D_CLAUSE.SUBSUMPTION.FORWARD . REMOVE-INHIBIT)
          (RED.D_CLAUSE.SUBSUMPTION.BACKWARD . REMOVE)
          (RED.D_CLAUSE.SUBSUMPTION.RECHECK)
          (RED.D_CLAUSE.REPL.FACTORING . T)
          (RED.D_CLAUSE.REPL.FACTORING.RECHECK . T)
          (RED.D_CLAUSE.REPL.RESOLUTION . SIMPLE)
          (RED.D_CLAUSE.REPL.RESOLUTION.RECHECK . T)
          (RED.D_CLAUSE.REWRITING . DEM)
          (RED.D_LINK.INCOMPATIBILITY . T)
          (RED.D_LINK.TAUTOLOGY . REMOVE-INHIBIT)
          (RED.D_LINK.TAUTOLOGY.RECHECK)
          (RED.D_LINK.SUBSUMPTION . REMOVE-INHIBIT)
          (RED.D_LINK.SUBSUMPTION.RECHECK)
          (FAC_INITIAL)
          (FAC_EACH.STEP)
          (STR_RESOLUTION . SET-OF-SUPPORT)
          (STR_PAR-RES . 10)
          (STR_LINK.DEPTH)
          (STR_TERM.DEPTH)
          (STR_FINITE.DOMAIN . T)
          (STR_SORT.LITERALS)
          (TERM_UNITS . T)
          (TERM_ITERATIONS . 0)
          (TERM_SET.OF.SUPPORT)
          (TERM_BREADTH.FIRST)
          (ER_PARAMODULATION . HEURISTIC-COMPLETION)
          (ER_COMPLETION . UNFAILING)
          (ER_CP.REDUCTION . T)
          (ER_ORDERING . LEXICOGRAPHIC-RECURSIVE-PATH)
          (ER_OPERATOR.ORDERING * - + 0 1)
          (ER_KNUTH.BENDIX.WEIGHT (+ 1) (* 1) (- 0) (0 1) (1 1))
          (ER_POLYNOMIAL.VARIABLES X Y Z U V W)
          (ER_POLYNOMIAL.WEIGHT (+ (+ X (* 2 Y))) (* (+ X (* X Y))) (- (+ (* 2 X) -1)) (0 2) (1 2))
          (ER_LINK.DEPTH.WEIGHT . 0)
          (ER_UNIT.FOCUS . 0)
          (ER_UNIT.FOCUS.WEIGHT . 1)
          (ER_EQUATION.FOCUS . 2)
          (ER_NARROW.DEPTH . 0)
          (ER_NARROW.NEXT . DEPTH)
          (ER_NARROW.TEST NORM C DELTA SL N)
          (ER_NARROW.LIMIT.FACTOR . 0)
          (ER_COMPILE)
          (GEN_SPLITTING . 0)
          (GEN_PRESIMPLIFICATION . T)
          (GEN_MIN.EXPRESSION.LENGTH.FOR.FILE)
          (GEN_MIN.EXPRESSION.SIZE.FOR.FILE)
          (GEN_MANUAL.CONTROL)
          (GEN_MAXIMUM.STEPS)
          (GEN_GRAPH.SAVING)
          (GEN_SAVE.FILE . SAVEDEFAULT)
          (GEN_LISP.GARBAGE.COLLECTION)
          (GEN_COMMON.LISP . T)
          (TR_PREPROCESSING)
          (TR_STEP.MODE . LR)
          (TR_DUMP)
          (TR_CLAUSE.MODE . I)
          (TR_LINK.MODE . I)
          (TR_TRACE.FILE)
          (TR_TERMINAL . T)
          (PR_LATEX)
          (PR_INFIX.FORM . T)
          (PR_PREFIX.FORM)
          (PR_OPTIONS)
          (PR_AXIOM.CLAUSES . T)
          (PR_SYMBOLS)
          (PR_DIRECT.PROOF . T)
          (PR_VARIABLE.PRINT.NAMES X Y Z U V W XX YY ZZ UU VV WW XXX YYY ZZZ UUU VVV WWW)
          (PR_STATISTICS)
          (PR_PROTOCOL . T)
          (PR_LEFT.MARGIN . 3)
          (PR_RIGHT.MARGIN . 117)
          (PR_LINELENGTH . 114)
          (PR_LITERALS)
         )

(REFUTATION (START.TIME 11010000)

(OPTIONS (TWO_RULES)
          (TWO_RULES.MAXLEVEL . 1)
          (TWO_SUPPRESS.NORULES)
          (RED.I_CLAUSE.MULTIPLE.LITERALS . T)
          (RED.I_CLAUSE.PURITY . P)
          (RED.I_CLAUSE.TAUTOLOGY . T)
          (RED.I_CLAUSE.TAUTOLOGY.RECHECK . PARTIAL)
          (RED.I_CLAUSE.SUBSUMPTION . T)
          (RED.I_CLAUSE.SUBSUMPTION.RECHECK . PARTIAL)
          (RED.I_CLAUSE.REPL.FACTORING . T)
          (RED.I_CLAUSE.REPL.FACTORING.RECHECK . T)
          (RED.I_CLAUSE.REPL.RESOLUTION . SIMPLE)
          (RED.I_CLAUSE.REPL.RESOLUTION.RECHECK . T)
          (RED.I_CLAUSE.REWRITING . DEM)
          (RED.I_LINK.INCOMPATIBILITY . T)
          (RED.I_LINK.TAUTOLOGY . REMOVE-INHIBIT)
          (RED.I_LINK.TAUTOLOGY.RECHECK)
          (RED.I_LINK.SUBSUMPTION . REMOVE-INHIBIT)
          (RED.I_LINK.SUBSUMPTION.RECHECK)
          (RED.D_CLAUSE.MULTIPLE.LITERALS . T)
          (RED.D_CLAUSE.PURITY . P)
          (RED.D_CLAUSE.TAUTOLOGY . REMOVE-INHIBIT)
          (RED.D_CLAUSE.TAUTOLOGY.RECHECK)
          (RED.D_CLAUSE.SUBSUMPTION.FORWARD . REMOVE-INHIBIT)
          (RED.D_CLAUSE.SUBSUMPTION.BACKWARD . REMOVE)
          (RED.D_CLAUSE.SUBSUMPTION.RECHECK)
          (RED.D_CLAUSE.REPL.FACTORING . T)
          (RED.D_CLAUSE.REPL.FACTORING.RECHECK . T)
          (RED.D_CLAUSE.REPL.RESOLUTION . SIMPLE)
          (RED.D_CLAUSE.REPL.RESOLUTION.RECHECK . T)
          (RED.D_CLAUSE.REWRITING . DEM)
          (RED.D_LINK.INCOMPATIBILITY . T)
          (RED.D_LINK.TAUTOLOGY . REMOVE-INHIBIT)
          (RED.D_LINK.TAUTOLOGY.RECHECK)
          (RED.D_LINK.SUBSUMPTION . REMOVE-INHIBIT)
          (RED.D_LINK.SUBSUMPTION.RECHECK)
          (FAC_INITIAL)
          (FAC_EACH.STEP)
          (STR_RESOLUTION . SET-OF-SUPPORT)
          (STR_PAR-RES . 10)
          (STR_LINK.DEPTH)
          (STR_TERM.DEPTH)
          (STR_FINITE.DOMAIN . T)
          (STR_SORT.LITERALS)
          (TERM_UNITS . T)
          (TERM_ITERATIONS . 0)
          (TERM_SET.OF.SUPPORT)
          (TERM_BREADTH.FIRST)
          (ER_PARAMODULATION . HEURISTIC-COMPLETION)
          (ER_COMPLETION . UNFAILING)
          (ER_CP.REDUCTION . T)
          (ER_ORDERING . LEXICOGRAPHIC-RECURSIVE-PATH)
          (ER_OPERATOR.ORDERING * - + 0 1)
          (ER_KNUTH.BENDIX.WEIGHT (+ 1) (* 1) (- 0) (0 1) (1 1))
          (ER_POLYNOMIAL.VARIABLES X Y Z U V W)
          (ER_POLYNOMIAL.WEIGHT (+ (+ X (* 2 Y))) (* (+ X (* X Y))) (- (+ (* 2 X) -1)) (0 2) (1 2))
          (ER_LINK.DEPTH.WEIGHT . 0)
          (ER_UNIT.FOCUS . 0)
          (ER_UNIT.FOCUS.WEIGHT . 1)
          (ER_EQUATION.FOCUS . 2)
          (ER_NARROW.DEPTH . 0)
          (ER_NARROW.NEXT . DEPTH)
          (ER_NARROW.TEST NORM C DELTA SL N)
          (ER_NARROW.LIMIT.FACTOR . 0)
          (ER_COMPILE)
          (GEN_SPLITTING . 0)
          (GEN_PRESIMPLIFICATION . T)
          (GEN_MIN.EXPRESSION.LENGTH.FOR.FILE)
          (GEN_MIN.EXPRESSION.SIZE.FOR.FILE)
          (GEN_MANUAL.CONTROL)
          (GEN_MAXIMUM.STEPS)
          (GEN_GRAPH.SAVING)
          (GEN_SAVE.FILE . SAVEDEFAULT)
          (GEN_LISP.GARBAGE.COLLECTION)
          (GEN_COMMON.LISP . T)
          (TR_PREPROCESSING)
          (TR_STEP.MODE . LR)
          (TR_DUMP)
          (TR_CLAUSE.MODE . I)
          (TR_LINK.MODE . I)
          (TR_TRACE.FILE)
          (TR_TERMINAL . T)
          (PR_LATEX)
          (PR_INFIX.FORM . T)
          (PR_PREFIX.FORM)
          (PR_OPTIONS)
          (PR_AXIOM.CLAUSES . T)
          (PR_SYMBOLS)
          (PR_DIRECT.PROOF . T)
          (PR_VARIABLE.PRINT.NAMES X Y Z U V W XX YY ZZ UU VV WW XXX YYY ZZZ UUU VVV WWW)
          (PR_STATISTICS)
          (PR_PROTOCOL . T)
          (PR_LEFT.MARGIN . 3)
          (PR_RIGHT.MARGIN . 117)
          (PR_LINELENGTH . 114)
          (PR_LITERALS)
         )
            (INITIAL   (CLAUSE 14 R.= AXIOM ((12 . ANY)) ((+ 2 (12 12)) ))
(CLAUSE 16 A1 AXIOM ((3 . ANY)) ((+ 2 ((6 (4 3) 3) 5)) ))
(CLAUSE 20 A2 AXIOM ((7 . ANY)) ((+ 2 ((6 7 5) 7)) ))
(CLAUSE 26 A3 AXIOM ((9 . ANY)(8 . ANY))
                             ((- 10 (8)) (- 10 (9)) (+ 10 ((6 (4 9) 8))) ))
(CLAUSE 11 T4 THEOREM () ((+ 10 (33)) ))
(CLAUSE 36 T5 THEOREM () ((- 10 ((4 33))) )) )
            (OPERATION (CLAUSE 17 P1 (16 20) () ((+ 2 ((4 5) 5)) ))
                       (PARAMODULATION 20 1 (1) 16 1 (1) NIL (7 (4 5) 3 5) 17))
            (OPERATION (CLAUSE 53 P2 (26 16) ((51 . ANY))
                               ((+ 10 (5)) (- 10 (51)) (- 10 (51)) ))
                       (PARAMODULATION 16 1 (1) 26 3 (1) NIL (3 8 9 8) 53))
            (OPERATION (CLAUSE 53 P2 (26 16) ((51 . ANY))
                               ((+ 10 (5)) (- 10 (51)) ))
                       (DOUBLE.LITERAL 2 3 NIL 53))
            (OPERATION (CLAUSE 53 P2 (26 16) ((51 . ANY))
                               ((+ 10 (5)) (- 10 (51)) ))
                       (REPLACEMENT.OPERATION (51 33) (53 11)
  (((53 . 2) (11 . 1) NIL))
  (NIL)
  NIL))
            (OPERATION (CLAUSE 68 P3 (26 20) ((62 . ANY))
                               ((+ 10 ((4 62))) (- 10 (5)) (- 10 (62)) ))
                       (PARAMODULATION 20 1 (1) 26 3 (1) NIL (7 (4 9) 8 5) 68))
            (OPERATION (CLAUSE 68 P3 (26 20) ((62 . ANY))
                               ((+ 10 ((4 62))) (- 10 (5)) (- 10 (62)) ))
                       (REPLACEMENT.OPERATION (62 33) (68 11 36)
  (((68 . 3) (11 . 1) NIL) ((68 . 1) (36 . 1) NIL))
  (NIL NIL)
  NIL))
            (OPERATION (CLAUSE 68 P3 (26 20) () ((- 10 (5)) ))
                       (REPLACEMENT.OPERATION NIL (68 53)
  (((68 . 1) (53 . 1) NIL))
  (NIL)
  NIL))
            (END.TIME 13420000)
            (SYMBOLS 
                     (LET (NEW.ADDRESS)
          (LIST (CONS   10 (DT-PREDICATE.CREATE "S" '(ANY)))
                             (PROG1 (CONS    2 (SETQ NEW.ADDRESS (DT-PREDICATE.CREATE "=" '(ANY ANY))))
                                    (DT-PREDICATE.ADD.ATTRIBUTES NEW.ADDRESS '(DEFINED SYMMETRIC REFLEXIVE SYMMETRIC REFLEXIVE)))
                             (PROG1 (CONS    1 (SETQ NEW.ADDRESS (DT-PREDICATE.CREATE "FALSE" 'NIL)))
                                    (DT-PREDICATE.ADD.ATTRIBUTES NEW.ADDRESS '(DEFINED)))
                             (PROG1 (CONS    0 (SETQ NEW.ADDRESS (DT-PREDICATE.CREATE "TRUE" 'NIL)))
                                    (DT-PREDICATE.ADD.ATTRIBUTES NEW.ADDRESS '(DEFINED)))
                             (CONS   33 (DT-CONSTANT.CREATE "c_1" 'ANY))
                             (CONS    5 (DT-CONSTANT.CREATE "e" 'ANY))
                             (CONS    6 (DT-FUNCTION.CREATE "f" 'ANY '(ANY ANY) 'NIL))
                             (CONS    4 (DT-FUNCTION.CREATE "i" 'ANY '(ANY) 'NIL)))))
            (SPLITPART.IDENTIFIER 1)
            (RESULT SUCCESS 68)
)