;;; -*- Mode: LISP; Package: MKRP; Syntax: Common-lisp -*- 

(SORT ELEMENT,MENGE,VERKN,ABB:ANY)
(TYPE APPLYA (ABB ELEMENT) :ELEMENT)
(TYPE APPLYV (VERKN ELEMENT ELEMENT) :ELEMENT)
(TYPE INVERS (ELEMENT VERKN) :ELEMENT)
(TYPE C:ELEMENT)
(ALL M:MENGE  ALL CHI:ABB  
     ALL X,XSTRICH,Y:ELEMENT  
     EL (X M)
     AND  
     EL (Y M)
     AND  
     EL (XSTRICH M)
     AND  
     APPLYA (CHI X) = Y
     AND  
     APPLYA (CHI XSTRICH) = Y
     IMPL  
     X = XSTRICH
     IMPL  
     INJEKTIV (CHI M M))
(ALL X,Y,Z,U,E:ELEMENT  ALL F:MENGE  ALL PHI:VERKN  
     EL (X F) AND EL (Y F) AND EL (U F) AND G (F PHI E)
     IMPL  
     (APPLYV (PHI X U) = Y IMPL APPLYV (PHI Y INVERS (U PHI)) = X))
(ALL U,F:MENGE ALL PHI:VERKN UHG (U F PHI) IMPL ME (U F))
(ALL M1,M2:MENGE ALL X:ELEMENT EL (X M1) AND ME (M1 M2) IMPL EL (X M2))

(ALL E:ELEMENT  ALL U,F:MENGE  ALL PHI:VERKN  ALL CHI:ABB  
     (ALL V:ELEMENT APPLYV (PHI V C) = APPLYA (CHI V))
     AND  
     UHG (U F PHI)
     AND  
     G (F PHI E)
     AND  
     EL (C U)
     IMPL  
     INJEKTIV (CHI U U))