;;; -*- Package: MKRP; Base: 10; Mode: LISP; Syntax: Common-lisp -*-
(PREP-PROBLEM.SPECIFICATION (QUOTE ((SORT ELEM,MENGE,VERKN : ANY) (TYPE APPLY (VERKN ELEM ELEM) : ELEM) (TYPE INVERS (VERKN ELEM) : ELEM) (* ABGESCHLOSSENHEIT VON GR BEZGL PHI *) (ALL PHI : VERKN ALL GR : MENGE ALL X,Y,E : ELEM G (GR PHI E) AND EL (X GR) AND EL (Y GR) IMPL EL (APPLY (PHI X Y) GR)) (* EXISTENZ DES INVERSEN INNERHALB GR *) (ALL PHI : VERKN ALL X : ELEM ALL GR : MENGE ALL E : ELEM G (GR PHI E) AND EL (X GR) IMPL EL (INVERS (PHI X) GR)) (ALL U,F : MENGE ALL PHI : VERKN ALL E : ELEM UG (U F PHI E) IMPL G (U PHI E)))) (QUOTE ((+ 0 NIL) (+ 0 NIL) (+ 0 NIL) COMMENT (ALL 4 (ALL 5 (ALL 8 (ALL 7 (ALL 6 (IMPL (AND (+ 9 (5 4 8) NIL) (AND (+ 10 (6 5) NIL) (+ 10 (7 5) NIL))) (+ 10 ((2 4 6 7) 5) NIL))))))) COMMENT (ALL 11 (ALL 12 (ALL 13 (ALL 14 (IMPL (AND (+ 9 (13 11 14) NIL) (+ 10 (12 13) NIL)) (+ 10 ((3 11 12) 13) NIL)))))) (ALL 16 (ALL 15 (ALL 17 (ALL 18 (IMPL (+ 19 (15 16 17 18) NIL) (+ 9 (15 17 18) NIL)))))))) (QUOTE ((* THEOREM *) (ALL PHI : VERKN (ALL F,U : MENGE (ALL E : ELEM G (F PHI E) AND ME (U F) IMPL UG (U F PHI E) IMPL (ALL X,Y : ELEM EL (X U) AND EL (Y U) IMPL EL (APPLY (PHI INVERS (PHI Y) X) U))))))) (QUOTE (COMMENT (ALL 20 (ALL 22 (ALL 21 (ALL 23 (IMPL (AND (+ 9 (21 20 23) NIL) (+ 26 (22 21) NIL)) (IMPL (+ 19 (22 21 20 23) NIL) (ALL 28 (ALL 27 (IMPL (AND (+ 10 (27 22) NIL) (+ 10 (28 22) NIL)) (+ 10 ((2 20 (3 20 28) 27) 22) NIL)))))))))))) (QUOTE ("Edit:     Axioms and Theorems edited: 13-DEC,1989 19:01 ")) (PROGN(PROGN (DT-RESET))

(PROG ((ADDRLIST
        '(299791 299796 299811 ATP.MEMORY.NIL ATP.MEMORY.NIL 299816 299821 299826 299831
          299846 299851 299856 299861 299866 299871 299876 299881 299886 299901 299916 299921
          299926 299931 299936 299941 299955 299969 299984 299999))
       (DATALIST
        '(15 "TRUE" NIL NIL NIL (DEFINED) NIL ((- 0 (POSITIVE))) ((+ 0 (NEGATIVE)))
          ((+ 0 (NIL))) ((- 0 (NIL))) NIL NIL (DT*ST-KIND NIL) PREDICATE 15 "FALSE" NIL NIL
          NIL (DEFINED) NIL ((- 1 (POSITIVE))) ((+ 1 (NEGATIVE))) ((+ 1 (NIL))) ((- 1 (NIL)))
          NIL NIL (DT*ST-KIND NIL) PREDICATE 14 "APPLY" NIL ELEM (VERKN ELEM ELEM) NIL NIL NIL
          NIL NIL 3 ELEM (DT*ST-KIND NIL) FUNCTION 14 "INVERS" NIL ELEM (VERKN ELEM) NIL NIL
          NIL NIL NIL 2 ELEM (DT*ST-KIND NIL) FUNCTION 5 VERKN NIL
          (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 MENGE NIL
          (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 ELEM NIL (ST*DATA NIL DT*ST-KIND SYS-VAR)
          VARIABLE 5 ELEM NIL (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 ELEM NIL
          (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 15 "G" NIL NIL (ANY ANY ANY) NIL NIL
          ((- 9 (POSITIVE))) ((+ 9 (NEGATIVE))) ((+ 9 (NIL))) ((- 9 (NIL))) NIL NIL
          (DT*ST-KIND NIL) PREDICATE 15 "EL" NIL NIL (ANY ANY) NIL NIL ((- 10 (POSITIVE)))
          ((+ 10 (NEGATIVE))) ((+ 10 (NIL))) ((- 10 (NIL))) NIL NIL (DT*ST-KIND NIL) PREDICATE
          5 VERKN NIL (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 ELEM NIL
          (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 MENGE NIL
          (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 ELEM NIL (ST*DATA NIL DT*ST-KIND SYS-VAR)
          VARIABLE 5 MENGE NIL (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 MENGE NIL
          (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 VERKN NIL
          (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 ELEM NIL (ST*DATA NIL DT*ST-KIND SYS-VAR)
          VARIABLE 15 "UG" NIL NIL (ANY ANY ANY ANY) NIL NIL ((- 19 (POSITIVE)))
          ((+ 19 (NEGATIVE))) ((+ 19 (NIL))) ((- 19 (NIL))) NIL NIL (DT*ST-KIND NIL) PREDICATE
          5 VERKN NIL (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 MENGE NIL
          (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 MENGE NIL
          (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 ELEM NIL (ST*DATA NIL DT*ST-KIND SYS-VAR)
          VARIABLE 15 "ME" NIL NIL (ANY ANY) NIL NIL ((- 26 (POSITIVE))) ((+ 26 (NEGATIVE)))
          ((+ 26 (NIL))) ((- 26 (NIL))) NIL NIL (DT*ST-KIND NIL) PREDICATE 5 ELEM NIL
          (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 ELEM NIL (ST*DATA NIL DT*ST-KIND SYS-VAR)
          VARIABLE))
       (INCREMENT (- MEM*SIZE 300000))
       COUNTER1)
      (MEM-RESET)
      (COND ((> MEM*SIZE 300000)
             (SETQ COUNTER1 29)
             (MAPC #'(LAMBDA (RADDR)
                       (SETF (AREF MEM*MEMORY (DECF COUNTER1))
                              (COND ((EQL RADDR 'ATP.MEMORY.NIL) RADDR)
                                    ((EQL 'END RADDR) RADDR)
                                    ((OR (EQL RADDR 0)
                                         (MINUSP RADDR))
                                     RADDR)
                                    (T (+ RADDR INCREMENT)))))
                   ADDRLIST)
             (SETQ COUNTER1 MEM*SIZE)
             (MAPC #'(LAMBDA (DATA) (SETF (AREF MEM*MEMORY (DECF COUNTER1)) DATA)) DATALIST))
            (T (UNLESS (= MEM*SIZE 300000)
                 (MEM-INITIALIZE 300000))
               (SETQ COUNTER1 29)
               (MAPC #'(LAMBDA (RADDR) (SETF (AREF MEM*MEMORY (DECF COUNTER1)) RADDR))
                     ADDRLIST)
               (SETQ COUNTER1 MEM*SIZE)
               (MAPC #'(LAMBDA (DATA) (SETF (AREF MEM*MEMORY (DECF COUNTER1)) DATA)) DATALIST))
            )
      (SETQ MEM*NEXT.RADR (IF (> MEM*SIZE 300000) (+ 299786 INCREMENT) 299786))
      (SETQ MEM*NEXT.VADR 29
            MEM*REST (- MEM*NEXT.RADR MEM*NEXT.VADR -1)
            MEM*FIRST.REUSABLE.VADR NIL
            MEM*LAST.REUSABLE.VADR NIL))

(PROGN (SETQ DT*SORT.ALL (QUOTE (VERKN MENGE ELEM ANY))) (SETQ DT*SORT.NR (QUOTE 5)) (SETQ DT*SORT.PROPERTIES (QUOTE (DT*MAX.SUBSORTS DT*LEAST.SUPERSORTS DT*TRANSITIVE.CLOSURE DT*INVERSE.TRANSITIVE.CLOSURE DT*MINIMAL.SUBSORTS DT*DIRECT.SUBSORTS DT*DIRECT.SUPERSORTS DT*DISJOINT.SORTS DT*COMPLETION.SORT))) (SETQ DT*SORT.COMMON.COMPUTE.FLAG (QUOTE NIL)) (SETQ DT*VARIABLE.COUNTER (QUOTE 0)) (SETQ DT*CONSTANT.COUNTER (QUOTE 0)) (SETQ DT*CONSTANT.ALL (QUOTE NIL)) (SETQ DT*ABBREVIATIONS (QUOTE NIL)) (SETQ DT*FUNCTION.COUNTER (QUOTE 0)) (SETQ DT*FUNCTION.ALL (QUOTE (3 2))) (SETQ DT*FUNCTION.ADMISSIBLE.THEORIES (QUOTE (ASSOCIATIVE))) (SETQ DT*FUNCTION.ACTUAL.THEORIES (QUOTE NIL)) (SETQ DT*FUNCTION.WITH.ARGUMENT.SYMMETRIES (QUOTE NIL)) (SETQ DT*FUNCTION.COMPONENTS (QUOTE (PNAME ATTRIBUTES MAX.RANGE.SORT MAX.DOMAIN.SORTS MIN.RANGE.SORTS SORT.LIST SORT.LIST.INVERSE SORT.TREE.CALC ARGUMENT.SYMMETRIES ARITY G.L.B.OF.RANGES))) (SETQ DT*PREDICATE.ADMISSABLE.ATTRIBUTES (QUOTE (SYMMETRIC DEFINED REFLEXIVE))) (SETQ DT*PREDICATE.COUNTER (QUOTE 0)) (SETQ DT*EQUALITY.SYMBOLS (QUOTE ("=" ":=" "=:" ":=:"))) (SETQ DT*EQUALITY.PREDICATES (QUOTE NIL)) (SETQ DT*NONEQUALITY.PREDICATES (QUOTE (26 19 10 9 1 0))) (SETQ DT*PREDICATE.ALL (QUOTE (26 19 10 9 1 0))) (SETQ DT*PREDICATE.WITH.ATTRIBUTES (QUOTE NIL)) (SETQ DT*PREDICATE.COMPONENTS (QUOTE (PNAME POSITIVE.OCCURRENCES NEGATIVE.OCCURRENCES DOMAINSORTS ATTRIBUTES REFL.CLAUSE +ROTHERSIDES -ROTHERSIDES +SOTHERSIDES -SOTHERSIDES +TOTHERSIDES -TOTHERSIDES))) (SETQ DT*TRUE.PREDICATE (QUOTE 0)) (SETQ DT*FALSE.PREDICATE (QUOTE 1)) (SETQ DT*UNI.CREATES.VARIABLES (QUOTE NIL)) (SETQ DT*SIGN.MINUS.SYMBOLS (QUOTE (- --))) (SETQ DT*SIGN.PLUS.SYMBOLS (QUOTE (+ ++))) (SETQ DT*SYMBOL.KINDS (QUOTE (CONSTANT.ALL FUNCTION.ALL PREDICATE.ALL)))) 
(PROGN) 
(PROGN (PROGN)) 
(PROGN (PROGN (SETF (GET (QUOTE VERKN) (QUOTE DT*DIRECT.SUBSORTS)) (QUOTE NIL)) (SETF (GET (QUOTE VERKN) (QUOTE DT*SORT.NUMBER)) (QUOTE 4)) (SETF (GET (QUOTE VERKN) (QUOTE DT*TRANSITIVE.CLOSURE)) (QUOTE (VERKN))) (SETF (GET (QUOTE VERKN) (QUOTE DT*MAX.SUBSORTS)) (QUOTE ((VERKN VERKN) (MENGE) (ELEM) (ANY VERKN)))) (SETF (GET (QUOTE VERKN) (QUOTE DT*MINIMAL.SUBSORTS)) (QUOTE (VERKN))) (SETF (GET (QUOTE VERKN) (QUOTE DT*DIRECT.SUPERSORTS)) (QUOTE (ANY))) (SETF (GET (QUOTE VERKN) (QUOTE DT*INVERSE.TRANSITIVE.CLOSURE)) (QUOTE (ANY VERKN)))) (PROGN (SETF (GET (QUOTE MENGE) (QUOTE DT*DIRECT.SUBSORTS)) (QUOTE NIL)) (SETF (GET (QUOTE MENGE) (QUOTE DT*SORT.NUMBER)) (QUOTE 3)) (SETF (GET (QUOTE MENGE) (QUOTE DT*TRANSITIVE.CLOSURE)) (QUOTE (MENGE))) (SETF (GET (QUOTE MENGE) (QUOTE DT*MAX.SUBSORTS)) (QUOTE ((VERKN) (MENGE MENGE) (ELEM) (ANY MENGE)))) (SETF (GET (QUOTE MENGE) (QUOTE DT*MINIMAL.SUBSORTS)) (QUOTE (MENGE))) (SETF (GET (QUOTE MENGE) (QUOTE DT*DIRECT.SUPERSORTS)) (QUOTE (ANY))) (SETF (GET (QUOTE MENGE) (QUOTE DT*INVERSE.TRANSITIVE.CLOSURE)) (QUOTE (ANY MENGE)))) (PROGN (SETF (GET (QUOTE ELEM) (QUOTE DT*DIRECT.SUBSORTS)) (QUOTE NIL)) (SETF (GET (QUOTE ELEM) (QUOTE DT*SORT.NUMBER)) (QUOTE 2)) (SETF (GET (QUOTE ELEM) (QUOTE DT*TRANSITIVE.CLOSURE)) (QUOTE (ELEM))) (SETF (GET (QUOTE ELEM) (QUOTE DT*MAX.SUBSORTS)) (QUOTE ((VERKN) (MENGE) (ELEM ELEM) (ANY ELEM)))) (SETF (GET (QUOTE ELEM) (QUOTE DT*MINIMAL.SUBSORTS)) (QUOTE (ELEM))) (SETF (GET (QUOTE ELEM) (QUOTE DT*DIRECT.SUPERSORTS)) (QUOTE (ANY))) (SETF (GET (QUOTE ELEM) (QUOTE DT*INVERSE.TRANSITIVE.CLOSURE)) (QUOTE (ANY ELEM)))) (PROGN (SETF (GET (QUOTE ANY) (QUOTE DT*SORT.NUMBER)) (QUOTE 1)) (SETF (GET (QUOTE ANY) (QUOTE DT*DIRECT.SUBSORTS)) (QUOTE (VERKN MENGE ELEM))) (SETF (GET (QUOTE ANY) (QUOTE DT*TRANSITIVE.CLOSURE)) (QUOTE (ANY VERKN MENGE ELEM))) (SETF (GET (QUOTE ANY) (QUOTE DT*MAX.SUBSORTS)) (QUOTE ((VERKN VERKN) (MENGE MENGE) (ELEM ELEM) (ANY ANY)))) (SETF (GET (QUOTE ANY) (QUOTE DT*MINIMAL.SUBSORTS)) (QUOTE (MENGE ELEM))) (SETF (GET (QUOTE ANY) (QUOTE DT*DIRECT.SUPERSORTS)) (QUOTE NIL)) (SETF (GET (QUOTE ANY) (QUOTE DT*INVERSE.TRANSITIVE.CLOSURE)) (QUOTE (ANY))))) ))