;;; -*- Mode: LISP; Package: MKRP; Syntax: Common-lisp -*-
(* AXIOMS FOR PROBLEM 41 :)
(* THERE ARE TWO PEOPLE
A AND B.)
(* EACH OF WHOM IS EITHER A KNIGHT,OR A KNAVE,OR A NORMAL.)
(* A
SAYS :B IS A KNIGHT.)
(* B SAYS : A IS A KNAVE %.)
(* PROVE: EITHER ONE OF
THEM IS TELLING THE TRUTH BUT IS NOT A KNIGHT OR ONE OF THEM IS LYING BUT IS NOT A KNAVE.)
(*)
(* KNIGHT2 (X Y) MEANS X SAYS Y IS A KNIGHT.)
(* KNAVE2 (X Y) MEANS X SAYS
Y IS A KNAVE.)
(* TRUTH (X) MEANS X SAYS THE TRUTH.)
(* LIE (X) MEANS X IS
TELLING A LIE.)
(*)
(ALL X NORMAL (X) EQV NOT KNIGHT (X) AND NOT KNAVE (X))
(ALL X KNAVE (X) EQV NOT NORMAL (X) AND NOT KNIGHT (X))
(ALL X KNIGHT (X) EQV NOT NORMAL (X) AND NOT KNAVE (X))
(ALL X,Y KNIGHT2 (X Y) AND KNAVE (X) IMPL NOT KNIGHT (Y))
(ALL X,Y KNIGHT2 (X Y) AND KNIGHT
(X) IMPL KNIGHT (Y))
(ALL X,Y KNAVE2 (X Y) AND KNIGHT (X) IMPL KNAVE (Y))
(ALL X,Y KNAVE2 (X Y) AND KNAVE (X) IMPL NOT KNAVE
(Y))
(ALL X,Y KNIGHT2 (X Y) AND TRUTH (X) IMPL KNIGHT (Y))
(ALL X,Y KNIGHT2 (X Y) AND LIE (X) IMPL NOT KNIGHT (Y))
(ALL
X,Y KNAVE2 (X Y) AND TRUTH (X) IMPL KNAVE (Y))
(ALL X,Y KNAVE2 (X Y) AND LIE (X) IMPL NOT KNAVE (Y))
(ALL X,Y KNIGHT2 (X Y)
AND KNIGHT (Y) IMPL TRUTH (X))
(ALL X,Y KNIGHT2 (X Y) AND NOT KNIGHT (Y) IMPL LIE (X))
(ALL X,Y KNAVE2 (X Y) AND KNAVE
(Y) IMPL TRUTH (X))
(ALL X,Y KNAVE2 (X Y) AND NOT KNAVE (Y) IMPL LIE (X))
(ALL X TRUTH (X) EQV NOT LIE (X))
(ALL X TRUTH
(X) IMPL NORMAL (X) OR KNIGHT (X))
(ALL X LIE (X) IMPL KNAVE (X) OR NORMAL (X))
(KNIGHT2 (A B))
(KNAVE2 (B A))

((TRUTH (B) impl NOT KNIGHT (B))
 and (not TRUTH (b) impl (lie(a) and NOT KNIGHT (A))))