;;; -*- Package: MKRP; Mode: LISP; Syntax: Common-lisp -*-

  
  
(SORT ELEMENT,MENGE,VERKN,ABB,NAT : ANY)
(TYPE APPLYV(VERKN ELEMENT ELEMENT) : ELEMENT)
(TYPE CONC : VERKN)
(TYPE W(MENGE) :MENGE)
(TYPE LENGTH(ELEMENT) : NAT)
(TYPE APPLYA(ABB ELEMENT) : ELEMENT)
(TYPE M: NAT)
(ALL X:         ELEMENT ALL A,B:MENGE ALL PHI:ABB EL(X W(B)) AND KLEINER(LENGTH(X) M)
     IMPL (EX Y:ELEMENT EL(Y W(A)) AND GLEICH(APPLYA(PHI Y) X)))
(ALL X:ELEMENT  ALL B:MENGE  
     EL(X W(B)) AND GLEICH(LENGTH(X) M)
     IMPL( EX U,V:ELEMENT        EL(U W(B))
	  AND EL(V W(B))
	  AND KLEINER(LENGTH(U) M)
	  AND KLEINER(LENGTH(V) M)
	  AND GLEICH(APPLYV(CONC U V) X)))
(ALL A,B:MENGE  ALL PHI:ABB  ALL X:ELEMENT  ALL U,V,T,S:ELEMENT  
     GLEICH(APPLYV(CONC U V) X)
     AND EL(X W(B))
     AND EL(T W(A))
     AND EL(S W(A))
     AND GLEICH(APPLYA(PHI T) U)
     AND GLEICH(APPLYA(PHI S) V)
     AND HOMOMORPH(PHI W(A) W(B))
     IMPL GLEICH(APPLYA(PHI APPLYV(CONC T S)) X) AND EL(APPLYV(CONC T S) W(A)))
  
(ALL X:ELEMENT  ALL A,B:MENGE  ALL PHI:ABB  
     EL(X W(B)) AND GLEICH(LENGTH(X) M) AND HOMOMORPH(PHI W(A) W(B))
     IMPL (EX Y:ELEMENT EL(Y W(A)) AND GLEICH(APPLYA(PHI Y) X)))
  
 
 