;;; -*- Package: MKRP; Mode: LISP; Syntax: Common-lisp -*-   

(SORT ELEM,MENGE,VERK:ANY)
(TYPE APPLY (VERK ELEM ELEM) :ELEM)
(TYPE INVERS (VERK ELEM) :ELEM)
(ALL PHI:VERK  ALL F:MENGE  ALL X,E:ELEM  
     G (F PHI E) AND EL (X F) IMPL APPLY (PHI INVERS (PHI X) X) = E)
(ALL U,V:MENGE ALL X:ELEM ME (U V) AND EL (X U) IMPL EL (X V))
(ALL U,F:MENGE  ALL PHI:VERK  ALL E:ELEM  
     UG (U F PHI E) IMPL ME (U F) AND G (U PHI E))
(ALL F:MENGE  ALL PHI:VERK  ALL E:ELEM  EX X:ELEM  
     G (F PHI E) IMPL EL (X F))

(ALL PHI:VERK  ALL F,U:MENGE  ALL E1,E2:ELEM  
     G (F PHI E1) AND UG (U F PHI E2) IMPL E1 = E2)