;;; -*- Mode: LISP; Package: MKRP; Syntax: Common-lisp -*-
(POSSIBLE  
  (MISSIONARIES.LEFT  
    (S (S (S (0))))
    CANNIBALS.LEFT  
    (S (S (S (0))))
    BOAT  
    (LEFT)
    CANNIBALS.RIGHT  
    (0)
    MISSIONARIES.RIGHT  
    (0)))
          
;;; * TRAVERSING RULES:
         
(ALL V,W,Y,Z  
     POSSIBLE  
     (MISSIONARIES.LEFT (S (V)) CANNIBALS.LEFT (W) BOAT (LEFT) CANNIBALS.RIGHT (Y) MISSIONARIES.RIGHT (Z))
     IMPL  
     REACHABLE  
     (MISSIONARIES.LEFT (V) CANNIBALS.LEFT (W) BOAT (RIGHT) CANNIBALS.RIGHT (Y) MISSIONARIES.RIGHT (S
			(Z))))

(ALL V,W,Y,Z  
     POSSIBLE  
     (MISSIONARIES.LEFT (V) CANNIBALS.LEFT (S (W)) BOAT (LEFT) CANNIBALS.RIGHT (Y) MISSIONARIES.RIGHT (Z))
     IMPL  
     REACHABLE  
     (MISSIONARIES.LEFT (V) CANNIBALS.LEFT (W) BOAT (RIGHT) CANNIBALS.RIGHT (S (Y)) MISSIONARIES.RIGHT (Z)))

(ALL V,W,Y,Z  
     POSSIBLE  
     (MISSIONARIES.LEFT (S (S (V))) CANNIBALS.LEFT (W) BOAT (LEFT) CANNIBALS.RIGHT (Y) MISSIONARIES.RIGHT (Z))
     IMPL  
     REACHABLE  
     (MISSIONARIES.LEFT  
       (V)
       CANNIBALS.LEFT  
       (W)
       BOAT  
       (RIGHT)
       CANNIBALS.RIGHT  
       (Y)
       MISSIONARIES.RIGHT  
       (S (S (Z)))))

(ALL V,W,Y,Z  
     POSSIBLE  
     (MISSIONARIES.LEFT (V) CANNIBALS.LEFT (S (S (W))) BOAT (LEFT) CANNIBALS.RIGHT (Y) MISSIONARIES.RIGHT (Z))
     IMPL  
     REACHABLE  
     (MISSIONARIES.LEFT  
       (V)
       CANNIBALS.LEFT  
       (W)
       BOAT  
       (RIGHT)
       CANNIBALS.RIGHT  
       (S (S (Y)))
       MISSIONARIES.RIGHT  
       (Z)))

(ALL V,W,Y,Z  
     POSSIBLE  
     (MISSIONARIES.LEFT (S (V)) CANNIBALS.LEFT (S (W)) BOAT (LEFT) CANNIBALS.RIGHT (Y) MISSIONARIES.RIGHT (Z))
     IMPL  
     REACHABLE  
     (MISSIONARIES.LEFT  
       (V)
       CANNIBALS.LEFT  
       (W)
       BOAT  
       (RIGHT)
       CANNIBALS.RIGHT  
       (S (Y))
       MISSIONARIES.RIGHT  
       (S (Z))))

(ALL V,W,Y,Z  
     POSSIBLE  
     (MISSIONARIES.LEFT (V) CANNIBALS.LEFT (W) BOAT (RIGHT) CANNIBALS.RIGHT (Y) MISSIONARIES.RIGHT (S
												     (Z)))
     IMPL  
     REACHABLE  
     (MISSIONARIES.LEFT (S (V)) CANNIBALS.LEFT (W) BOAT (LEFT) CANNIBALS.RIGHT (Y) MISSIONARIES.RIGHT (Z)))

(ALL V,W,Y,Z  
     POSSIBLE  
     (MISSIONARIES.LEFT (V) CANNIBALS.LEFT (W) BOAT (RIGHT) CANNIBALS.RIGHT (S (Y)) MISSIONARIES.RIGHT (Z))
     IMPL  
     REACHABLE  
     (MISSIONARIES.LEFT (V) CANNIBALS.LEFT (S (W)) BOAT (LEFT) CANNIBALS.RIGHT (Y) MISSIONARIES.RIGHT (Z)))

(ALL V,W,Y,Z  
     POSSIBLE  
     (MISSIONARIES.LEFT  
       (V)
       CANNIBALS.LEFT  
       (W)
       BOAT  
       (RIGHT)
       CANNIBALS.RIGHT  
       (Y)
       MISSIONARIES.RIGHT  
       (S (S (Z))))
     IMPL  
     REACHABLE  
     (MISSIONARIES.LEFT (S (S (V))) CANNIBALS.LEFT (W) BOAT (LEFT) CANNIBALS.RIGHT (Y) MISSIONARIES.RIGHT (Z)))

(ALL V,W,Y,Z  
     POSSIBLE  
     (MISSIONARIES.LEFT  
       (V)
       CANNIBALS.LEFT  
       (W)
       BOAT  
       (RIGHT)
       CANNIBALS.RIGHT  
       (S (S (Y)))
       MISSIONARIES.RIGHT  
       (Z))
     IMPL  
     REACHABLE  
     (MISSIONARIES.LEFT (V) CANNIBALS.LEFT (S (S (W))) BOAT (LEFT) CANNIBALS.RIGHT (Y) MISSIONARIES.RIGHT (Z)))

(ALL V,W,Y,Z  
     POSSIBLE  
     (MISSIONARIES.LEFT  
       (V)
       CANNIBALS.LEFT  
       (W)
       BOAT  
       (RIGHT)
       CANNIBALS.RIGHT  
       (S (Y))
       MISSIONARIES.RIGHT  
       (S (Z)))
     IMPL  
     REACHABLE  
     (MISSIONARIES.LEFT (S (V)) CANNIBALS.LEFT (S (W)) BOAT (LEFT) CANNIBALS.RIGHT (Y) MISSIONARIES.RIGHT (Z)))

;;; ADMISSIBILITY CONDITION:
           
(ALL V,W,X,Y,Z  
     REACHABLE  
     (MISSIONARIES.LEFT (V) CANNIBALS.LEFT (W) BOAT (X) CANNIBALS.RIGHT (Y) MISSIONARIES.RIGHT (Z))
     AND  
     NOT OUTNUMBER (W V)
     AND  
     NOT OUTNUMBER (Y Z)
     IMPL  
     POSSIBLE (MISSIONARIES.LEFT (V) CANNIBALS.LEFT (W) BOAT (X) CANNIBALS.RIGHT (Y) MISSIONARIES.RIGHT
				 (Z)))
           
;;; AUXILIARY DEFINITIONS:
           
(ALL X NOT OUTNUMBER (X 0))
(ALL X NOT OUTNUMBER (X X))
(ALL X NOT OUTNUMBER (X S (X)))
(ALL X NOT OUTNUMBER (X S (S (X))))
(ALL X NOT OUTNUMBER (X S (S (S (X)))))
 
;;; THEOREMS :
(POSSIBLE  
  (MISSIONARIES.LEFT  
    (0)
    CANNIBALS.LEFT  
    (0)
    BOAT  
    (RIGHT)
    CANNIBALS.RIGHT  
    (S (S (S (0))))
    MISSIONARIES.RIGHT  
    (S (S (S (0))))))
 
