;;; -*- Mode: Lisp; Package: MKRP; Base: 10.; Syntax: Common-lisp -*-
((P1 OR P2 OR P3)
 AND  
 (P4 OR P5 OR P6)
 AND  
 (P7 OR Q1 OR Q2)
 AND  
 (P10 OR P11 OR P12)
 AND  
 (NOT P1 OR NOT P4)
 AND  
 (NOT P1 OR NOT P7)
 AND  
 (NOT P1 OR NOT P10)
 AND  
 (NOT P4 OR NOT P7)
 AND  
 (NOT P4 OR NOT P10)
 AND  
 (NOT P7 OR NOT P10)
 AND  
 (NOT P2 OR NOT P5)
 AND  
 (NOT P2 OR NOT Q1)
 AND  
 (NOT P2 OR NOT P11)
 AND  
 (NOT P5 OR NOT Q1)
 AND  
 (NOT P5 OR NOT P11)
 AND  
 (NOT Q1 OR NOT P11)
 AND  
 (NOT P3 OR NOT P6)
 AND  
 (NOT P3 OR NOT Q2)
 AND  
 (NOT P3 OR NOT P12)
 AND  
 (NOT P6 OR NOT Q2)
 AND  
 (NOT P6 OR NOT P12)
 AND  
 (NOT Q2 OR NOT P12))


