;;; -*- Package: MKRP; Base: 10; Mode: LISP; Syntax: Common-lisp -*-

(CONSTRUCTION  "Genera 8.0.1 Logical Pathnames Translation Files NEWEST IP-TCP 422.2 RPC 415.0 Embedding Support 407.0 UX Support 416.0 Experimental Network RPC 415.0 Experimental NFS Client 415.0 CLX 419.0 C Runtime 416.0 Compiler Tools Package 411.0 Compiler Tools Runtime 411.0 C Packages 413.0 Minimal Lexer Runtime 416.0 Lexer Package 415.0 Syntax Editor Runtime 411.0 Experimental X Server 409.0 X Remote Screen 418.1 KKL 20.1 HADES 16.0 Waltz 7.0 COLUMN 7.0 MKRP 49.10 GENTRAFO 1.0" "24-NOV,1991 23:28" 
   ("                                                                                                                     "
   "*********************************************************************************************************************"
   "                                                                                                                     "
   " FORMULA:  Date: 24-NOV,1991 23:28"
   "           Axioms und Theorems for this proof have been read from"
   "              Axiom-File: NIL"
   "            Theorem-File: NIL"
   "                                                                                                                     "
   "*********************************************************************************************************************"
   ))

(AXIOMS.INFIX    ((* AXIOMS *)
   (* GROUP *)
   (AC (+))
   (ALL X + (0 X) = X)
   (ALL X + (- (X) X) = 0)
   (* * *)
   (ALL |X,Y,Z| * (* (X Y) Z) = * (X * (Y Z)))
   (* * GROUP CONNECTION *)
   (ALL |X,Y,Z| * (+ (X Y) Z) = + (* (X Z) * (Y Z)))
   (ALL |X,Y,Z| * (Z + (X Y)) = + (* (Z X) * (Z Y)))
   (* ADDITIONAL AXIOM AND THEOREM *)
   (ALL X * (X * (X X)) = X)))

(THEOREMS.INFIX ((ALL |X,Y| * (X Y) = * (Y X))))

(AXIOMS.PREFIX   (COMMENT
   COMMENT
   (+ 0 NIL NIL)
   (ALL 4 (+ 2 ((3 5 4) 4) NIL))
   (ALL 6 (+ 2 ((3 (7 6) 6) 5) NIL))
   COMMENT
   (ALL 10 (ALL 9 (ALL 8 (+ 2 ((11 (11 8 9) 10) (11 8 (11 9 10))) NIL))))
   COMMENT
   (ALL 14 (ALL 13 (ALL 12 (+ 2 ((11 (3 12 13) 14) (3 (11 12 14) (11 13 14))) NIL))))
   (ALL 17 (ALL 16 (ALL 15 (+ 2 ((11 17 (3 15 16)) (3 (11 17 15) (11 17 16))) NIL))))
   COMMENT
   (ALL 18 (+ 2 ((11 18 (11 18 18)) 18) NIL))))

(THEOREMS.PREFIX ((ALL 20 (ALL 19 (+ 2 ((11 19 20) (11 20 19)) NIL)))))

(OPTIONS (TWO_RULES)
    (TWO_RULES.MAXLEVEL . 1)
    (TWO_SUPPRESS.NORULES)
    (RED.I_CLAUSE.MULTIPLE.LITERALS . T)
    (RED.I_CLAUSE.PURITY . PARTIAL)
    (RED.I_CLAUSE.TAUTOLOGY . T)
    (RED.I_CLAUSE.TAUTOLOGY.RECHECK . PARTIAL)
    (RED.I_CLAUSE.SUBSUMPTION . T)
    (RED.I_CLAUSE.SUBSUMPTION.RECHECK . PARTIAL)
    (RED.I_CLAUSE.REPL.FACTORING . T)
    (RED.I_CLAUSE.REPL.FACTORING.RECHECK . T)
    (RED.I_CLAUSE.REPL.RESOLUTION . SIMPLE)
    (RED.I_CLAUSE.REPL.RESOLUTION.RECHECK . T)
    (RED.I_CLAUSE.REWRITING . DEM)
    (RED.I_LINK.INCOMPATIBILITY . T)
    (RED.I_LINK.TAUTOLOGY . REMOVE-INHIBIT)
    (RED.I_LINK.TAUTOLOGY.RECHECK)
    (RED.I_LINK.SUBSUMPTION . REMOVE-INHIBIT)
    (RED.I_LINK.SUBSUMPTION.RECHECK)
    (RED.D_CLAUSE.MULTIPLE.LITERALS . T)
    (RED.D_CLAUSE.PURITY . PARTIAL)
    (RED.D_CLAUSE.TAUTOLOGY . REMOVE-INHIBIT)
    (RED.D_CLAUSE.TAUTOLOGY.RECHECK)
    (RED.D_CLAUSE.SUBSUMPTION.FORWARD . REMOVE-INHIBIT)
    (RED.D_CLAUSE.SUBSUMPTION.BACKWARD . REMOVE)
    (RED.D_CLAUSE.SUBSUMPTION.RECHECK)
    (RED.D_CLAUSE.REPL.FACTORING . T)
    (RED.D_CLAUSE.REPL.FACTORING.RECHECK . T)
    (RED.D_CLAUSE.REPL.RESOLUTION . SIMPLE)
    (RED.D_CLAUSE.REPL.RESOLUTION.RECHECK . T)
    (RED.D_CLAUSE.REWRITING . DEM)
    (RED.D_LINK.INCOMPATIBILITY . T)
    (RED.D_LINK.TAUTOLOGY . REMOVE-INHIBIT)
    (RED.D_LINK.TAUTOLOGY.RECHECK)
    (RED.D_LINK.SUBSUMPTION . REMOVE-INHIBIT)
    (RED.D_LINK.SUBSUMPTION.RECHECK)
    (FAC_INITIAL)
    (FAC_EACH.STEP)
    (STR_RESOLUTION . SET-OF-SUPPORT)
    (STR_R.SELECTION * 10 (+ 2 VARIABLES (* 2 DEPTH) (* 3 NOLIT)))
    (STR_LINK.DEPTH)
    (STR_TERM.DEPTH)
    (STR_FINITE.DOMAIN . T)
    (TERM_UNITS . T)
    (TERM_ITERATIONS . 0)
    (TERM_SET.OF.SUPPORT)
    (TERM_BREADTH.FIRST)
    (SORT_LITERALS)
    (ER_PARAMODULATION . HEURISTIC-COMPLETION)
    (ER_P.SELECTION * WEIGHT (IF SUPPORT 1 1.5) (IF EQUATIONAL 1 2))
    (ER_COMPLETION . UNFAILING)
    (ER_CP.REDUCTION . T)
    (ER_ORDERING . POLYNOMIAL)
    (ER_OPERATOR.ORDERING * - + 0 1)
    (ER_KNUTH.BENDIX.WEIGHT (+ 1) (* 1) (- 0) (0 1) (1 1))
    (ER_POLYNOMIAL.WEIGHT (+ (X Y) (+ (* X Y) X)) (* (X Y) (+ (* X Y) X)) (- (X) (* X X)) (0 NIL 3) (1 NIL 3))
    (ER_NARROW.DEPTH . 0)
    (ER_NARROW.NEXT . DEPTH)
    (ER_NARROW.TEST NORM C DELTA SL N)
    (ER_COMPILE)
    (GEN_SPLITTING . 0)
    (GEN_PRESIMPLIFICATION . T)
    (GEN_MIN.EXPRESSION.LENGTH.FOR.FILE)
    (GEN_MIN.EXPRESSION.SIZE.FOR.FILE)
    (GEN_MANUAL.CONTROL)
    (GEN_MAXIMUM.STEPS)
    (GEN_GRAPH.SAVING)
    (GEN_SAVE.FILE . SAVEDEFAULT)
    (GEN_LISP.GARBAGE.COLLECTION)
    (GEN_COMMON.LISP)
    (TR_PREPROCESSING)
    (TR_STEP.MODE . LR)
    (TR_DUMP)
    (TR_CLAUSE.MODE . I)
    (TR_LINK.MODE . I)
    (TR_TRACE.FILE)
    (TR_TERMINAL . T)
    (PR_LATEX)
    (PR_INFIX.FORM . T)
    (PR_PREFIX.FORM)
    (PR_OPTIONS)
    (PR_AXIOM.CLAUSES . T)
    (PR_SYMBOLS)
    (PR_DIRECT.PROOF . T)
    (PR_VARIABLE.PRINT.NAMES X Y Z U V W XX YY ZZ UU VV WW XXX YYY ZZZ UUU VVV WWW)
    (PR_PROTOCOL . T)
    (PR_LEFT.MARGIN . 3)
    (PR_RIGHT.MARGIN . 117)
    (PR_LINELENGTH . 114)
    (PR_LITERALS)
   )

(LINK.COLOURS (R RIW RD S SI SIW SID T TI TIW P PIW PD RIWD))

(AXIOMS (START.TIME 75595506)
   (PARTIAL   (CLAUSE 23 R.= AXIOM ((21 . ANY)) ((+ 2 (21 21)) ))(CLAUSE 30 A.+ NIL ((26 . ANY)(25 . ANY)(24 . ANY)) ((+ 2 ((3 24 (3 25 26)) (3 (3 24 25) 26))) ))(CLAUSE 32 A1 AXIOM ((4 . ANY)) ((+ 2 ((3 5 4) 4)) )))
   (PARTIAL   (CLAUSE 54 A2 AXIOM ((6 . ANY)) ((+ 2 ((3 (7 6) 6) 5)) )))
   (PARTIAL   (CLAUSE 80 A3 AXIOM ((10 . ANY)(9 . ANY)(8 . ANY)) ((+ 2 ((11 (11 8 9) 10) (11 8 (11 9 10)))) )))
   (PARTIAL   (CLAUSE 88 A4 AXIOM ((14 . ANY)(13 . ANY)(12 . ANY)) ((+ 2 ((11 (3 12 13) 14) (3 (11 12 14) (11 13 14)))) )))
   (PARTIAL   (CLAUSE 98 A5 AXIOM ((16 . ANY)(15 . ANY)(17 . ANY)) ((+ 2 ((11 17 (3 15 16)) (3 (11 17 15) (11 17 16)))) )))
   (PARTIAL   (CLAUSE 110 A6 AXIOM ((18 . ANY)) ((+ 2 ((11 18 (11 18 18)) 18)) )))
   (END.TIME 75623769)
   (FINAL 23 30 32 54 80 88 98 110)
   (SYMBOLS 
   (LET (NEW.ADDRESS)
   (LIST (PROG1 (CONS    2 (SETQ NEW.ADDRESS (DT-PREDICATE.CREATE "=" '(ANY ANY))))
   (DT-PREDICATE.ADD.ATTRIBUTES NEW.ADDRESS '(DEFINED SYMMETRIC REFLEXIVE)))
   (PROG1 (CONS    1 (SETQ NEW.ADDRESS (DT-PREDICATE.CREATE "FALSE" 'NIL)))
   (DT-PREDICATE.ADD.ATTRIBUTES NEW.ADDRESS '(DEFINED)))
   (PROG1 (CONS    0 (SETQ NEW.ADDRESS (DT-PREDICATE.CREATE "TRUE" 'NIL)))
   (DT-PREDICATE.ADD.ATTRIBUTES NEW.ADDRESS '(DEFINED)))
   (CONS    5 (DT-CONSTANT.CREATE "0" 'ANY))
   (CONS   11 (DT-FUNCTION.CREATE "*" 'ANY '(ANY ANY) 'NIL))
   (CONS    7 (DT-FUNCTION.CREATE "-" 'ANY '(ANY) 'NIL))
   (PROG1 (CONS    3 (SETQ NEW.ADDRESS (DT-FUNCTION.CREATE "+" 'ANY '(ANY ANY) 'NIL)))
   (DT-FUNCTION.ADD.ATTRIBUTES NEW.ADDRESS '(AC))))))
   (RESULT))

(THEOREMS (SPLITPART.IDENTIFIER 1)
   (START.TIME 75623888)
   (PARTIAL   (CLAUSE 19 T7 THEOREM () ((- 2 ((11 121 120) (11 120 121))) )))
(indices ((19 7) (110 6) (98 5) (88 4) (80 3) (54 2) (32 1) (30 NIL) (23 NIL)))