;;; -*- Mode: Lisp; Package: MKRP; Syntax: Common-lisp -*-
(* )
(* Definitionen der Mengenlehre)
(sort set:any)
(sort element:any)
(type el (element set))
(* Definition 1.3 Kartesisches Produkt)
(type cartes (set set) :set)
(sort rel:set)
(* Definition 1.5: Durchschnitt Sortenproblem!!!!)
(type intersection (rel rel) :rel)
(all a,b:rel all x:element el(x intersection(a b)) eqv el(x a) and el(x b))
(* )
(* Definition von Relationen auf einer festen Menge S)
(type pair (element element) :element)
(type s:set)
(sort el.of.s:element)
(* )
(* Definition 2.5: Reflexiv)
(Type reflexiv (rel))
(all rho:rel reflexiv (rho) eqv (all a:el.of.s el (pair (a a) rho)))
(* Definition 2.6: Symmetrisch)
(type symmetrisch (rel))
(all rho:rel symmetrisch (rho) eqv (all a,b:el.of.s el (pair (a b) rho) impl el (pair (b a) rho)))
(* Definition 7.2 Transitiv)
(type transitive (rel))
(all rho :rel transitiv (rho) eqv (all a,b,c:el.of.s el (pair(a b) rho) and el (pair (b c) rho) impl el (pair (a c) rho)))
(* Definition 2.8 Aequivalenzrelation)
(type eqvrel (rel))
(all rho:rel eqvrel (rho) eqv reflexiv (rho) and symmetrisch (rho) and transitiv(rho))
(sort eqvrelation:rel)
(all rho:eqvrelation reflexiv(rho) and symmetrisch(rho) and transitiv (rho))

(all rho,sigma:eqvrelation eqvrel(intersection (rho sigma)))