;;; -*- Package: MKRP; Base: 10.; Mode: LISP; Syntax: Common-lisp -*- 

(SORT MENGE,ELEMENT,VERKN,ABB :ANY)
(TYPE W(MENGE) :MENGE)
(TYPE BILD(ABB MENGE) :MENGE)
(TYPE EHG(MENGE VERKN) :MENGE)
(TYPE RESTRICTION(ABB MENGE) :MENGE)
(TYPE F:MENGE)
(TYPE INVERS(ABB) :ABB)
(* DEF. FREIES ERZEUGENDES SYSTEM *)
(ALL MAL1:VERKN  ALL E:MENGE  (
			       GLEICH(EHG(E MAL1) F)
			       AND( ALL H:MENGE  ALL PHINULL:ABB  ALL MAL2:VERKN  
				   HG(H MAL2) AND ABBILDUNG(PHINULL E H)
				   IMPL (EX PHI:ABB HOMOMORPH(PHI F H) AND GLEICH(RESTRICTION(PHI E) PHINULL))))
     IMPL FREI(F MAL1))
(ALL X:MENGE  ALL PSI:ABB  ALL MAL2:VERKN  
     HG(F MAL2) AND ISOMORPH(PSI F W(X))
     IMPL ME(BILD(INVERS(PSI) X) F) AND GLEICH(EHG(BILD(INVERS(PSI) X) MAL2) F))
(ALL H,X:MENGE  ALL PHINULL,PSI:ABB  ALL MAL,MALSTR:VERKN  
     HG(F MALSTR) AND ISOMORPH(PSI F W(X)) AND HG(H MAL) AND ABBILDUNG(PHINULL BILD(INVERS(PSI) X) H)
     IMPL (EX PHI:ABB HOMOMORPH(PHI F H) AND GLEICH(RESTRICTION(PHI BILD(INVERS(PSI) X)) PHINULL)))
(ALL A,B:MENGE ALL PHI:ABB ISOMORPH(PHI A B) IMPL HOMOMORPH(PHI A B))
(ALL A,B:MENGE ALL PHI:ABB HOMOMORPH(PHI A B) IMPL ABBILDUNG(PHI A B))

(ALL MALSTR:VERKN ALL PSI:ABB ALL X:MENGE HG(F MALSTR) AND ISOMORPH(PSI F W(X)) IMPL FREI(F MALSTR))




