;;; -*- Mode: LISP; Package: MKRP; Syntax: Common-lisp -*-
(* AXIOMS OF PROBLEM 46 %.)
(* WE HAVE TWO MARRIED
COUPLES ON THE ISLAND OF BAHAVA.)
(* MR AND MRS ABNORMAL AND MR AND MRS BOLD.)
(* MR ABNORMAL SAYS : MR BOLD IS A KNIGHT.)
(* MRS ABNORMAL SAYS : MY HUSBAND IS RIGHT ;MR BOLD
IS A KNIGHT.)
(* MRS BOLD SAYS : THAT IS RIGHT. MY HUSBAND IS INDEED A KNIGHT.)
(*)
(* WHAT ARE THE 4 PEOPLE AND WHICH STATEMENTS ARE TRUE.)
(*)
(* KNIGHT2 (X Y) MEANS X SAYS : Y IS A KNIGHT.)
(*)
(ALL X KNIGHT (X) EQV
NOT KNAVE (X) AND NOT NORMAL (X))
(ALL X NORMAL (X) EQV NOT KNAVE (X) AND NOT KNIGHT (X))
(ALL X KNAVE (X) EQV NOT NORMAL (X) AND NOT KNIGHT (X))
(ALL X,Y MARRIED (X Y) IMPL KNAVE (X) AND KNIGHT (Y) OR KNIGHT (X) AND KNAVE (Y) OR NORMAL (X) AND NORMAL (Y))
(ALL X,Y KNIGHT2 (X Y) AND KNIGHT (X) IMPL KNIGHT
(Y))
(ALL X,Y
KNIGHT2 (X Y) AND KNAVE (X) IMPL NOT KNIGHT (Y))
(MARRIED (MRBOLD MRSBOLD))
(MARRIED
(MRABNORMAL MRSABNORMAL))
(KNIGHT2 (MRABNORMAL MRBOLD))
(KNIGHT2 (MRSABNORMAL MRBOLD))
(KNIGHT2 (MRSBOLD MRBOLD))

(NORMAL (MRABNORMAL) AND NORMAL (MRSABNORMAL) AND NORMAL (MRBOLD) AND
NORMAL (MRSBOLD))