;;; -*- Mode: LISP; Package: MKRP; Syntax: Common-lisp -*-
(* PROBLEM 56)
(*)
(* ONE DAY ALICE
CAME ACROSS JUST ONE OF THE BROTHERS.)
(* HE MADE THE FOLLOWING STATEMENT:)
(*)
(* I AM LYING TODAY OR I AM TWEEDLEDEE.)
(*)
(* WHO
WAS IT?)
(*)
(*)
(* FORMALIZING THE PROBLEM IN FIRST ORDER
LOGIC)
(*)
(TYPE FIRSTONE :PERSON)
(TYPE LION,UNICORN:ANIMAL)
(* LIKE (X Y) MEANS : THE LYING-BEHAVIOR OF X IS LIKE THE ANIMAL Y.)
(ALL X:PERSON
LIKE (X LION) OR LIKE (X UNICORN))
(ALL
X:PERSON NOT (LIKE (X LION) AND LIKE (X UNICORN)))
(*)
(ALL X:DAYS MO (X) EQV (NOT TU (X) AND NOT WE (X) AND NOT TH (X) AND NOT
FR (X) AND NOT SA (X) AND NOT SU (X)))
(ALL X:DAYS TU (X) EQV (NOT MO (X) AND NOT WE (X) AND NOT TH (X) AND NOT
FR (X) AND NOT SA (X) AND NOT SU (X)))
(ALL X:DAYS WE (X) EQV (NOT MO (X) AND NOT TU (X) AND NOT TH (X) AND NOT
FR (X) AND NOT SA (X) AND NOT SU (X)))
(ALL X:DAYS TH (X) EQV (NOT MO (X) AND NOT TU (X) AND NOT WE (X) AND NOT
FR (X) AND NOT SA (X) AND NOT SU (X)))
(ALL X:DAYS FR (X) EQV (NOT MO (X) AND NOT TU (X) AND NOT WE (X) AND NOT
TH (X) AND NOT SA (X) AND NOT SU (X)))
(ALL X:DAYS SA (X) EQV (NOT MO (X) AND NOT TU (X) AND NOT WE (X) AND NOT
TH (X) AND NOT FR (X) AND NOT SU (X)))
(ALL X:DAYS SU (X) EQV (NOT MO (X) AND NOT TU (X) AND NOT WE (X) AND NOT
TH (X) AND NOT FR (X) AND NOT SA (X)))
(*)
(*)
(* THE PREDICATE LAORTWEEDEE
HAS THE FOLLOWING MEANING:)
(* LAORTWEEDEE (X Y) IS TRUE, IF IT IS POSSIBLE FOR X ,TO STATE AT
THE DAY Y:I AM LYING TODAY OR I AM TWEEDLEDEE.)
(*)
(ALL X:PERSON ALL Y:DAYS
NOT MEMBER (Y LYING-DAYS (X)) AND NOT (MEMBER (Y LYING-DAYS (X)) OR TWEEDLEDEE (X)) IMPL NOT LAORTWEEDEE (X Y))
(ALL X:PERSON ALL Y:DAYS NOT MEMBER (Y LYING-DAYS (X))
AND (MEMBER (Y LYING-DAYS (X)) OR TWEEDLEDEE (X)) IMPL LAORTWEEDEE (X Y))
(ALL X:PERSON ALL Y:DAYS MEMBER (Y LYING-DAYS (X)) AND (MEMBER (Y LYING-DAYS (X)) OR TWEEDLEDEE (X)) IMPL NOT
LAORTWEEDEE (X Y))
(ALL X:PERSON ALL Y:DAYS MEMBER (Y LYING-DAYS
(X)) AND NOT (MEMBER (Y LYING-DAYS (X)) OR TWEEDLEDEE (X)) IMPL LAORTWEEDEE (X Y))
(*)
(ALL X:DAYS MEMBER (X LYING-DAYS (LION)) EQV (MO (X) OR TU (X) OR WE (X)))
(ALL X:DAYS MEMBER (X LYING-DAYS (UNICORN)) EQV (TH (X) OR FR (X) OR SA (X)))
(*)
(ALL X:PERSON ALL Y:ANIMAL LIKE (X Y) IMPL (ALL Z:DAYS (MEMBER (Z LYING-DAYS (Y)) EQV MEMBER
(Z LYING-DAYS (X)))))
(*)
(*)
(TYPE TODAY:DAYS)
(LAORTWEEDEE (FIRSTONE TODAY))

(TWEEDLEDEE (FIRSTONE))