;;; -*- Mode: LISP; Package: MKRP; Syntax: Common-lisp -*-
(* PROBLEM 62)
(*)
(* ONE DAY ALICE
MET THE BROTHERS.)
(* SHE ASKED THE FIRSTONE:)
(* DO YOU OWN THE RATTLE?)
(* HE ANSWERED YES.)
(* SHE ASKED THE SECONDONE THE SAME QUESTION.)
(* HE ANSWERED AND ALICE GAVE THE RATTLE TO ONE OF THEM.)
(*)
(* WHO OWNS
THE RATTLE?)
(*)
(* FORMALIZING THE PROBLEM IN FIRST ORDER LOGIC)
(*)
(TYPE FIRSTONE,SECONDONE :PERSON)
(*)
(ALL X:DAYS MO
(X) EQV (NOT TU (X) AND NOT WE (X) AND NOT TH (X) AND NOT FR (X) AND NOT SA (X) AND NOT SU (X)))
(ALL X:DAYS TU
(X) EQV (NOT MO (X) AND NOT WE (X) AND NOT TH (X) AND NOT FR (X) AND NOT SA (X) AND NOT SU (X)))
(ALL X:DAYS WE
(X) EQV (NOT MO (X) AND NOT TU (X) AND NOT TH (X) AND NOT FR (X) AND NOT SA (X) AND NOT SU (X)))
(ALL X:DAYS TH
(X) EQV (NOT MO (X) AND NOT TU (X) AND NOT WE (X) AND NOT FR (X) AND NOT SA (X) AND NOT SU (X)))
(ALL X:DAYS FR
(X) EQV (NOT MO (X) AND NOT TU (X) AND NOT WE (X) AND NOT TH (X) AND NOT SA (X) AND NOT SU (X)))
(ALL X:DAYS SA
(X) EQV (NOT MO (X) AND NOT TU (X) AND NOT WE (X) AND NOT TH (X) AND NOT FR (X) AND NOT SU (X)))
(ALL X:DAYS SU
(X) EQV (NOT MO (X) AND NOT TU (X) AND NOT WE (X) AND NOT TH (X) AND NOT FR (X) AND NOT SA (X)))
(*)
(ALL Y:PERSON TWEEDLEDUM (Y) IMPL (ALL X:DAYS MEMBER (X LYING-DAYS (Y)) EQV (MO (X) OR TU (X) OR WE (X))))
(ALL Y:PERSON TWEEDLEDEE (Y) IMPL (ALL X:DAYS MEMBER (X LYING-DAYS (Y))
EQV (TH (X) OR FR (X) OR SA (X))))
(*)
(*)
(*)
(*)
(* RATTLE-OWNER (X) MEANS: X OWNS THE RATTLE.)
(*)
(RATTLE-OWNER (FIRSTONE) OR RATTLE-OWNER (SECONDONE))
(NOT (RATTLE-OWNER (FIRSTONE) AND RATTLE-OWNER (SECONDONE)))
(*)
(* RATTLE-OWNER2 (X Y) MEANS: X COULD STATE AT DAY Y:
THE RATTLE IS MINE.)
(ALL X:PERSON ALL Y:DAYS NOT RATTLE-OWNER (X) AND NOT MEMBER (Y LYING-DAYS
(X)) IMPL NOT RATTLE-OWNER2 (X Y))
(ALL X:PERSON ALL Y:DAYS RATTLE-OWNER (X) AND NOT MEMBER
(Y LYING-DAYS (X)) IMPL RATTLE-OWNER2 (X Y))
(ALL X:PERSON ALL Y:DAYS RATTLE-OWNER (X) AND MEMBER (Y
LYING-DAYS (X)) IMPL NOT RATTLE-OWNER2 (X Y))
(ALL X:PERSON ALL Y:DAYS NOT RATTLE-OWNER (X) AND MEMBER
(Y LYING-DAYS (X)) IMPL RATTLE-OWNER2 (X Y))
(*)
(* YES (X Y) MEANS: X COULD SAY AT
DAY Y: YES, THE RATTLE IS MINE.)
(ALL X:PERSON ALL Y:DAYS YES (X Y) IMPL RATTLE-OWNER2 (X Y))
(* NO (X Y) MEANS: X COULD
SAY AT DAY Y: NO, THE RATTLE IS NOT MINE.)
(TYPE NO (PERSON DAYS))
(ALL X:PERSON
ALL Y:DAYS NO (X Y) IMPL NOT RATTLE-OWNER2 (X Y))
(ALL X:PERSON ALL Y:DAYS NO (X Y) EQV NOT YES (X Y))
(*)
(TYPE TODAY:DAYS)
(YES (FIRSTONE TODAY) AND (YES (SECONDONE TODAY) OR NO (SECONDONE TODAY)))

((TWEEDLEDEE (FIRSTONE) AND TWEEDLEDUM (SECONDONE) OR TWEEDLEDUM (FIRSTONE)
AND TWEEDLEDEE (SECONDONE)) IMPL (NO (SECONDONE TODAY) IMPL RATTLE-OWNER (FIRSTONE)))