;;; -*- Mode: Lisp; Syntax: Common-lisp; Package: MKRP -*-

(* Definitionen der Mengenlehre)
(sort set:any)
(sort element:any)
(type el (element set))
(* Definition 1.3 Kartesisches Produkt)
(type cartes (set set) :set)
(type pair (element element) :element)
(* )
(* Definitionen von Relationen auf einer festen Menge S)
(sort rel:set)
(type s:set)
(sort el.of.s:element)
(* Definition 1.4: Vereinigung und Sortenproblem)
(type union (rel rel):rel)
(all x,y:rel all a,b:el.of.s el(pair (a b) union (x y)) eqv el (pair (a b) x) or el (pair (a b ) y))
(* Definition 2.4: Konverse Relation)
(type converse (rel) :rel)
(all rho:rel all a,b:el.of.s el(pair(a b) converse(rho)) eqv el(pair (b a) rho))
(* Definition 2.6: Symmetrisch)
(type symmetrisch (rel))
(* Lemma 2.5)
(all rho:rel (all a,b:el.of.s el(pair(a b) rho) impl el (pair (b a) rho )) impl symmetrisch (rho))

(all rho:rel symmetrisch(union (rho converse (rho))))