;;; -*- Package: MKRP; Base: 10.; Mode: LISP; Syntax: Common-lisp -*- 
(SORT ELEMENT,MENGE,VERKN,NAT,ABB:ANY)
(TYPE APPLYA(ABB ELEMENT) :ELEMENT)
(TYPE APPLYV(VERKN ELEMENT ELEMENT) :ELEMENT)
(TYPE LENGTH(ELEMENT) :NAT)
(TYPE W(MENGE) :MENGE)
(TYPE CONC:VERKN)
(TYPE 1:NAT)
(ALL X:MENGE  ALL U,V,W:ELEMENT  
     EL(U X) AND EL(V W(X)) AND EL(W W(X)) AND APPLYV(CONC U V) = APPLYV(CONC U W) IMPL V = W)
(ALL X:MENGE ALL U:ELEMENT EL(U W(X)) AND LENGTH(U) = 1 IMPL EL(U X))

(ALL X:MENGE  ALL U,V,W:ELEMENT  
     EL(U W(X)) AND EL(V W(X)) AND EL(W W(X)) AND LENGTH(U) = 1 AND APPLYV(CONC U V) = APPLYV(CONC U W)
     IMPL V = W)