;;; -*- Mode: LISP; Package: MKRP; Syntax: Common-lisp -*-
(* PROBLEM 64)
(*)
(* ON ANOTHER
OCCASSION THEY MADE THE FOLLOWING STATEMENTS.)
(*)
(* FIRST ONE / I AM TWEEDLEDOO.)
(* SECOND ONE / YES, HE IS TWEEDLEDOO.)
(*)
(* DOES TWEEDLEDOO
EXISTS?)
(*)
(*)
(* FORMALIZING THE PROBLEM IN FIRST ORDER
LOGIC)
(*)
(TYPE FIRSTONE,SECONDONE:PERSON)
(TYPE 
TWEEDLEDEE,TWEEDLEDUM,TWEEDLEDOO:BROTHERS)
(*)
(ALL X:DAYS MO (X) EQV (NOT TU
(X) AND NOT WE (X) AND NOT TH (X) AND NOT FR (X) AND NOT SA (X) AND NOT SU (X)))
(ALL X:DAYS TU (X) EQV (NOT MO (X)
AND NOT WE (X) AND NOT TH (X) AND NOT FR (X) AND NOT SA (X) AND NOT SU (X)))
(ALL X:DAYS WE (X) EQV (NOT MO (X)
AND NOT TU (X) AND NOT TH (X) AND NOT FR (X) AND NOT SA (X) AND NOT SU (X)))
(ALL X:DAYS TH (X) EQV (NOT MO (X)
AND NOT TU (X) AND NOT WE (X) AND NOT FR (X) AND NOT SA (X) AND NOT SU (X)))
(ALL X:DAYS FR (X) EQV (NOT MO (X)
AND NOT TU (X) AND NOT WE (X) AND NOT TH (X) AND NOT SA (X) AND NOT SU (X)))
(ALL X:DAYS SA (X) EQV (NOT MO (X)
AND NOT TU (X) AND NOT WE (X) AND NOT TH (X) AND NOT FR (X) AND NOT SU (X)))
(ALL X:DAYS SU (X) EQV (NOT MO (X)
AND NOT TU (X) AND NOT WE (X) AND NOT TH (X) AND NOT FR (X) AND NOT SA (X)))
(*)
(*)
(ALL X:PERSON ALL Y:BROTHERS IS (X Y) IMPL (ALL Z:DAYS (MEMBER (Z LYING-DAYS (Y)) EQV MEMBER (Z LYING-DAYS
(X)))))
(*)
(TYPE MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRYDAY,SATURDAY,SUNDAY:
DAYS)
(MO (MONDAY))
(TU (TUESDAY))
(WE (WEDNESDAY))
(TH (THURSDAY))
(FR (FRYDAY))
(SA (SATURDAY))
(SU (SUNDAY))
(* IS (X Y) MEANS: X IS Y.)
(IS (X TWEEDLEDUM) EQV (NOT IS (X TWEEDLEDEE)
AND NOT IS (X TWEEDLEDOO)))
(IS (X TWEEDLEDEE) EQV (NOT IS (X TWEEDLEDUM) AND NOT IS (X TWEEDLEDOO)))
(IS (X TWEEDLEDOO) EQV (NOT
IS (X TWEEDLEDEE) AND NOT IS (X TWEEDLEDUM)))
(NOT (IS (FIRSTONE TWEEDLEDUM) AND IS (SECONDONE TWEEDLEDUM)))
(NOT (IS (FIRSTONE TWEEDLEDEE) AND IS (SECONDONE
TWEEDLEDEE)))
(NOT (IS (FIRSTONE TWEEDLEDOO)
AND IS (SECONDONE TWEEDLEDOO)))
(ALL X:PERSON
IS (X TWEEDLEDUM) OR IS (X TWEEDLEDEE) OR IS (X TWEEDLEDOO))
(*)
(ALL X:DAYS MEMBER (X LYING-DAYS (TWEEDLEDUM))
EQV (MO (X) OR TU (X) OR WE (X)))
(ALL X:DAYS MEMBER (X LYING-DAYS (TWEEDLEDEE)) EQV (TH (X) OR FR (X)
OR SA (X)))
(ALL X:DAYS MEMBER (X LYING-DAYS (TWEEDLEDOO)))
(*)
(* IS-TWEEDLEDOO3 (X Y Z) MEANS: X COULD STATE AT DAY Y: Z IS TWEEDLEDOO.)
(ALL X,Z:PERSON ALL Y:DAYS NOT MEMBER (Y LYING-DAYS (X)) AND NOT IS (Z TWEEDLEDOO) IMPL NOT 
IS-TWEEDLDOO3 (X Y Z))
(ALL X,Z:PERSON ALL Y:DAYS NOT MEMBER (Y LYING-DAYS
(X)) AND IS (Z TWEEDLEDOO) IMPL IS-TWEEDLDOO3 (X Y Z))
(ALL X,Z:PERSON ALL Y:DAYS MEMBER
(Y LYING-DAYS (X)) AND IS (Z TWEEDLEDOO) IMPL NOT IS-TWEEDLDOO3 (X Y Z))
(ALL X,Z:PERSON
ALL Y:DAYS MEMBER (Y LYING-DAYS (X)) AND NOT IS (Z TWEEDLEDOO) IMPL IS-TWEEDLDOO3 (X Y Z))
(TYPE TODAY:DAYS)
(TWEEDLEDOO3 (FIRSTONE TODAY FIRSTONE) AND TWEEDLEDOO3 (SECONDONE TODAY FIRSTONE))

(IS (SECONDONE TWEEDLEDOO))