;;; -*- Mode: Lisp; Package: MKRP; Base: 10.; Syntax: Common-lisp -*-
(SORT WOLF,FOX,BIRD,CATERPILLAR,SNAIL:ANIMAL)
(SORT GRAIN:PLANT)
(ALL X:ANIMAL  
 (ALL Y:PLANT EATS (X Y)) OR (ALL Y:ANIMAL SMALLER (Y X) AND (EX Z:PLANT EATS (Y Z)) IMPL EATS (X Y)))
(ALL X:CATERPILLAR ALL Y:BIRD SMALLER (X Y))
(ALL X:SNAIL ALL Y:BIRD SMALLER (X Y))
(ALL X:BIRD ALL Y:FOX SMALLER (X Y))
(ALL X:FOX ALL Y:WOLF SMALLER (X Y))
(ALL X:FOX ALL Y:WOLF NOT EATS (Y X))
(ALL X:GRAIN ALL Y:WOLF NOT EATS (Y X))
(ALL X:BIRD ALL Y:CATERPILLAR EATS (X Y))
(ALL X:BIRD ALL Y:SNAIL NOT EATS (X Y))
(ALL X:CATERPILLAR EX Y:PLANT EATS (X Y))
(ALL X:SNAIL EX Y:PLANT EATS (X Y))

(* THEOREMS ) 
(EX X,Y:ANIMAL EX Z:GRAIN EATS (X Y) AND EATS (Y Z))