;;; -*- Mode: Lisp; Package: MKRP; Base: 10.; Syntax: Common-lisp -*-
(SORT WOLF,FOX,BIRD,CATERPILLAR,SNAIL:ANIMAL)
(SORT GRAIN:PLANT)
(ALL AN1:ANIMAL  
 (ALL PL1:PLANT EATS (AN1 PL1)) OR (ALL AN2:ANIMAL SMALLER (AN2 AN1) AND (EX PL2:PLANT EATS (AN2 PL2)) IMPL EATS (AN1 AN2)))
(ALL CA:CATERPILLAR ALL BI:BIRD SMALLER (CA BI))
(ALL SN:SNAIL ALL BI:BIRD SMALLER (SN BI))
(ALL BI:BIRD ALL FO:FOX SMALLER (BI FO))
(ALL FO:FOX ALL WO:WOLF SMALLER (FO WO))
(ALL FO:FOX ALL WO:WOLF NOT EATS (WO FO))
(ALL GR:GRAIN ALL WO:WOLF NOT EATS (WO GR))
(ALL BI:BIRD ALL CA:CATERPILLAR EATS (BI CA))
(ALL BI:BIRD ALL SN:SNAIL NOT EATS (BI SN))
(ALL CA:CATERPILLAR EX PL:PLANT EATS (CA PL))
(ALL SN:SNAIL EX PL:PLANT EATS (SN PL))

(* THEOREMS ) 
(EX AN1,AN2:ANIMAL EX GR:GRAIN EATS (AN1 AN2) AND EATS (AN2 GR))