;;; -*- Package: MKRP; Mode: LISP; Syntax: Common-lisp -*-
(NOT A = B AND NOT A = C AND NOT B = C)
(SCHULDIG (A) OR SCHULDIG (B) OR SCHULDIG (C))
(SCHULDIG (A) IMPL (SCHULDIG (B) OR SCHULDIG (C)) AND
	  NOT (SCHULDIG (B) AND SCHULDIG (C)))
(NOT SCHULDIG (B) IMPL NOT SCHULDIG (C)
     (EX X,Y,Z NOT X = Y AND NOT X = Z AND NOT Y = Z AND
	 SCHULDIG (X) AND SCHULDIG (Y) AND NOT SCHULDIG (Z))
     IMPL SCHULDIG (A))
(NOT SCHULDIG (C) IMPL NOT SCHULDIG (B))