;;; -*- Mode: LISP; Package: MKRP; Syntax: Common-lisp -*-
(* PROBLEM 66)
(*)
(* ON ANOTHER
OCCASSION THEY MADE THE FOLLOWING STATEMENTS.)
(*)
(* FIRST ONE / TWEEDLEDOO
EXISTS.)
(* SECOND ONE / I EXIST.)
(*)
(* DOES TWEEDLEDOO
EXISTS?)
(*)
(*)
(* FORMALIZING THE PROBLEM IN FIRST ORDER
LOGIC)
(*)
(TYPE FIRSTONE, SECONDONE:PERSON)
(TYPE 
TWEEDLEDEE,TWEEDLEDUM,TWEEDLEDOO:BROTHERS)
(*)
(ALL X:DAYS MO (X) EQV (NOT TU
(X) AND NOT WE (X) AND NOT TH (X) AND NOT FR (X) AND NOT SA (X) AND NOT SU (X)))
(ALL X:DAYS TU (X) EQV (NOT MO (X)
AND NOT WE (X) AND NOT TH (X) AND NOT FR (X) AND NOT SA (X) AND NOT SU (X)))
(ALL X:DAYS WE (X) EQV (NOT MO (X)
AND NOT TU (X) AND NOT TH (X) AND NOT FR (X) AND NOT SA (X) AND NOT SU (X)))
(ALL X:DAYS TH (X) EQV (NOT MO (X)
AND NOT TU (X) AND NOT WE (X) AND NOT FR (X) AND NOT SA (X) AND NOT SU (X)))
(ALL X:DAYS FR (X) EQV (NOT MO (X)
AND NOT TU (X) AND NOT WE (X) AND NOT TH (X) AND NOT SA (X) AND NOT SU (X)))
(ALL X:DAYS SA (X) EQV (NOT MO (X)
AND NOT TU (X) AND NOT WE (X) AND NOT TH (X) AND NOT FR (X) AND NOT SU (X)))
(ALL X:DAYS SU (X) EQV (NOT MO (X)
AND NOT TU (X) AND NOT WE (X) AND NOT TH (X) AND NOT FR (X) AND NOT SA (X)))
(*)
(*)
(ALL X:PERSON ALL Y:BROTHERS IS (X Y) IMPL (ALL Z:DAYS (MEMBER (Z LYING-DAYS (Y)) EQV MEMBER (Z LYING-DAYS
(X)))))
(*)
(TYPE MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRYDAY,SATURDAY,SUNDAY:
DAYS)
(MO (MONDAY))
(TU (TUESDAY))
(WE (WEDNESDAY))
(TH (THURSDAY))
(FR (FRYDAY))
(SA (SATURDAY))
(SU (SUNDAY))
(* IS (X Y) MEANS: X IS Y.)
(ALL X:PERSON IS (X TWEEDLEDUM) EQV (NOT IS
(X TWEEDLEDEE) AND NOT IS (X TWEEDLEDOO)))
(ALL X:PERSON IS (X TWEEDLEDEE) EQV (NOT IS (X TWEEDLEDUM) AND
NOT IS (X TWEEDLEDOO)))
(ALL X:PERSON IS (X TWEEDLEDOO) EQV (NOT IS (X TWEEDLEDEE) AND NOT IS (X TWEEDLEDUM)))
(NOT (IS (FIRSTONE TWEEDLEDUM) AND IS (SECONDONE TWEEDLEDUM)))
(NOT (IS (FIRSTONE TWEEDLEDEE) AND IS (SECONDONE TWEEDLEDEE)))
(NOT (IS (FIRSTONE TWEEDLEDOO) AND IS (SECONDONE TWEEDLEDOO)))
(ALL X:PERSON IS (X TWEEDLEDUM) OR IS (X TWEEDLEDEE)
OR IS (X TWEEDLEDOO))
(*)
(ALL X:DAYS MEMBER (X LYING-DAYS (TWEEDLEDUM)) EQV (MO (X) OR TU (X) OR
WE (X)))
(ALL X:DAYS MEMBER (X LYING-DAYS (TWEEDLEDEE)) EQV (TH (X) OR FR (X) OR SA (X)))
(ALL
X:DAYS MEMBER (X LYING-DAYS (TWEEDLEDOO)))
(*)
(* EXIST3 (X Y Z) MEANS: X COULD STATE AT DAY Y: Z EXISTS.)
(*)
(ALL Z ALL
X:PERSON ALL Y:DAYS NOT MEMBER (Y LYING-DAYS (X)) AND NOT EXIST (Z) IMPL NOT EXIST3 (X Y Z))
(ALL Z ALL X:PERSON ALL Y:DAYS NOT MEMBER (Y LYING-DAYS (X)) AND EXIST (Z) IMPL EXIST3 (X Y Z))
(ALL Z ALL X:PERSON ALL Y:DAYS MEMBER (Y LYING-DAYS (X)) AND NOT EXIST (Z) IMPL EXIST3
(X Y Z))
(ALL Z ALL X:PERSON ALL Y:DAYS MEMBER (Y LYING-DAYS (X)) AND EXIST (Z) IMPL
NOT EXIST3 (X Y Z))
(*)
(ALL X:BROTHERS EXIST (X) EQV (IS (FIRSTONE
X) OR IS (SECONDONE X) OR (EX Y:PERSON EX Z:DAYS EXIST3 (Y Z X) AND NOT MEMBER (Z LYING-DAYS (Y)))))
(*)
(TYPE TODAY:DAYS)
(EXIST3 (FIRSTONE TODAY TWEEDLEDOO) AND EXIST3 (SECONDONE TODAY SECONDONE))
(EXIST (FIRSTONE) AND EXIST (SECONDONE))

(NOT EXIST (TWEEDLEDOO))