;;; -*- Mode: LISP; Package: MKRP; Syntax: Common-lisp -*-
(* AXIOMS OF PROBLEM 32 %.)
(* WE HAVE THREE PEOPLE:
A, B, C.)
(* A SAYS: ALL OF US ARE KNAVES.)
(* B SAYS: EXACTLY ONE OF US IS
A KNAVE.)
(* WHAT ARE A, B, C?)
(*)
(* EVERY (X) MEANS: X
SAYS: WE ARE ALL KNAVES.)
(* EXACT (X) MEANS: X SAYS: EXACTLY ONE OF US IS A KNAVE.)
(*)
(ALL X KNIGHT (X) EQV NOT KNAVE (X))
(ALL X NOT (KNIGHT (X) AND EVERY (X)))
(ALL X (KNAVE (X) AND EVERY (X)) IMPL NOT (KNAVE (A) AND KNAVE
						 (B) AND KNAVE (C)))
(ALL X (KNAVE (X) AND EXACT (X)) IMPL NOT ((KNAVE (A) OR KNAVE (B) OR
						  KNAVE (C)) AND NOT (KNAVE (A) AND KNAVE (B))
						  AND NOT (KNAVE (A) AND KNAVE (C)) AND NOT (KNAVE (B) AND KNAVE (C))))
(ALL X KNIGHT (X) AND EXACT (X) IMPL (KNAVE (A) OR KNAVE
					    (B) OR KNAVE (C)) AND NOT (KNAVE (A) AND KNAVE (B)) AND
					    NOT (KNAVE (A) AND KNAVE (C)) AND NOT (KNAVE (B) AND KNAVE
											 (C)))
(EVERY (A))
(EXACT (B))



(KNAVE (A) AND KNAVE (B) AND KNIGHT (B) AND KNIGHT (C))