;;; -*- Mode: LISP; Package: MKRP; Syntax: Common-lisp -*-
(* AXIOME FUER BEISPIEL D 65A)
(PORTRAIT (GOLD) OR PORTRAIT (LEAD) OR PORTRAIT (SILVER))
(NOT (PORTRAIT (GOLD) AND PORTRAIT (LEAD) OR PORTRAIT (GOLD) AND
PORTRAIT (SILVER) OR PORTRAIT (SILVER) AND PORTRAIT (LEAD)))
(NOT PORTRAIT (GOLD) AND PORTRAIT (SILVER) AND
PORTRAIT (GOLD) OR PORTRAIT (GOLD) AND PORTRAIT (SILVER) AND PORTRAIT (GOLD) OR NOT PORTRAIT (GOLD) AND NOT PORTRAIT (SILVER) AND PORTRAIT (GOLD) OR NOT PORTRAIT (GOLD) AND PORTRAIT (SILVER) AND NOT PORTRAIT (GOLD))

(* THEOREM FUER BEISPIEL D 65A)
(*)
(* OFFENSICHTLICH IST DAS PORTRAET IM SILBERNEN KAESTCHEN)
(*)
(PORTRAIT (GOLD) AND PORTRAIT (SILVER) AND PORTRAIT (LEAD))