;;; -*- Mode: LISP; Syntax: Common-lisp; Package: MKRP -*- 
(SORT MENGE,VERKN,ELEMENT,INDEX,INDEXMENGE:ANY)
(TYPE LIDEAL (MENGE MENGE VERKN))
(TYPE RIDEAL (MENGE MENGE VERKN))
(TYPE UHG (MENGE MENGE VERKN))
(TYPE ME (MENGE MENGE))
(TYPE NICHTLEER (MENGE))
(TYPE HG (MENGE VERKN))
(TYPE EL (ELEMENT MENGE))
(TYPE MINIMAL (MENGE MENGE VERKN))
(TYPE MPROD (MENGE MENGE VERKN) :MENGE)
(TYPE APPLYV (VERKN ELEMENT ELEMENT) :ELEMENT)
(TYPE F*X (MENGE ELEMENT VERKN) :MENGE)
(TYPE SM (MENGE MENGE) :MENGE)
(TYPE SET (ELEMENT) :MENGE)
(TYPE VER (MENGE MENGE) :MENGE)
(TYPE GR (MENGE VERKN ELEMENT))
(TYPE INVERS (VERKN ELEMENT) :ELEMENT)
(TYPE MINIMAL-BED-L (MENGE VERKN))
(TYPE MINIMAL-BED-R (MENGE VERKN))
(TYPE EL-IND (INDEX INDEXMENGE))
(TYPE U (INDEX) : MENGE)
(TYPE E (INDEX INDEX) : ELEMENT)
(TYPE NICHTLEER-IND (INDEXMENGE))
(TYPE GLEICH (MENGE MENGE))
(TYPE VER-IND (INDEXMENGE) : MENGE)
(TYPE SM-IND (INDEXMENGE) : MENGE)
(TYPE IDEAL (MENGE MENGE VERKN))
(TYPE EXINV (MENGE VERKN ELEMENT))
(* DEFINITION INV *)
(ALL F:MENGE  ALL MAL:VERKN  ALL E:ELEMENT  
     EINS (E MAL F)
     IMPL  
     (ALL X:ELEMENT EL (X F) IMPL (EX Y:ELEMENT EL (Y F) IMPL GLEICH-E (APPLYV (MAL Y X) E)))
     IMPL  
     EXINV (F MAL E))
(* LEMMA 3.11.A *
   * VORAUSSETZUNG311A (F MAL I1 I2) BEDEUTET : HG (F MAL)
   AND  
   MINIMAL-BED-L (F MAL)
   AND  
   MINIMAL-BED-R (F MAL)
   AND  
   (ALL K1:INDEX EL-IND (K1 I1) IMPL RIDEAL (U (K1) F MAL) AND MINIMAL (U (K1) F MAL))
   AND  
   (ALL K2:INDEX EL-IND (K2 I2) IMPL LIDEAL (U (K2) F MAL) AND MINIMAL (U (K2) F MAL)) *)
(ALL F:MENGE  ALL MAL:VERKN  ALL I1,I2:INDEXMENGE  ALL J1,J2,J3,J4:INDEX  
     VORAUSSETZUNG311A (F MAL I1 I2)
     AND  
     EL-IND (J1 I1)
     AND  
     EL-IND (J2 I2)
     AND  
     EL-IND (J3 I1)
     AND  
     EL-IND (J4 I2)
     IMPL  
     (ALL X:ELEMENT EL (X SM (U (J3) U (J4))) IMPL GLEICH (F*X (SM (U (J1) U (J2)) X MAL) SM (U (J1) U (J4)))))
(* F*X FUER ELEMENTE *)
(ALL A,B:MENGE  ALL MAL:VERKN  ALL Y:ELEMENT  
     (ALL X:ELEMENT EL (X A) IMPL GLEICH (F*X (A X MAL) B)) AND EL (Y B)
     IMPL  
     (ALL X:ELEMENT EL (X A) IMPL (EX I:ELEMENT EL (I A) AND GLEICH-E (APPLYV (MAL I X) Y))))

(ALL F:MENGE  ALL MAL:VERKN  ALL I1,I2:INDEXMENGE  ALL J1,J2:INDEX  ALL E:ELEMENT  
     HG (F MAL)
     AND  
     MINIMAL-BED-L (F MAL)
     AND  
     MINIMAL-BED-R (F MAL)
     AND  
     (ALL J1:INDEX EL-IND (J1 I1) IMPL RIDEAL (U (J1) F MAL) AND MINIMAL (U (J1) F MAL))
     AND  
     (ALL J2:INDEX EL-IND (J2 I2) IMPL LIDEAL (U (J2) F MAL) AND MINIMAL (U (J2) F MAL))
     AND  
     EL-IND (J1 I1)
     AND  
     EL-IND (J2 I2)
     AND  
     ME (SM (U (J1) U (J2)) F)
     AND  
     GLEICH (MPROD (U (J1) U (J2) MAL) SM (U (J1) U (J2)))
     AND  
     EINS (E MAL SM (U (J1) U (J2)))
     AND  
     VORAUSSETZUNG311A (F MAL I1 I2)
     IMPL  
     EXINV (SM (U (J1) U (J2)) MAL E))