;;; -*- Mode: LISP; Package: MKRP; Syntax: Common-lisp -*- 

(SORT ELEMENT,MENGE,VERKN:ANY)
(TYPE SM (MENGE MENGE) :MENGE)
(TYPE APPLY (VERKN ELEMENT ELEMENT) :ELEMENT)
(TYPE INVERS (ELEMENT VERKN) :ELEMENT)
(ALL X:ELEMENT  ALL M1,M2:MENGE  
     EL (X SM (M1 M2)) EQV EL (X M1) AND EL (X M2))
(ALL PHI:VERKN  ALL X,E:ELEMENT  ALL U,F:MENGE  
     UG (U F PHI E) AND EL (X U)
     IMPL  
     GLEICH (APPLY (PHI X INVERS (X PHI)) E) AND EL (INVERS (X
							      PHI) U))

(ALL PHI:VERKN  ALL X,E:ELEMENT  ALL U1,U2,F:MENGE  
     UG (U1 F PHI E) AND UG (U2 F PHI E) AND EL (X SM (U1 U2))
     IMPL  
     GLEICH (APPLY (PHI X INVERS (X PHI)) E)
     AND  
     EL (INVERS (X PHI) SM (U1 U2)))