;;; -*- Package: MKRP; Mode: LISP; Syntax: Common-lisp -*- 

(SORT ELEMENT,MENGE,VERKN,INDEX:ANY)
(TYPE EHG (MENGE VERKN INDEX) :MENGE)
(TYPE PLUS (INDEX INDEX) :INDEX)
(TYPE APPLY (VERKN ELEMENT ELEMENT) :ELEMENT)
(TYPE 1,M:INDEX)
(ALL X,Y:ELEMENT  ALL E:MENGE  ALL N,NSTRICH:INDEX  ALL PHI:VERKN  
     KLEINERGLEICH (NSTRICH N)
     AND  
     EL (X EHG (E PHI M))
     AND  
     EL (Y EHG (E PHI NSTRICH))
     IMPL  
     EL (APPLY (PHI X Y) EHG (E PHI PLUS (M NSTRICH))))
(ALL K:INDEX  ALL X,Y:ELEMENT  ALL PHI:VERKN  ALL E:MENGE  
     EL (X EHG (E PHI K)) AND EL (Y EHG (E PHI 1))
     IMPL  
     EL (APPLY (PHI X Y) EHG (E PHI PLUS (K 1))))
(ALL K:INDEX  ALL X:ELEMENT  ALL PHI:VERKN  ALL E:MENGE  
     EL (X EHG (E PHI PLUS (K 1)))
     IMPL  
     EX Y,Z:ELEMENT  
     X = APPLY (PHI Y Z)
     AND  
     EL (Y EHG (E PHI K))
     AND  
     EL (Z EHG (E PHI 1)))
(ALL PHI  
     :VERKN ALL  
     X,Y,Z:ELEMENT  
     APPLY  
     PHI X APPLY (PHI Y Z)
     =  
     APPLY  
     PHI APPLY (PHI X Y) Z)

(ALL E,F:MENGE  ALL X,Y:ELEMENT  ALL PHI:VERKN  ALL N,NSTRICH:INDEX  
     HG (F PHI)
     AND  
     ME (E F)
     AND  
     EL (X EHG (E PHI M))
     AND  
     EL (Y EHG (E PHI PLUS (NSTRICH 1)))
     AND  
     KLEINERGLEICH (NSTRICH N)
     IMPL  
     EL (APPLY (PHI X Y) EHG (E PHI PLUS (PLUS (M NSTRICH) 1))))