;;; -*- Package: MKRP; Base: 10; Mode: LISP; Syntax: Common-lisp -*-
(PREP-PROBLEM.SPECIFICATION (QUOTE ((SORT ELEM,MENGE,VERKN : ANY) (TYPE APPLY (VERKN ELEM ELEM) : ELEM) (TYPE INVERS (VERKN ELEM) : ELEM) (ALL PHI : VERKN ALL U,F : MENGE ALL E : ELEM G (F PHI E) AND ME (U F) AND EL (E U) IMPL EINS (E PHI U)) (ALL U,V : MENGE ALL X : ELEM ME (U V) AND EL (X U) IMPL EL (X V)) (ALL PHI : VERKN ALL F : MENGE ALL X,E : ELEM G (F PHI E) AND EL (X F) IMPL APPLY (PHI INVERS (PHI X) X) = E))) (QUOTE ((+ 0 NIL) (+ 0 NIL) (+ 0 NIL) (ALL 4 (ALL 6 (ALL 5 (ALL 7 (IMPL (AND (+ 8 (6 4 7) NIL) (AND (+ 9 (5 6) NIL) (+ 10 (7 5) NIL))) (+ 11 (7 4 5) NIL)))))) (ALL 13 (ALL 12 (ALL 14 (IMPL (AND (+ 9 (12 13) NIL) (+ 10 (14 12) NIL)) (+ 10 (14 13) NIL))))) (ALL 15 (ALL 16 (ALL 18 (ALL 17 (IMPL (AND (+ 8 (16 15 18) NIL) (+ 10 (17 16) NIL)) (+ 19 ((2 15 (3 15 17) 17) 18) NIL)))))))) (QUOTE ((* THEOREM *) (ALL PHI : VERKN ALL U,F : MENGE ALL Z,E : ELEM G (F PHI E) AND ME (U F) IMPL (ALL X,Y : ELEM EL (X U) AND EL (Y U) IMPL EL (APPLY (PHI INVERS (PHI Y) X) U) AND EL (Z U) IMPL EINS (E PHI U))))) (QUOTE (COMMENT (ALL 24 (ALL 22 (ALL 23 (ALL 20 (ALL 21 (IMPL (AND (+ 8 (22 24 20) NIL) (+ 9 (23 22) NIL)) (ALL 26 (ALL 25 (IMPL (AND (+ 10 (25 23) NIL) (+ 10 (26 23) NIL)) (IMPL (AND (+ 10 ((2 24 (3 24 26) 25) 23) NIL) (+ 10 (21 23) NIL)) (+ 11 (20 24 23) NIL))))))))))))) (QUOTE ("Edit:     Axioms and Theorems edited: 13-DEC,1989 19:06 ")) (PROGN(PROGN (DT-RESET))

(PROG ((ADDRLIST
        '(299781 299786 299811 299806 299801 299796 299791 299826 299831 299836 299841 299846
          299851 299856 299861 299876 299891 299906 299921 299926 299931 299936 299941 299955
          299969 299984 299999))
       (DATALIST
        '(15 "TRUE" NIL NIL NIL (DEFINED) NIL ((- 0 (POSITIVE))) ((+ 0 (NEGATIVE)))
          ((+ 0 (NIL))) ((- 0 (NIL))) NIL NIL (DT*ST-KIND NIL) PREDICATE 15 "FALSE" NIL NIL
          NIL (DEFINED) NIL ((- 1 (POSITIVE))) ((+ 1 (NEGATIVE))) ((+ 1 (NIL))) ((- 1 (NIL)))
          NIL NIL (DT*ST-KIND NIL) PREDICATE 14 "APPLY" NIL ELEM (VERKN ELEM ELEM) NIL NIL NIL
          NIL NIL 3 ELEM (DT*ST-KIND NIL) FUNCTION 14 "INVERS" NIL ELEM (VERKN ELEM) NIL NIL
          NIL NIL NIL 2 ELEM (DT*ST-KIND NIL) FUNCTION 5 VERKN NIL
          (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 MENGE NIL
          (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 MENGE NIL
          (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 ELEM NIL (ST*DATA NIL DT*ST-KIND SYS-VAR)
          VARIABLE 15 "G" NIL NIL (ANY ANY ANY) NIL NIL ((- 8 (POSITIVE))) ((+ 8 (NEGATIVE)))
          ((+ 8 (NIL))) ((- 8 (NIL))) NIL NIL (DT*ST-KIND NIL) PREDICATE 15 "ME" NIL NIL
          (ANY ANY) NIL NIL ((- 9 (POSITIVE))) ((+ 9 (NEGATIVE))) ((+ 9 (NIL))) ((- 9 (NIL)))
          NIL NIL (DT*ST-KIND NIL) PREDICATE 15 "EL" NIL NIL (ANY ANY) NIL NIL
          ((- 10 (POSITIVE))) ((+ 10 (NEGATIVE))) ((+ 10 (NIL))) ((- 10 (NIL))) NIL NIL
          (DT*ST-KIND NIL) PREDICATE 15 "EINS" NIL NIL (ANY ANY ANY) NIL NIL
          ((- 11 (POSITIVE))) ((+ 11 (NEGATIVE))) ((+ 11 (NIL))) ((- 11 (NIL))) NIL NIL
          (DT*ST-KIND NIL) PREDICATE 5 MENGE NIL (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5
          MENGE NIL (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 ELEM NIL
          (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 VERKN NIL
          (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 MENGE NIL
          (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 ELEM NIL (ST*DATA NIL DT*ST-KIND SYS-VAR)
          VARIABLE 5 ELEM NIL (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 15 "=" NIL NIL
          (ANY ANY) (DEFINED SYMMETRIC REFLEXIVE SYMMETRIC REFLEXIVE) NIL
          ((- 19 (POSITIVE . SYMMETRIC))) ((+ 19 (NEGATIVE . SYMMETRIC)))
          ((+ 19 (NIL . SYMMETRIC))) ((- 19 (NIL . SYMMETRIC))) NIL NIL (DT*ST-KIND NIL)
          PREDICATE 5 VERKN NIL (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 MENGE NIL
          (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 MENGE NIL
          (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 ELEM NIL (ST*DATA NIL DT*ST-KIND SYS-VAR)
          VARIABLE 5 ELEM NIL (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 ELEM NIL
          (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 ELEM NIL (ST*DATA NIL DT*ST-KIND SYS-VAR)
          VARIABLE))
       (INCREMENT (- MEM*SIZE 300000))
       COUNTER1)
      (MEM-RESET)
      (COND ((> MEM*SIZE 300000)
             (SETQ COUNTER1 27)
             (MAPC #'(LAMBDA (RADDR)
                       (SETF (AREF MEM*MEMORY (DECF COUNTER1))
                              (COND ((EQL RADDR 'ATP.MEMORY.NIL) RADDR)
                                    ((EQL 'END RADDR) RADDR)
                                    ((OR (EQL RADDR 0)
                                         (MINUSP RADDR))
                                     RADDR)
                                    (T (+ RADDR INCREMENT)))))
                   ADDRLIST)
             (SETQ COUNTER1 MEM*SIZE)
             (MAPC #'(LAMBDA (DATA) (SETF (AREF MEM*MEMORY (DECF COUNTER1)) DATA)) DATALIST))
            (T (UNLESS (= MEM*SIZE 300000)
                 (MEM-INITIALIZE 300000))
               (SETQ COUNTER1 27)
               (MAPC #'(LAMBDA (RADDR) (SETF (AREF MEM*MEMORY (DECF COUNTER1)) RADDR))
                     ADDRLIST)
               (SETQ COUNTER1 MEM*SIZE)
               (MAPC #'(LAMBDA (DATA) (SETF (AREF MEM*MEMORY (DECF COUNTER1)) DATA)) DATALIST))
            )
      (SETQ MEM*NEXT.RADR (IF (> MEM*SIZE 300000) (+ 299776 INCREMENT) 299776))
      (SETQ MEM*NEXT.VADR 27
            MEM*REST (- MEM*NEXT.RADR MEM*NEXT.VADR -1)
            MEM*FIRST.REUSABLE.VADR NIL
            MEM*LAST.REUSABLE.VADR NIL))

(PROGN (SETQ DT*SORT.ALL (QUOTE (VERKN MENGE ELEM ANY))) (SETQ DT*SORT.NR (QUOTE 5)) (SETQ DT*SORT.PROPERTIES (QUOTE (DT*MAX.SUBSORTS DT*LEAST.SUPERSORTS DT*TRANSITIVE.CLOSURE DT*INVERSE.TRANSITIVE.CLOSURE DT*MINIMAL.SUBSORTS DT*DIRECT.SUBSORTS DT*DIRECT.SUPERSORTS DT*DISJOINT.SORTS DT*COMPLETION.SORT))) (SETQ DT*SORT.COMMON.COMPUTE.FLAG (QUOTE NIL)) (SETQ DT*VARIABLE.COUNTER (QUOTE 0)) (SETQ DT*CONSTANT.COUNTER (QUOTE 0)) (SETQ DT*CONSTANT.ALL (QUOTE NIL)) (SETQ DT*ABBREVIATIONS (QUOTE NIL)) (SETQ DT*FUNCTION.COUNTER (QUOTE 0)) (SETQ DT*FUNCTION.ALL (QUOTE (3 2))) (SETQ DT*FUNCTION.ADMISSIBLE.THEORIES (QUOTE (ASSOCIATIVE))) (SETQ DT*FUNCTION.ACTUAL.THEORIES (QUOTE NIL)) (SETQ DT*FUNCTION.WITH.ARGUMENT.SYMMETRIES (QUOTE NIL)) (SETQ DT*FUNCTION.COMPONENTS (QUOTE (PNAME ATTRIBUTES MAX.RANGE.SORT MAX.DOMAIN.SORTS MIN.RANGE.SORTS SORT.LIST SORT.LIST.INVERSE SORT.TREE.CALC ARGUMENT.SYMMETRIES ARITY G.L.B.OF.RANGES))) (SETQ DT*PREDICATE.ADMISSABLE.ATTRIBUTES (QUOTE (SYMMETRIC DEFINED REFLEXIVE))) (SETQ DT*PREDICATE.COUNTER (QUOTE 0)) (SETQ DT*EQUALITY.SYMBOLS (QUOTE ("=" ":=" "=:" ":=:"))) (SETQ DT*EQUALITY.PREDICATES (QUOTE (19))) (SETQ DT*NONEQUALITY.PREDICATES (QUOTE (11 10 9 8 1 0))) (SETQ DT*PREDICATE.ALL (QUOTE (19 11 10 9 8 1 0))) (SETQ DT*PREDICATE.WITH.ATTRIBUTES (QUOTE NIL)) (SETQ DT*PREDICATE.COMPONENTS (QUOTE (PNAME POSITIVE.OCCURRENCES NEGATIVE.OCCURRENCES DOMAINSORTS ATTRIBUTES REFL.CLAUSE +ROTHERSIDES -ROTHERSIDES +SOTHERSIDES -SOTHERSIDES +TOTHERSIDES -TOTHERSIDES))) (SETQ DT*TRUE.PREDICATE (QUOTE 0)) (SETQ DT*FALSE.PREDICATE (QUOTE 1)) (SETQ DT*UNI.CREATES.VARIABLES (QUOTE NIL)) (SETQ DT*SIGN.MINUS.SYMBOLS (QUOTE (- --))) (SETQ DT*SIGN.PLUS.SYMBOLS (QUOTE (+ ++))) (SETQ DT*SYMBOL.KINDS (QUOTE (CONSTANT.ALL FUNCTION.ALL PREDICATE.ALL)))) 
(PROGN) 
(PROGN (PROGN)) 
(PROGN (PROGN (SETF (GET (QUOTE VERKN) (QUOTE DT*SORT.NUMBER)) (QUOTE 4)) (SETF (GET (QUOTE VERKN) (QUOTE DT*DIRECT.SUBSORTS)) (QUOTE NIL)) (SETF (GET (QUOTE VERKN) (QUOTE DT*TRANSITIVE.CLOSURE)) (QUOTE (VERKN))) (SETF (GET (QUOTE VERKN) (QUOTE DT*MAX.SUBSORTS)) (QUOTE ((VERKN VERKN) (MENGE) (ELEM) (ANY VERKN)))) (SETF (GET (QUOTE VERKN) (QUOTE DT*MINIMAL.SUBSORTS)) (QUOTE (VERKN))) (SETF (GET (QUOTE VERKN) (QUOTE DT*DIRECT.SUPERSORTS)) (QUOTE (ANY))) (SETF (GET (QUOTE VERKN) (QUOTE DT*INVERSE.TRANSITIVE.CLOSURE)) (QUOTE (ANY VERKN)))) (PROGN (SETF (GET (QUOTE MENGE) (QUOTE DT*SORT.NUMBER)) (QUOTE 3)) (SETF (GET (QUOTE MENGE) (QUOTE DT*DIRECT.SUBSORTS)) (QUOTE NIL)) (SETF (GET (QUOTE MENGE) (QUOTE DT*TRANSITIVE.CLOSURE)) (QUOTE (MENGE))) (SETF (GET (QUOTE MENGE) (QUOTE DT*MAX.SUBSORTS)) (QUOTE ((VERKN) (MENGE MENGE) (ELEM) (ANY MENGE)))) (SETF (GET (QUOTE MENGE) (QUOTE DT*MINIMAL.SUBSORTS)) (QUOTE (MENGE))) (SETF (GET (QUOTE MENGE) (QUOTE DT*DIRECT.SUPERSORTS)) (QUOTE (ANY))) (SETF (GET (QUOTE MENGE) (QUOTE DT*INVERSE.TRANSITIVE.CLOSURE)) (QUOTE (ANY MENGE)))) (PROGN (SETF (GET (QUOTE ELEM) (QUOTE DT*SORT.NUMBER)) (QUOTE 2)) (SETF (GET (QUOTE ELEM) (QUOTE DT*DIRECT.SUBSORTS)) (QUOTE NIL)) (SETF (GET (QUOTE ELEM) (QUOTE DT*TRANSITIVE.CLOSURE)) (QUOTE (ELEM))) (SETF (GET (QUOTE ELEM) (QUOTE DT*MAX.SUBSORTS)) (QUOTE ((VERKN) (MENGE) (ELEM ELEM) (ANY ELEM)))) (SETF (GET (QUOTE ELEM) (QUOTE DT*MINIMAL.SUBSORTS)) (QUOTE (ELEM))) (SETF (GET (QUOTE ELEM) (QUOTE DT*DIRECT.SUPERSORTS)) (QUOTE (ANY))) (SETF (GET (QUOTE ELEM) (QUOTE DT*INVERSE.TRANSITIVE.CLOSURE)) (QUOTE (ANY ELEM)))) (PROGN (SETF (GET (QUOTE ANY) (QUOTE DT*SORT.NUMBER)) (QUOTE 1)) (SETF (GET (QUOTE ANY) (QUOTE DT*DIRECT.SUBSORTS)) (QUOTE (VERKN MENGE ELEM))) (SETF (GET (QUOTE ANY) (QUOTE DT*TRANSITIVE.CLOSURE)) (QUOTE (ANY VERKN MENGE ELEM))) (SETF (GET (QUOTE ANY) (QUOTE DT*MAX.SUBSORTS)) (QUOTE ((VERKN VERKN) (MENGE MENGE) (ELEM ELEM) (ANY ANY)))) (SETF (GET (QUOTE ANY) (QUOTE DT*MINIMAL.SUBSORTS)) (QUOTE (MENGE ELEM))) (SETF (GET (QUOTE ANY) (QUOTE DT*DIRECT.SUPERSORTS)) (QUOTE NIL)) (SETF (GET (QUOTE ANY) (QUOTE DT*INVERSE.TRANSITIVE.CLOSURE)) (QUOTE (ANY))))) ))