;;; -*- Package: MKRP; Mode: LISP; Syntax: Common-lisp -*- 

(SORT ELEMENT,MENGE,INDEXMENGE,INDEX,VERKN:ANY)
(TYPE SM (MENGE MENGE) :MENGE)
(TYPE APPLY (VERKN ELEMENT ELEMENT) :ELEMENT)
(TYPE S (INDEXMENGE) :MENGE)
(TYPE V (INDEXMENGE INDEX) :INDEXMENGE)
(TYPE U (INDEX) :MENGE)
(ALL I,ISTRICH:INDEXMENGE  ALL F:MENGE  ALL PHI  
     :VERKN ALL E:ELEMENT ME (ISTRICH I) IMPL UG (S (ISTRICH) F
						    PHI E))
(ALL U1,U2,F  
     :MENGE ALL  
     E,X:ELEMENT ALL  
     PHI:VERKN UG (U1 F PHI E)
     AND  
     UG (U2 F PHI E)
     AND  
     EL (X SM (U1 U2))
     IMPL  
     EINS (E PHI SM (U1 U2)))
(ALL K:INDEXMENGE ALL J:INDEX SM (S (K) U (J)) = S (V (K J)))

(ALL I,ISTRICH:INDEXMENGE  ALL J:INDEX  ALL F:MENGE  ALL E  
     :ELEMENT ALL  
     PHI:VERKN ME (ISTRICH I)
     AND  
     UG (U (J) F PHI E)
     AND  
     (EX X:ELEMENT EL (X S (V (ISTRICH J))))
     IMPL  
     EINS (E PHI S (V (ISTRICH J))))