;;; -*- Mode: LISP; Package: MKRP; Syntax: Common-lisp -*-
(* AXIOMS OF PROBLEM 37)
(* THERE ARE TWO PEOPLE
A AND B.)
(* YOU ASK A : IS B A KNIGHT ?)
(* THEN YOU ASK B : IS A A KNIGHT
?)
(* ARE THE ANSWERS THE SAME ?)
(*)
(* YES (X Y) MEANS
: X SAYS : Y IS A KNIGHT.)
(* NO (X Y) MEANS : X SAYS : Y IS NOT A KNIGHT.)

(ALL X,Y YES (X Y) EQV NOT NO (X Y))
(ALL X,Y YES (X Y) AND KNIGHT (X) IMPL KNIGHT (Y))
(ALL X,Y YES (X Y) AND KNAVE (X) IMPL KNAVE (Y))
(ALL X,Y NO (X
Y) AND KNIGHT (X) IMPL KNAVE (Y))
(ALL X,Y NO (X Y) AND KNAVE (X) IMPL KNIGHT (Y))
(ALL X KNIGHT (X) EQV NOT KNAVE (X))


(YES (A B) IMPL YES (B A))
(NO (A B) IMPL NO (B A))


