;;; -*- Mode: LISP; Package: MKRP; Syntax: Common-lisp -*-
(* AXIOMS FOR PROBLEM 43 %.)
(* GIVEN THREE PEOPLE
A,B AND C.)
(* ONE IS A KNIGHT ,ONE A KNAVE ,ONE A NORMAL.)
(* A SAYS : B IS
OF HIGHER RANK THAN C.)
(* B SAYS : C IS OF A HIGHER RANK THAN A.)
(*)
(* THEN C IS ASKED : WHO HAS A HIGHER RANK ,A OR B. WHAT DOES C ANSWER?)
(*)
(*)
(* HRANK2 (X Y) MEANS : X IS OF A HIGHER RANK THAN Y.)
(* HRANK3
(X Y Z) MEANS : X SAYS : Y IS OF A HIGHER RANK THAN Z.)
(*)
(*)
(ALL X KNIGHT (X) EQV NOT KNAVE (X) AND NOT NORMAL (X))
(ALL X KNAVE (X)
EQV NOT KNIGHT (X) AND NOT NORMAL (X))
(ALL X NORMAL (X) EQV NOT KNIGHT
(X) AND NOT KNAVE (X))
(ALL X,Y,Z HRANK3 (X Y Z) AND KNAVE (X) IMPL NOT HRANK2
(Y Z))
(ALL X,Y,Z HRANK3 (X Y Z) AND KNIGHT (X) IMPL HRANK2 (Y Z))
(ALL X,Y HRANK2
(X Y) EQV KNIGHT (X) AND NOT KNIGHT (Y) OR NORMAL (X) AND KNAVE (Y))
(NORMAL (A) OR NORMAL (B)
OR NORMAL (C))
(KNIGHT (A) OR
KNIGHT (B) OR KNIGHT (C))
(KNAVE
(A) OR KNAVE (B) OR KNAVE (C))
(HRANK3 (A B C))
(HRANK3 (B C A))
(HRANK3 (C B A) OR HRANK3 (C A B))

(HRANK3 (C B A))