;;; -*- Package: MKRP; Base:10.; Syntax: Common-lisp; Mode: LISP -*-

(SORT ELEMENT,MENGE,VERKN:ANY)
(TYPE W (MENGE) :MENGE)
(TYPE EHG (MENGE VERKN) :MENGE)
(TYPE RESTRICTION (MENGE MENGE) :MENGE)
(TYPE CONC:VERKN)

(ALL F,E:MENGE
     ALL MAL1:VERKN
     HG (F MAL1) AND ME (E F)
     IMPL  
     (FERZSYS (E F MAL1)
	      EQV  
	      EHG (E MAL1) = F
	      AND  
	      (ALL H:MENGE  ALL MAL2:VERKN  ALL PHINULL:MENGE  
		   HG (H MAL2) AND ABB (PHINULL E H)
		   IMPL  
		   (EX PHI:MENGE HOMOMORPH (PHI F H) AND RESTRICTION (PHI E) = PHINULL))))

(ALL X:MENGE HG (W (X) CONC))
(ALL X:MENGE ME (X W (X)))

(ALL X:MENGE EHG (X CONC) = W (X))

(ALL X:MENGE  ALL H:MENGE  ALL MAL:VERKN  ALL PHINULL:MENGE  
               HG (H MAL) AND ABB (PHINULL X H)
               IMPL  
               (EX PHI:MENGE HOMOMORPH (PHI W (X) H) AND RESTRICTION (PHI X) = PHINULL))



(ALL X:MENGE FERZSYS (X W (X) CONC))
 
 