;;; -*- Package: MKRP; Base: 10.; Mode: LISP; Syntax: Common-lisp -*- 


(SORT MENGE,ELEMENT,VERKN,ABB:ANY)
(TYPE W(MENGE) :MENGE)
(TYPE RESTRICTION(ABB MENGE) :ABB)
(TYPE MAPC(ABB ELEMENT) :ELEMENT)
(TYPE MAL,CONC:ABB)
(TYPE ELEM(MENGE) :ABB)
(TYPE CHI,CHINULL:ABB)
(TYPE F,X:MENGE)
(TYPE EHG(MENGE ABB) :MENGE)
(TYPE T:ELEMENT)
(* INJEKTIV *)
(ALL A,B:MENGE  ALL PHI:ABB  
     (ALL U,V:ELEMENT EL(U A) AND EL(V A) AND MAPC(PHI U) = MAPC(PHI V) IMPL U = V) IMPL INJEKTIV(PHI A B))
(* DEF. FREIES ERZEUGENDESSYSTEM 1.TEIL *)
(ALL H:MENGE ALL MAL2:ABB HG(H MAL2) AND FREI(H MAL2) IMPL(EX E:MENGE EHG(E MAL2) = H))
(* WIRKUNG VON MAPC AUF ELEMENTE EINER HALBGRUPPE *)
(ALL U,V:ELEMENT  ALL MAL2:ABB  ALL H:MENGE  
     HG(H MAL2) AND EL(U H) AND EL(V H) AND U=V IMPL MAPC(MAL2 U) = MAPC(MAL2 V))
(* DEF. VON HOMOMORPHISMUS UNTER VERWENDUNG VON MAPC *)
(ALL H,G:MENGE  ALL MAL1,MAL2,PHI:ABB  
     HG(H MAL1) AND HG(G MAL2) AND HOMOMORPH(PHI H G)
     IMPL (ALL U:ELEMENT MAPC(ELEM(H) U) = T IMPL MAPC(PHI MAPC(MAL1 U)) = MAPC(MAL2 MAPC(PHI U))))
(ALL A:MENGE EX PHINULL:ABB ABBILDUNG(PHINULL A W(A)) AND(ALL Y:ELEMENT EL(Y A) IMPL MAPC(PHINULL Y) = Y))
(ALL A,B,C:MENGE  ALL PHI,PHINULL:ABB  
     ABBILDUNG(PHI A B) AND RESTRICTION(PHI C) = PHINULL
     IMPL (ALL Y:ELEMENT EL(Y C) IMPL MAPC(PHINULL Y) = MAPC(PHI Y)) AND ABBILDUNG(PHINULL C B) AND ME(C A))
(ALL H:MENGE  ALL MAL2:ABB  ALL Y:ELEMENT  EX E:MENGE  
     HG(H MAL2) AND EL(Y H) AND EHG(E MAL2) = H IMPL(EX U:ELEMENT MAPC(ELEM(E) U) = T AND MAPC(MAL2 U) = Y))

(HG(F MAL) AND FREI(F MAL) AND HOMOMORPH(CHI F W(X)) AND RESTRICTION(CHI X) = CHINULL
   IMPL INJEKTIV(CHI F W(X)))