;;; -*- Mode: Lisp; Syntax: Common-lisp; Package: MKRP -*-)
(* ************************************************)
(* DEFINITIONEN DER MENGENLEHRE)
(SORT SET:ANY)
(SORT ELEMENT:SET)
(TYPE EL (ELEMENT SET))
(SORT EL.OF.S:ELEMENT)
(* DEFINITION 1.7: FUNKTION)
(SORT SYMB.OF.FUNCTION:ANY)
(TYPE MAPPING.S (SYMB.OF.FUNCTION SET SET))
(TYPE S:SET)
(SORT EL.OF.S:ELEMENT)
(TYPE APPLY (SYMB.OF.FUNCTION ELEMENT) :ELEMENT)
(ALL F:SYMB.OF.FUNCTION ALL Y:SET MAPPING.S (F S Y) IMPL (ALL A:EL.OF.S EL (APPLY (F A) Y)))
(* DEFINITION 1.8: SURJEKTIV)
(TYPE SURJECTIVE.S (SYMB.OF.FUNCTION SET SET))
(ALL F:SYMB.OF.FUNCTION ALL Y:SET 
     SURJECTIVE.S (F S Y)
     IMPL 
     MAPPING.S (F S Y) AND (ALL B:ELEMENT EL (B Y) IMPL (EX A:EL.OF.S APPLY (F A) = B)))

(ALL GR.PHI,PHI1,PHI2:SYMB.OF.FUNCTION ALL U,V:SET )
(ALL T:EL.OF.S APPLY (GR.PHI APPLY (PHI1 T)) = APPLY (PHI2 T)
     AND 
     SURJECTIVE.S (PHI1 S U)
     AND 
     MAPPING.S (PHI2 S V)
     IMPL 
     (ALL U1:ELEMENT EL (U1 U) IMPL (EX V1:ELEMENT EL (V1 V) AND APPLY (GR.PHI U1) = V1)))
