;;; -*- Package: MKRP; Mode: LISP; Syntax: Common-lisp -*-
(SORT MENGE,NAT:ANY)
(TYPE CARD (MENGE) :NAT)
(TYPE W (MENGE) :MENGE)
(* DEFINITION VON CARD *)
(ALL X,Y,PHI:MENGE ISOMORPH (PHI X Y) IMPL CARD (X) = CARD (Y))
(* LEMMA 2.6.LR.1 *)
(ALL X,Y,PHI:MENGE ISOMORPH (PHI W (X) W (Y)) IMPL (EX PSI:MENGE ISOMORPH (PSI X Y)))
 
(ALL X,Y,PHI:MENGE ISOMORPH (PHI W (X) W (Y)) IMPL CARD (X) = CARD (Y))
 
 