;;; -*- Package: MKRP; Base: 10; Mode: LISP; Syntax: Common-lisp -*-

(problem andrews0 proved
    ((type-constants ANY)
    (constants (P (O ANY)))
    (conclusion th1 (EQUIV (EXISTS (LAM (X_3 ANY) (FORALL (LAM (X_4 ANY) (EQUIV (P X_3) (P X_4)))))) (EQUIV (EXISTS (LAM (X_6 ANY) (P X_6))) (FORALL (LAM (X_7 ANY) (P X_7)))))))
    (resolution-proof
        (cnf (
            (clause R.= ((X_8 ANY)) (+ (= X_8 X_8)))
            (clause T1 ((X_15 ANY)(X_11 ANY)) (- (P X_11)) (- (P (F_1 X_11))) (- (P X_15)) (- (P C_1)))
            (clause T2 ((X_27 ANY)(X_29 ANY)) (- (P X_29)) (- (P (F_1 X_29))) (+ (P C_2)) (+ (P X_27)))
            (clause T3 ((X_4 ANY)(X_26 ANY)) (+ (P X_26)) (+ (P (F_1 X_26))) (- (P X_4)) (- (P C_1)))
            (clause T4 ((X_14 ANY)(X_7 ANY)) (+ (P X_7)) (+ (P (F_1 X_7))) (+ (P C_2)) (+ (P X_14)))
            (clause T5 ((X_21 ANY)) (+ (P C_3)) (- (P X_21)) (+ (P C_4)) (- (P C_5)))
            (clause T6 ((X_22 ANY)(X_23 ANY)(X_24 ANY)) (+ (P C_3)) (- (P X_24)) (- (P X_23)) (+ (P X_22)))
            (clause T7 ((X_25 ANY)) (- (P C_3)) (+ (P X_25)) (+ (P C_4)) (- (P C_5)))
            (clause T8 ((X_18 ANY)(X_6 ANY)(X_19 ANY)) (- (P C_3)) (+ (P X_19)) (- (P X_6)) (+ (P X_18))))
            (delta-relation 
          (th1 ((POSITION 1 1 0 1 0 1) (T8 (POSITION 0))))
          (th1 ((POSITION 1 1 0 1 0 2) (T8 (POSITION 1))))
          (th1 ((POSITION 2 1 1 0) (T8 (POSITION 2))))
          (th1 ((POSITION 2 2 1 0) (T8 (POSITION 3))))
          (th1 ((POSITION 1 1 0 1 0 1) (T7 (POSITION 0))))
          (th1 ((POSITION 1 1 0 1 0 2) (T7 (POSITION 1))))
          (th1 ((POSITION 2 1 1 0) (T7 (POSITION 2))))
          (th1 ((POSITION 2 2 1 0) (T7 (POSITION 3))))
          (th1 ((POSITION 1 1 0 1 0 1) (T6 (POSITION 0))))
          (th1 ((POSITION 1 1 0 1 0 2) (T6 (POSITION 1))))
          (th1 ((POSITION 2 1 1 0) (T6 (POSITION 2))))
          (th1 ((POSITION 2 2 1 0) (T6 (POSITION 3))))
          (th1 ((POSITION 1 1 0 1 0 1) (T5 (POSITION 0))))
          (th1 ((POSITION 1 1 0 1 0 2) (T5 (POSITION 1))))
          (th1 ((POSITION 2 1 1 0) (T5 (POSITION 2))))
          (th1 ((POSITION 2 2 1 0) (T5 (POSITION 3))))
          (th1 ((POSITION 1 1 0 1 0 1) (T4 (POSITION 0))))
          (th1 ((POSITION 1 1 0 1 0 2) (T4 (POSITION 1))))
          (th1 ((POSITION 2 1 1 0) (T4 (POSITION 2))))
          (th1 ((POSITION 2 2 1 0) (T4 (POSITION 3))))
          (th1 ((POSITION 1 1 0 1 0 1) (T3 (POSITION 0))))
          (th1 ((POSITION 1 1 0 1 0 2) (T3 (POSITION 1))))
          (th1 ((POSITION 2 1 1 0) (T3 (POSITION 2))))
          (th1 ((POSITION 2 2 1 0) (T3 (POSITION 3))))
          (th1 ((POSITION 1 1 0 1 0 1) (T2 (POSITION 0))))
          (th1 ((POSITION 1 1 0 1 0 2) (T2 (POSITION 1))))
          (th1 ((POSITION 2 1 1 0) (T2 (POSITION 2))))
          (th1 ((POSITION 2 2 1 0) (T2 (POSITION 3))))
          (th1 ((POSITION 1 1 0 1 0 1) (T1 (POSITION 0))))
          (th1 ((POSITION 1 1 0 1 0 2) (T1 (POSITION 1))))
          (th1 ((POSITION 2 1 1 0) (T1 (POSITION 2))))
          (th1 ((POSITION 2 2 1 0) (T1 (POSITION 3))))))
        (factoring step-0 
          (clause T1.Ren0 ((X_41 ANY)(X_42 ANY)) (- (P X_42)) (- (P (F_1 X_42))) (- (P C_1)))
          (T1 (position 3) (position 2))
          (substitution (X_15) (C_1))
          (substitution (X_15 X_11) (X_41 X_42)))
        (factoring step-1 
          (clause T2.Ren1 ((X_58 ANY)(X_59 ANY)) (- (P X_59)) (- (P (F_1 X_59))) (+ (P C_2)))
          (T2 (position 2) (position 3))
          (substitution (X_27) (C_2))
          (substitution (X_27 X_29) (X_58 X_59)))
        (factoring step-2 
          (clause T3.Ren2 ((X_82 ANY)(X_83 ANY)) (+ (P X_83)) (+ (P (F_1 X_83))) (- (P C_1)))
          (T3 (position 3) (position 2))
          (substitution (X_4) (C_1))
          (substitution (X_4 X_26) (X_82 X_83)))
        (factoring step-3 
          (clause T4.Ren3 ((X_112 ANY)(X_113 ANY)) (+ (P X_113)) (+ (P (F_1 X_113))) (+ (P C_2)))
          (T4 (position 2) (position 3))
          (substitution (X_14) (C_2))
          (substitution (X_14 X_7) (X_112 X_113)))
        (factoring step-4 
          (clause T5.Ren4 ((X_131 ANY)) (+ (P C_3)) (+ (P C_4)) (- (P C_5)))
          (T5 (position 3) (position 1))
          (substitution (X_21) (C_5))
          (substitution (X_21) (X_131)))
        (factoring step-5 
          (clause T6.Ren5 ((X_180 ANY)(X_181 ANY)(X_182 ANY)) (+ (P C_3)) (- (P X_182)) (+ (P X_180)))
          (T6 (position 1) (position 2))
          (substitution (X_23) (X_24))
          (substitution (X_22 X_23 X_24) (X_180 X_181 X_182)))
        (factoring step-6 
          (clause T6.Ren6 ((X_183 ANY)(X_184 ANY)) (+ (P C_3)) (- (P X_184)))
          (T6.Ren5 (position 0) (position 2))
          (substitution (X_180) (C_3))
          (substitution (X_180 X_182) (X_183 X_184)))
        (resolution step-0 
          (clause T6.Ren7 ((X_189 ANY)(X_190 ANY)) (+ (P C_3)) (+ (P C_2)) (+ (P (F_1 C_2))))
          (T6.Ren6 (position 1)) (T4.Ren3 (position 2))
          (substitution (X_184 X_113) (C_2 C_2))
          (substitution (X_184 X_113) (X_189 X_190)))
        (resolution step-1 
          (clause T6.Ren8 ((X_191 ANY)(X_192 ANY)) (+ (P C_3)) (+ (P (F_1 C_2))) (+ (P C_3)))
          (T6.Ren7 (position 1)) (T6.Ren6 (position 1))
          (substitution (X_189 X_190 X_184) (C_2 C_2 C_2))
          (substitution (X_189 X_190) (X_191 X_192)))
        (factoring step-7 
          (clause T6.Ren9 ((X_193 ANY)(X_194 ANY)) (+ (P C_3)) (+ (P (F_1 C_2))))
          (T6.Ren8 (position 0) (position 2))
          (substitution (X_191 X_192) (C_2 C_2))
          (substitution (X_191 X_192) (X_193 X_194)))
        (factoring step-8 
          (clause T7.Ren10 ((X_158 ANY)) (- (P C_3)) (+ (P C_4)) (- (P C_5)))
          (T7 (position 2) (position 1))
          (substitution (X_25) (C_4))
          (substitution (X_25) (X_158)))
        (factoring step-9 
          (clause T8.Ren11 ((X_198 ANY)(X_199 ANY)(X_200 ANY)) (- (P C_3)) (+ (P X_200)) (- (P X_199)))
          (T8 (position 1) (position 3))
          (substitution (X_18) (X_19))
          (substitution (X_18 X_6 X_19) (X_198 X_199 X_200)))
        (factoring step-10 
          (clause T8.Ren12 ((X_201 ANY)(X_202 ANY)) (- (P C_3)) (+ (P X_202)))
          (T8.Ren11 (position 0) (position 2))
          (substitution (X_199) (C_3))
          (substitution (X_199 X_200) (X_201 X_202)))
        (resolution step-2 
          (clause T8.Ren13 ((X_204 ANY)(X_205 ANY)) (- (P C_3)) (- (P C_3)) (- (P (F_1 C_3))))
          (T8.Ren12 (position 1)) (T1.Ren0 (position 2))
          (substitution (X_202 X_42) (C_1 C_3))
          (substitution (X_202 X_42) (X_204 X_205)))
        (resolution step-3 
          (clause T8.Ren14 ((X_206 ANY)(X_207 ANY)) (- (P C_3)) (- (P (F_1 C_3))))
          (T8.Ren13 (position 1)) (T6.Ren9 (position 0))
          (substitution (X_204 X_205) (C_1 C_3))
          (substitution (X_204 X_205) (X_206 X_207))))
    (prover mkrp 
        (options (TWO_RULES)
         (TWO_RULES.MAXLEVEL . 1)
         (TWO_SUPPRESS.NORULES)
         (RED.I_CLAUSE.MULTIPLE.LITERALS . T)
         (RED.I_CLAUSE.PURITY . PARTIAL)
         (RED.I_CLAUSE.TAUTOLOGY . T)
         (RED.I_CLAUSE.TAUTOLOGY.RECHECK . PARTIAL)
         (RED.I_CLAUSE.SUBSUMPTION . T)
         (RED.I_CLAUSE.SUBSUMPTION.RECHECK . PARTIAL)
         (RED.I_CLAUSE.REPL.FACTORING . T)
         (RED.I_CLAUSE.REPL.FACTORING.RECHECK . T)
         (RED.I_CLAUSE.REPL.RESOLUTION . SIMPLE)
         (RED.I_CLAUSE.REPL.RESOLUTION.RECHECK . T)
         (RED.I_CLAUSE.REWRITING . DEM)
         (RED.I_LINK.INCOMPATIBILITY . T)
         (RED.I_LINK.TAUTOLOGY . REMOVE-INHIBIT)
         (RED.I_LINK.TAUTOLOGY.RECHECK)
         (RED.I_LINK.SUBSUMPTION . REMOVE-INHIBIT)
         (RED.I_LINK.SUBSUMPTION.RECHECK)
         (RED.D_CLAUSE.MULTIPLE.LITERALS . T)
         (RED.D_CLAUSE.PURITY . PARTIAL)
         (RED.D_CLAUSE.TAUTOLOGY . REMOVE-INHIBIT)
         (RED.D_CLAUSE.TAUTOLOGY.RECHECK)
         (RED.D_CLAUSE.SUBSUMPTION.FORWARD . REMOVE-INHIBIT)
         (RED.D_CLAUSE.SUBSUMPTION.BACKWARD . REMOVE)
         (RED.D_CLAUSE.SUBSUMPTION.RECHECK)
         (RED.D_CLAUSE.REPL.FACTORING . T)
         (RED.D_CLAUSE.REPL.FACTORING.RECHECK . T)
         (RED.D_CLAUSE.REPL.RESOLUTION . SIMPLE)
         (RED.D_CLAUSE.REPL.RESOLUTION.RECHECK . T)
         (RED.D_CLAUSE.REWRITING . DEM)
         (RED.D_LINK.INCOMPATIBILITY . T)
         (RED.D_LINK.TAUTOLOGY . REMOVE-INHIBIT)
         (RED.D_LINK.TAUTOLOGY.RECHECK)
         (RED.D_LINK.SUBSUMPTION . REMOVE-INHIBIT)
         (RED.D_LINK.SUBSUMPTION.RECHECK)
         (FAC_INITIAL)
         (FAC_EACH.STEP)
         (STR_RESOLUTION . SET-OF-SUPPORT)
         (STR_R.SELECTION * 10 (+ 2 VARIABLES (* 2 DEPTH) (* 3 NOLIT)))
         (STR_LINK.DEPTH)
         (STR_TERM.DEPTH)
         (STR_FINITE.DOMAIN . T)
         (TERM_UNITS . T)
         (TERM_ITERATIONS . 0)
         (TERM_SET.OF.SUPPORT)
         (TERM_BREADTH.FIRST)
         (SORT_LITERALS)
         (SORT_MAX.UNIFICATION.RULE.STEPS . 100)
         (SORT_MAX.UNIFICATION.TREE.DEPTH . 100)
         (SORT_MAX.UNIFICATION.TREE.OPEN.NODES . 20)
         (SORT_UNIFIER.STOP.NUMBER . 100)
         (SORT_SHOW.VARIABLE.SORTS . T)
         (ER_PARAMODULATION . HEURISTIC-COMPLETION)
         (ER_WEIGHT.POLYNOMIALS)
         (ER_P.SELECTION * WEIGHT (IF SUPPORT 1 1.5) (IF EQUATIONAL 1 2))
         (ER_COMPLETION . UNFAILING)
         (ER_CP.REDUCTION . T)
         (ER_ORDERING . LEXICOGRAPHIC-RECURSIVE-PATH)
         (ER_OPERATOR.ORDERING * - + 0 1)
         (ER_KNUTH.BENDIX.WEIGHT (+ 1) (* 1) (- 0) (0 1) (1 1))
         (ER_POLYNOMIAL.WEIGHT (+ (X Y) (+ (* 2 Y) X)) (* (X Y) (+ (* X Y) X)) (- (X) (* X X)) (0 NIL 2) (1 NIL 2))
         (ER_NARROW.DEPTH . 0)
         (ER_NARROW.NEXT . DEPTH)
         (ER_NARROW.TEST NORM C DELTA SL N)
         (GEN_SPLITTING . 0)
         (GEN_PRESIMPLIFICATION . T)
         (GEN_MIN.EXPRESSION.LENGTH.FOR.FILE)
         (GEN_MIN.EXPRESSION.SIZE.FOR.FILE)
         (GEN_MANUAL.CONTROL)
         (GEN_MAXIMUM.STEPS)
         (GEN_MAXIMUM.TIME)
         (GEN_GRAPH.SAVING)
         (GEN_SAVE.FILE . SAVEDEFAULT)
         (GEN_LISP.GARBAGE.COLLECTION)
         (GEN_COMMON.LISP . T)
         (GEN_OTHER.PROVER . MKRP)
         (TR_PREPROCESSING)
         (TR_STEP.MODE . LR)
         (TR_DUMP)
         (TR_CLAUSE.MODE . I)
         (TR_LINK.MODE . I)
         (TR_TRACE.FILE)
         (TR_TERMINAL . T)
         (PR_INFIX.FORM . T)
         (PR_PREFIX.FORM)
         (PR_OPTIONS)
         (PR_AXIOM.CLAUSES . T)
         (PR_SYMBOLS)
         (PR_DIRECT.PROOF . T)
         (PR_VARIABLE.PRINT.NAMES X Y Z U V W XX YY ZZ UU VV WW XXX YYY ZZZ UUU VVV WWW)
         (PR_PROTOCOL . POST)
         (PR_LEFT.MARGIN . 0)
         (PR_RIGHT.MARGIN . 117)
         (PR_LATEX)
         (PR_LINELENGTH . 117)
         (PR_LITERALS)
        )))