;;; -*- Package: MKRP; Base: 10; Mode: LISP; Syntax: Common-lisp -*-
(PREP-PROBLEM.SPECIFICATION (QUOTE ((* PROBLEM 50) (*) (* ONE DAY ALICE MET THE LION.) (* HE MADE THE FOLLOWING STATEMENT :) (*) (* I LIED YESTERDAY AND) (* I WILL LIE AGAIN TOMORROW.) (*) (* ON WHAT DAYS OF THE WEEK IS THIS POSSIBLE?) (*) (*) (* FORMALIZING THE PROBLEM IN FIRST ORDER LOGIC) (*) (ALL X : DAYS MO (X) EQV (NOT TU (X) AND NOT WE (X) AND NOT TH (X) AND NOT FR (X) AND NOT SA (X) AND NOT SU (X))) (ALL X : DAYS TU (X) EQV (NOT MO (X) AND NOT WE (X) AND NOT TH (X) AND NOT FR (X) AND NOT SA (X) AND NOT SU (X))) (ALL X : DAYS WE (X) EQV (NOT MO (X) AND NOT TU (X) AND NOT TH (X) AND NOT FR (X) AND NOT SA (X) AND NOT SU (X))) (ALL X : DAYS TH (X) EQV (NOT MO (X) AND NOT TU (X) AND NOT WE (X) AND NOT FR (X) AND NOT SA (X) AND NOT SU (X))) (ALL X : DAYS FR (X) EQV (NOT MO (X) AND NOT TU (X) AND NOT WE (X) AND NOT TH (X) AND NOT SA (X) AND NOT SU (X))) (ALL X : DAYS SA (X) EQV (NOT MO (X) AND NOT TU (X) AND NOT WE (X) AND NOT TH (X) AND NOT FR (X) AND NOT SU (X))) (ALL X : DAYS SU (X) EQV (NOT MO (X) AND NOT TU (X) AND NOT WE (X) AND NOT TH (X) AND NOT FR (X) AND NOT SA (X))) (*) (TYPE YESTERDAY (DAYS) : DAYS) (ALL X : DAYS MO (YESTERDAY (X)) EQV TU (X)) (ALL X : DAYS TU (YESTERDAY (X)) EQV WE (X)) (ALL X : DAYS WE (YESTERDAY (X)) EQV TH (X)) (ALL X : DAYS TH (YESTERDAY (X)) EQV FR (X)) (ALL X : DAYS FR (YESTERDAY (X)) EQV SA (X)) (ALL X : DAYS SA (YESTERDAY (X)) EQV SU (X)) (ALL X : DAYS SU (YESTERDAY (X)) EQV MO (X)) (*) (TYPE TOMORROW (DAYS) : DAYS) (ALL X : DAYS MO (TOMORROW (X)) EQV SU (X)) (ALL X : DAYS TU (TOMORROW (X)) EQV MO (X)) (ALL X : DAYS WE (TOMORROW (X)) EQV TU (X)) (ALL X : DAYS TH (TOMORROW (X)) EQV WE (X)) (ALL X : DAYS FR (TOMORROW (X)) EQV TH (X)) (ALL X : DAYS SA (TOMORROW (X)) EQV FR (X)) (ALL X : DAYS SU (TOMORROW (X)) EQV SA (X)) (*) (* THE PREDICATE LA2 HAS THE FOLLOWING MEANING :) (* LA (X Y Z U) MEANS THAT X COULD SAY AT THE DAY Y : I LIE AT DAY Z AND U.) (*) (TYPE LA2 (ANIMAL DAYS DAYS DAYS)) (TYPE LION : ANIMAL) (ALL X : DAYS MEMBER (X LYING.DAYS (LION)) EQV (MO (X) OR TU (X) OR WE (X))) (*) (ALL T : ANIMAL ALL X,Y,U : DAYS NOT MEMBER (X LYING.DAYS (T)) AND MEMBER (Y LYING.DAYS (T)) AND MEMBER (U LYING.DAYS (T)) IMPL LA2 (T X Y U)) (ALL T : ANIMAL ALL X,Y,U : DAYS MEMBER (X LYING.DAYS (T)) AND MEMBER (Y LYING.DAYS (T)) AND MEMBER (U LYING.DAYS (T)) IMPL NOT LA2 (T X Y U)) (ALL T : ANIMAL ALL X,Y,U : DAYS NOT MEMBER (X LYING.DAYS (T)) AND NOT (MEMBER (Y LYING.DAYS (T)) AND MEMBER (U LYING.DAYS (T))) IMPL NOT LA2 (T X Y U)) (ALL T : ANIMAL ALL X,Y,U : DAYS MEMBER (X LYING.DAYS (T)) AND NOT (MEMBER (Y LYING.DAYS (T)) AND MEMBER (U LYING.DAYS (T))) IMPL LA2 (T X Y U)) (*) (*) (TYPE MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY,SUNDAY : DAYS) (MO (MONDAY)) (TU (TUESDAY)) (WE (WEDNESDAY)) (TH (THURSDAY)) (FR (FRIDAY)) (SA (SATURDAY)) (SU (SUNDAY)) (*))) (QUOTE (COMMENT COMMENT COMMENT COMMENT COMMENT COMMENT COMMENT COMMENT COMMENT COMMENT COMMENT COMMENT COMMENT (ALL 2 (EQV (+ 3 (2) (KIND (EQV T 150))) (AND (NOT (+ 4 (2) (KIND (EQV NIL 150)))) (AND (NOT (+ 5 (2) (KIND (EQV NIL 150)))) (AND (NOT (+ 6 (2) (KIND (EQV NIL 150)))) (AND (NOT (+ 7 (2) (KIND (EQV NIL 150)))) (AND (NOT (+ 8 (2) (KIND (EQV NIL 150)))) (NOT (+ 9 (2) (KIND (EQV NIL 150))))))))))) (ALL 10 (EQV (+ 4 (10) (KIND (EQV T 160))) (AND (NOT (+ 3 (10) (KIND (EQV NIL 160)))) (AND (NOT (+ 5 (10) (KIND (EQV NIL 160)))) (AND (NOT (+ 6 (10) (KIND (EQV NIL 160)))) (AND (NOT (+ 7 (10) (KIND (EQV NIL 160)))) (AND (NOT (+ 8 (10) (KIND (EQV NIL 160)))) (NOT (+ 9 (10) (KIND (EQV NIL 160))))))))))) (ALL 11 (EQV (+ 5 (11) (KIND (EQV T 170))) (AND (NOT (+ 3 (11) (KIND (EQV NIL 170)))) (AND (NOT (+ 4 (11) (KIND (EQV NIL 170)))) (AND (NOT (+ 6 (11) (KIND (EQV NIL 170)))) (AND (NOT (+ 7 (11) (KIND (EQV NIL 170)))) (AND (NOT (+ 8 (11) (KIND (EQV NIL 170)))) (NOT (+ 9 (11) (KIND (EQV NIL 170))))))))))) (ALL 12 (EQV (+ 6 (12) (KIND (EQV T 180))) (AND (NOT (+ 3 (12) (KIND (EQV NIL 180)))) (AND (NOT (+ 4 (12) (KIND (EQV NIL 180)))) (AND (NOT (+ 5 (12) (KIND (EQV NIL 180)))) (AND (NOT (+ 7 (12) (KIND (EQV NIL 180)))) (AND (NOT (+ 8 (12) (KIND (EQV NIL 180)))) (NOT (+ 9 (12) (KIND (EQV NIL 180))))))))))) (ALL 13 (EQV (+ 7 (13) (KIND (EQV T 190))) (AND (NOT (+ 3 (13) (KIND (EQV NIL 190)))) (AND (NOT (+ 4 (13) (KIND (EQV NIL 190)))) (AND (NOT (+ 5 (13) (KIND (EQV NIL 190)))) (AND (NOT (+ 6 (13) (KIND (EQV NIL 190)))) (AND (NOT (+ 8 (13) (KIND (EQV NIL 190)))) (NOT (+ 9 (13) (KIND (EQV NIL 190))))))))))) (ALL 14 (EQV (+ 8 (14) (KIND (EQV T 200))) (AND (NOT (+ 3 (14) (KIND (EQV NIL 200)))) (AND (NOT (+ 4 (14) (KIND (EQV NIL 200)))) (AND (NOT (+ 5 (14) (KIND (EQV NIL 200)))) (AND (NOT (+ 6 (14) (KIND (EQV NIL 200)))) (AND (NOT (+ 7 (14) (KIND (EQV NIL 200)))) (NOT (+ 9 (14) (KIND (EQV NIL 200))))))))))) (ALL 15 (EQV (+ 9 (15) (KIND (EQV T 210))) (AND (NOT (+ 3 (15) (KIND (EQV NIL 210)))) (AND (NOT (+ 4 (15) (KIND (EQV NIL 210)))) (AND (NOT (+ 5 (15) (KIND (EQV NIL 210)))) (AND (NOT (+ 6 (15) (KIND (EQV NIL 210)))) (AND (NOT (+ 7 (15) (KIND (EQV NIL 210)))) (NOT (+ 8 (15) (KIND (EQV NIL 210))))))))))) COMMENT (+ 0 NIL) (ALL 17 (EQV (+ 3 ((16 17)) (KIND (EQV T 240))) (+ 4 (17) (KIND (EQV NIL 240))))) (ALL 18 (EQV (+ 4 ((16 18)) (KIND (EQV T 250))) (+ 5 (18) (KIND (EQV NIL 250))))) (ALL 19 (EQV (+ 5 ((16 19)) (KIND (EQV T 260))) (+ 6 (19) (KIND (EQV NIL 260))))) (ALL 20 (EQV (+ 6 ((16 20)) (KIND (EQV T 270))) (+ 7 (20) (KIND (EQV NIL 270))))) (ALL 21 (EQV (+ 7 ((16 21)) (KIND (EQV T 280))) (+ 8 (21) (KIND (EQV NIL 280))))) (ALL 22 (EQV (+ 8 ((16 22)) (KIND (EQV T 290))) (+ 9 (22) (KIND (EQV NIL 290))))) (ALL 23 (EQV (+ 9 ((16 23)) (KIND (EQV T 300))) (+ 3 (23) (KIND (EQV NIL 300))))) COMMENT (+ 0 NIL) (ALL 25 (EQV (+ 3 ((24 25)) (KIND (EQV T 330))) (+ 9 (25) (KIND (EQV NIL 330))))) (ALL 26 (EQV (+ 4 ((24 26)) (KIND (EQV T 340))) (+ 3 (26) (KIND (EQV NIL 340))))) (ALL 27 (EQV (+ 5 ((24 27)) (KIND (EQV T 350))) (+ 4 (27) (KIND (EQV NIL 350))))) (ALL 28 (EQV (+ 6 ((24 28)) (KIND (EQV T 360))) (+ 5 (28) (KIND (EQV NIL 360))))) (ALL 29 (EQV (+ 7 ((24 29)) (KIND (EQV T 370))) (+ 6 (29) (KIND (EQV NIL 370))))) (ALL 30 (EQV (+ 8 ((24 30)) (KIND (EQV T 380))) (+ 7 (30) (KIND (EQV NIL 380))))) (ALL 31 (EQV (+ 9 ((24 31)) (KIND (EQV T 390))) (+ 8 (31) (KIND (EQV NIL 390))))) COMMENT COMMENT COMMENT COMMENT (+ 0 NIL) (+ 0 NIL) (ALL 34 (EQV (+ 36 (34 (35 33)) (KIND (EQV T 460))) (OR (+ 3 (34) (KIND (EQV NIL 460))) (OR (+ 4 (34) (KIND (EQV NIL 460))) (+ 5 (34) (KIND (EQV NIL 460))))))) COMMENT (ALL 37 (ALL 40 (ALL 39 (ALL 38 (IMPL (AND (NOT (+ 36 (38 (35 37)) NIL)) (AND (+ 36 (39 (35 37)) NIL) (+ 36 (40 (35 37)) NIL))) (+ 32 (37 38 39 40) NIL)))))) (ALL 41 (ALL 44 (ALL 43 (ALL 42 (IMPL (AND (+ 36 (42 (35 41)) NIL) (AND (+ 36 (43 (35 41)) NIL) (+ 36 (44 (35 41)) NIL))) (NOT (+ 32 (41 42 43 44) NIL))))))) (ALL 45 (ALL 48 (ALL 47 (ALL 46 (IMPL (AND (NOT (+ 36 (46 (35 45)) NIL)) (NOT (AND (+ 36 (47 (35 45)) NIL) (+ 36 (48 (35 45)) NIL)))) (NOT (+ 32 (45 46 47 48) NIL))))))) (ALL 49 (ALL 52 (ALL 51 (ALL 50 (IMPL (AND (+ 36 (50 (35 49)) NIL) (NOT (AND (+ 36 (51 (35 49)) NIL) (+ 36 (52 (35 49)) NIL)))) (+ 32 (49 50 51 52) NIL)))))) COMMENT COMMENT (+ 0 NIL) (+ 3 (53) NIL) (+ 4 (54) NIL) (+ 5 (55) NIL) (+ 6 (56) NIL) (+ 7 (57) NIL) (+ 8 (58) NIL) (+ 9 (59) NIL) COMMENT)) (QUOTE ((EX X : DAYS LA2 (LION X YESTERDAY (X) TOMORROW (X))))) (QUOTE ((EX 60 (+ 32 (33 60 (16 60) (24 60)) NIL)))) (QUOTE ("Edit:     Axioms and Theorems edited: 15-DEC,1989 01:34 ")) (PROGN(PROGN (DT-RESET))

(PROG ((ADDRLIST
        '(9562 9567 9572 9577 9582 9587 9592 9597 9602 9607 9612 9617 9622 9627 9632 9637 9642
          9647 9652 9657 9662 9667 9672 9677 9692 9706 9711 9716 9731 9736 9741 9746 9751 9756
          9761 9766 9780 9785 9790 9795 9800 9805 9810 9815 9829 9834 9839 9844 9849 9854 9859
          9874 9889 9904 9919 9934 9949 9964 9969 9984 9999))
       (DATALIST
        '(15 "TRUE" NIL NIL NIL (DEFINED) NIL ((- 0 (POSITIVE))) ((+ 0 (NEGATIVE)))
          ((+ 0 (NIL))) ((- 0 (NIL))) NIL NIL (DT*ST-KIND NIL) PREDICATE 15 "FALSE" NIL NIL
          NIL (DEFINED) NIL ((- 1 (POSITIVE))) ((+ 1 (NEGATIVE))) ((+ 1 (NIL))) ((- 1 (NIL)))
          NIL NIL (DT*ST-KIND NIL) PREDICATE 5 DAYS NIL (ST*DATA NIL DT*ST-KIND SYS-VAR)
          VARIABLE 15 "MO" NIL NIL (ANY) NIL NIL ((- 3 (POSITIVE))) ((+ 3 (NEGATIVE)))
          ((+ 3 (NIL))) ((- 3 (NIL))) NIL NIL (DT*ST-KIND NIL) PREDICATE 15 "TU" NIL NIL (ANY)
          NIL NIL ((- 4 (POSITIVE))) ((+ 4 (NEGATIVE))) ((+ 4 (NIL))) ((- 4 (NIL))) NIL NIL
          (DT*ST-KIND NIL) PREDICATE 15 "WE" NIL NIL (ANY) NIL NIL ((- 5 (POSITIVE)))
          ((+ 5 (NEGATIVE))) ((+ 5 (NIL))) ((- 5 (NIL))) NIL NIL (DT*ST-KIND NIL) PREDICATE 15
          "TH" NIL NIL (ANY) NIL NIL ((- 6 (POSITIVE))) ((+ 6 (NEGATIVE))) ((+ 6 (NIL)))
          ((- 6 (NIL))) NIL NIL (DT*ST-KIND NIL) PREDICATE 15 "FR" NIL NIL (ANY) NIL NIL
          ((- 7 (POSITIVE))) ((+ 7 (NEGATIVE))) ((+ 7 (NIL))) ((- 7 (NIL))) NIL NIL
          (DT*ST-KIND NIL) PREDICATE 15 "SA" NIL NIL (ANY) NIL NIL ((- 8 (POSITIVE)))
          ((+ 8 (NEGATIVE))) ((+ 8 (NIL))) ((- 8 (NIL))) NIL NIL (DT*ST-KIND NIL) PREDICATE 15
          "SU" NIL NIL (ANY) NIL NIL ((- 9 (POSITIVE))) ((+ 9 (NEGATIVE))) ((+ 9 (NIL)))
          ((- 9 (NIL))) NIL NIL (DT*ST-KIND NIL) PREDICATE 5 DAYS NIL
          (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 DAYS NIL (ST*DATA NIL DT*ST-KIND SYS-VAR)
          VARIABLE 5 DAYS NIL (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 DAYS NIL
          (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 DAYS NIL (ST*DATA NIL DT*ST-KIND SYS-VAR)
          VARIABLE 5 DAYS NIL (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 14 "YESTERDAY" NIL
          DAYS (DAYS) NIL NIL NIL NIL NIL 1 DAYS (DT*ST-KIND NIL) FUNCTION 5 DAYS NIL
          (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 DAYS NIL (ST*DATA NIL DT*ST-KIND SYS-VAR)
          VARIABLE 5 DAYS NIL (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 DAYS NIL
          (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 DAYS NIL (ST*DATA NIL DT*ST-KIND SYS-VAR)
          VARIABLE 5 DAYS NIL (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 DAYS NIL
          (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 14 "TOMORROW" NIL DAYS (DAYS) NIL NIL NIL
          NIL NIL 1 DAYS (DT*ST-KIND NIL) FUNCTION 5 DAYS NIL (ST*DATA NIL DT*ST-KIND SYS-VAR)
          VARIABLE 5 DAYS NIL (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 DAYS NIL
          (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 DAYS NIL (ST*DATA NIL DT*ST-KIND SYS-VAR)
          VARIABLE 5 DAYS NIL (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 DAYS NIL
          (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 DAYS NIL (ST*DATA NIL DT*ST-KIND SYS-VAR)
          VARIABLE 15 "LA2" NIL NIL (ANIMAL DAYS DAYS DAYS) NIL NIL ((- 32 (POSITIVE)))
          ((+ 32 (NEGATIVE))) ((+ 32 (NIL))) ((- 32 (NIL))) NIL NIL (DT*ST-KIND NIL) PREDICATE
          5 ANIMAL "LION" (DT*ST-KIND NIL) CONSTANT 5 DAYS NIL (ST*DATA NIL DT*ST-KIND SYS-VAR)
          VARIABLE 14 "LYING.DAYS" NIL ANY (ANY) NIL NIL NIL NIL NIL 1 ANY (DT*ST-KIND NIL)
          FUNCTION 15 "MEMBER" NIL NIL (ANY ANY) NIL NIL ((- 36 (POSITIVE)))
          ((+ 36 (NEGATIVE))) ((+ 36 (NIL))) ((- 36 (NIL))) NIL NIL (DT*ST-KIND NIL) PREDICATE
          5 ANIMAL NIL (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 DAYS NIL
          (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 DAYS NIL (ST*DATA NIL DT*ST-KIND SYS-VAR)
          VARIABLE 5 DAYS NIL (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 ANIMAL NIL
          (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 DAYS NIL (ST*DATA NIL DT*ST-KIND SYS-VAR)
          VARIABLE 5 DAYS NIL (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 DAYS NIL
          (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 ANIMAL NIL
          (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 DAYS NIL (ST*DATA NIL DT*ST-KIND SYS-VAR)
          VARIABLE 5 DAYS NIL (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 DAYS NIL
          (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 ANIMAL NIL
          (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 DAYS NIL (ST*DATA NIL DT*ST-KIND SYS-VAR)
          VARIABLE 5 DAYS NIL (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 DAYS NIL
          (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 DAYS "MONDAY" (DT*ST-KIND NIL) CONSTANT
          5 DAYS "TUESDAY" (DT*ST-KIND NIL) CONSTANT 5 DAYS "WEDNESDAY" (DT*ST-KIND NIL)
          CONSTANT 5 DAYS "THURSDAY" (DT*ST-KIND NIL) CONSTANT 5 DAYS "FRIDAY" (DT*ST-KIND NIL)
          CONSTANT 5 DAYS "SATURDAY" (DT*ST-KIND NIL) CONSTANT 5 DAYS "SUNDAY" (DT*ST-KIND NIL)
          CONSTANT 5 DAYS NIL (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE))
       (INCREMENT (- MEM*SIZE 10000))
       COUNTER1)
      (MEM-RESET)
      (COND ((> MEM*SIZE 10000)
             (SETQ COUNTER1 61)
             (MAPC #'(LAMBDA (RADDR)
                       (SETF (AREF MEM*MEMORY (DECF COUNTER1))
                              (COND ((EQL RADDR 'ATP.MEMORY.NIL) RADDR)
                                    ((EQL 'END RADDR) RADDR)
                                    ((OR (EQL RADDR 0)
                                         (MINUSP RADDR))
                                     RADDR)
                                    (T (+ RADDR INCREMENT)))))
                   ADDRLIST)
             (SETQ COUNTER1 MEM*SIZE)
             (MAPC #'(LAMBDA (DATA) (SETF (AREF MEM*MEMORY (DECF COUNTER1)) DATA)) DATALIST))
            (T (UNLESS (= MEM*SIZE 10000)
                 (MEM-INITIALIZE 10000))
               (SETQ COUNTER1 61)
               (MAPC #'(LAMBDA (RADDR) (SETF (AREF MEM*MEMORY (DECF COUNTER1)) RADDR))
                     ADDRLIST)
               (SETQ COUNTER1 MEM*SIZE)
               (MAPC #'(LAMBDA (DATA) (SETF (AREF MEM*MEMORY (DECF COUNTER1)) DATA)) DATALIST))
            )
      (SETQ MEM*NEXT.RADR (IF (> MEM*SIZE 10000) (+ 9557 INCREMENT) 9557))
      (SETQ MEM*NEXT.VADR 61
            MEM*REST (- MEM*NEXT.RADR MEM*NEXT.VADR -1)
            MEM*FIRST.REUSABLE.VADR NIL
            MEM*LAST.REUSABLE.VADR NIL))

(PROGN (SETQ DT*SORT.ALL (QUOTE (ANIMAL DAYS ANY))) (SETQ DT*SORT.NR (QUOTE 4)) (SETQ DT*SORT.PROPERTIES (QUOTE (DT*MAX.SUBSORTS DT*LEAST.SUPERSORTS DT*TRANSITIVE.CLOSURE DT*INVERSE.TRANSITIVE.CLOSURE DT*MINIMAL.SUBSORTS DT*DIRECT.SUBSORTS DT*DIRECT.SUPERSORTS DT*DISJOINT.SORTS DT*COMPLETION.SORT))) (SETQ DT*SORT.COMMON.COMPUTE.FLAG (QUOTE NIL)) (SETQ DT*VARIABLE.COUNTER (QUOTE 0)) (SETQ DT*CONSTANT.COUNTER (QUOTE 0)) (SETQ DT*CONSTANT.ALL (QUOTE (59 58 57 56 55 54 53 33))) (SETQ DT*ABBREVIATIONS (QUOTE NIL)) (SETQ DT*FUNCTION.COUNTER (QUOTE 0)) (SETQ DT*FUNCTION.ALL (QUOTE (35 24 16))) (SETQ DT*FUNCTION.ADMISSIBLE.THEORIES (QUOTE (ASSOCIATIVE))) (SETQ DT*FUNCTION.ACTUAL.THEORIES (QUOTE NIL)) (SETQ DT*FUNCTION.WITH.ARGUMENT.SYMMETRIES (QUOTE NIL)) (SETQ DT*FUNCTION.COMPONENTS (QUOTE (PNAME ATTRIBUTES MAX.RANGE.SORT MAX.DOMAIN.SORTS MIN.RANGE.SORTS SORT.LIST SORT.LIST.INVERSE SORT.TREE.CALC ARGUMENT.SYMMETRIES ARITY G.L.B.OF.RANGES))) (SETQ DT*PREDICATE.ADMISSABLE.ATTRIBUTES (QUOTE (SYMMETRIC DEFINED REFLEXIVE))) (SETQ DT*PREDICATE.COUNTER (QUOTE 0)) (SETQ DT*EQUALITY.SYMBOLS (QUOTE ("=" ":=" "=:" ":=:"))) (SETQ DT*EQUALITY.PREDICATES (QUOTE NIL)) (SETQ DT*NONEQUALITY.PREDICATES (QUOTE (36 32 9 8 7 6 5 4 3 1 0))) (SETQ DT*PREDICATE.ALL (QUOTE (36 32 9 8 7 6 5 4 3 1 0))) (SETQ DT*PREDICATE.WITH.ATTRIBUTES (QUOTE NIL)) (SETQ DT*PREDICATE.COMPONENTS (QUOTE (PNAME POSITIVE.OCCURRENCES NEGATIVE.OCCURRENCES DOMAINSORTS ATTRIBUTES REFL.CLAUSE +ROTHERSIDES -ROTHERSIDES +SOTHERSIDES -SOTHERSIDES +TOTHERSIDES -TOTHERSIDES))) (SETQ DT*TRUE.PREDICATE (QUOTE 0)) (SETQ DT*FALSE.PREDICATE (QUOTE 1)) (SETQ DT*UNI.CREATES.VARIABLES (QUOTE NIL)) (SETQ DT*SIGN.MINUS.SYMBOLS (QUOTE (- --))) (SETQ DT*SIGN.PLUS.SYMBOLS (QUOTE (+ ++))) (SETQ DT*SYMBOL.KINDS (QUOTE (CONSTANT.ALL FUNCTION.ALL PREDICATE.ALL)))) 
(PROGN) 
(PROGN (PROGN)) 
(PROGN (PROGN (SETF (GET (QUOTE ANIMAL) (QUOTE DT*SORT.NUMBER)) (QUOTE 3)) (SETF (GET (QUOTE ANIMAL) (QUOTE DT*DIRECT.SUBSORTS)) (QUOTE NIL)) (SETF (GET (QUOTE ANIMAL) (QUOTE DT*TRANSITIVE.CLOSURE)) (QUOTE (ANIMAL))) (SETF (GET (QUOTE ANIMAL) (QUOTE DT*MAX.SUBSORTS)) (QUOTE ((ANIMAL ANIMAL) (DAYS) (ANY ANIMAL)))) (SETF (GET (QUOTE ANIMAL) (QUOTE DT*MINIMAL.SUBSORTS)) (QUOTE (ANIMAL))) (SETF (GET (QUOTE ANIMAL) (QUOTE DT*DIRECT.SUPERSORTS)) (QUOTE (ANY))) (SETF (GET (QUOTE ANIMAL) (QUOTE DT*INVERSE.TRANSITIVE.CLOSURE)) (QUOTE (ANY ANIMAL)))) (PROGN (SETF (GET (QUOTE DAYS) (QUOTE DT*SORT.NUMBER)) (QUOTE 2)) (SETF (GET (QUOTE DAYS) (QUOTE DT*DIRECT.SUBSORTS)) (QUOTE NIL)) (SETF (GET (QUOTE DAYS) (QUOTE DT*TRANSITIVE.CLOSURE)) (QUOTE (DAYS))) (SETF (GET (QUOTE DAYS) (QUOTE DT*MAX.SUBSORTS)) (QUOTE ((ANIMAL) (DAYS DAYS) (ANY DAYS)))) (SETF (GET (QUOTE DAYS) (QUOTE DT*MINIMAL.SUBSORTS)) (QUOTE (DAYS))) (SETF (GET (QUOTE DAYS) (QUOTE DT*DIRECT.SUPERSORTS)) (QUOTE (ANY))) (SETF (GET (QUOTE DAYS) (QUOTE DT*INVERSE.TRANSITIVE.CLOSURE)) (QUOTE (ANY DAYS)))) (PROGN (SETF (GET (QUOTE ANY) (QUOTE DT*SORT.NUMBER)) (QUOTE 1)) (SETF (GET (QUOTE ANY) (QUOTE DT*DIRECT.SUBSORTS)) (QUOTE (ANIMAL DAYS))) (SETF (GET (QUOTE ANY) (QUOTE DT*TRANSITIVE.CLOSURE)) (QUOTE (ANY ANIMAL DAYS))) (SETF (GET (QUOTE ANY) (QUOTE DT*MAX.SUBSORTS)) (QUOTE ((ANIMAL ANIMAL) (DAYS DAYS) (ANY ANY)))) (SETF (GET (QUOTE ANY) (QUOTE DT*MINIMAL.SUBSORTS)) (QUOTE (DAYS))) (SETF (GET (QUOTE ANY) (QUOTE DT*DIRECT.SUPERSORTS)) (QUOTE NIL)) (SETF (GET (QUOTE ANY) (QUOTE DT*INVERSE.TRANSITIVE.CLOSURE)) (QUOTE (ANY))))) ))