;;; -*- Package: MKRP; Base: 10.; Mode: LISP; Syntax: Common-lisp -*- 

(SORT MENGE,VERKN,ELEMENT,NAT,ABB:ANY)
(TYPE W(MENGE) :MENGE)
(TYPE RESTRICTION(ABB MENGE) :ABB)
(TYPE APPLYV(VERKN ELEMENT ELEMENT) :ELEMENT)
(TYPE APPLYA(ABB ELEMENT) :ELEMENT)
(TYPE CONC:VERKN)
(TYPE HG(MENGE VERKN))
(TYPE ABBILDUNG(ABB MENGE MENGE))
(TYPE HOMOMORPH(ABB MENGE MENGE))
(TYPE ME(MENGE MENGE))
(TYPE REKERW(ABB MENGE) :MENGE)
(* REKURSIVE ERWEITERUNG EINER ABBILDUNG *)
(ALL X,H:MENGE  ALL PHINULL:ABB  ALL MAL:VERKN  
     HG(H MAL) AND ABBILDUNG(PHINULL X H)
     IMPL (EX PHI:ABB ABBILDUNG(PHI W(X) H) AND GLEICH(REKERW(PHINULL W(X)) PHI)))
(* DEFINITION DER REKURSIVEN ERWEITERUNG REKERW *)
(ALL X,H:MENGE  ALL PHINULL,PHI:ABB  ALL MAL:VERKN  
     HG(H MAL) AND ABBILDUNG(PHINULL X H) AND ABBILDUNG(PHI W(X) H) AND GLEICH(REKERW(PHINULL W(X)) PHI)
     IMPL((ALL U:ELEMENT EL(U X) IMPL APPLYA(PHI U) = APPLYA(PHINULL U))
	  AND( ALL U,V:ELEMENT EL(U X) AND EL(V W(X))
	      IMPL APPLYA(PHI APPLYV(CONC U V)) = applyv(mal applya(phi v) applya(phinull u)))))
(* LEMMA 2.5.1.2.1 *)
(ALL X,H:MENGE  ALL PHINULL,PHI:ABB  ALL MAL:VERKN  
     HG(H MAL) AND ABBILDUNG(PHINULL X H) AND ABBILDUNG(PHI W(X) H) AND GLEICH(REKERW(PHINULL W(X)) PHI)
     IMPL HOMOMORPH(PHI W(X) H))
(* DEFINITION DER EINSCHRAENKUNG RESTRICTION *)
(ALL A,B,C:MENGE
     ALL PHINULL,PHI:ABB
     ABBILDUNG(PHI A B)
     AND ABBILDUNG(PHINULL C B)
     AND ME(C A)
     AND (ALL U:ELEMENT EL(U C) IMPL APPLYA(PHI U) = APPLYA(PHINULL U))
     IMPL GLEICH(RESTRICTION(PHI C) PHINULL))
(* EIGENSCHAFT VON W(X) *)
(ALL X:MENGE ME(X W(X)))

(ALL X,H:MENGE  ALL MAL:VERKN  ALL PHINULL:ABB  
     HG(H MAL) AND ABBILDUNG(PHINULL X H)
     IMPL (EX PHI:ABB HOMOMORPH(PHI W(X) H) AND GLEICH(RESTRICTION(PHI X) PHINULL)))