;;; -*- Mode: LISP; Package: MKRP; Syntax: Common-lisp -*-
(* THERE ARE TWO PEOPLE A ,B %.)
(* A IS ASKED:IS
EITHER OF YOU A KNIGHT ?)
(* HE GIVES AN ANSWER AND WE KNOW WHAT THEY ARE %.)

(*)
(* WHAT ARE THEY ?)
(*)
(* NO (X) MEANS X ANSWERS WITH
NO %.)
(* YES (X) MEANS X ANSWERS WITH YES %.)
(* EITHER2 (X Y) MEANS X OR
Y IS A KNIGHT %.)
(* EITHER3 (X Y Z) MEANS X SAYS: Y OR Z IS A KNIGHT %.)
(*
NEITHER3 (X Y Z) MEANS X SAYS: Y AND Z ARE KNAVES %.)
(*)
(ALL X KNAVE (X)
EQV NOT KNIGHT (X))

(ALL X NO (X) EQV NOT YES (X))
(ALL X NO (X) IMPL NEITHER3 (X A B))
(ALL X YES (X) IMPL EITHER3 (X A B))
(ALL X EITHER3 (X A B) AND KNIGHT (X) IMPL EITHER2 (A B))
(ALL X EITHER3 (X A B) AND KNAVE (X) IMPL NOT EITHER2
(A B))
(ALL
X NEITHER3 (X A B) AND KNIGHT (X) IMPL NOT EITHER2 (A B))
(ALL X NEITHER3 (X A B) AND KNAVE (X) IMPL EITHER2 (A B))
(ALL X,Y EITHER2 (X Y) EQV KNIGHT
(X) OR KNIGHT (Y))


(NO (A) IMPL KNAVE (A) AND KNIGHT (B))


