;;; -*- Package: MKRP; Mode: LISP; Syntax: Common-lisp -*-
 
 
(SORT ELEMENT,MENGE,VERKN,ABB,NAT:ANY)
(TYPE W(MENGE) :MENGE)
(TYPE LENGTH(ELEMENT) : NAT)
(TYPE URBILD(ELEMENT ABB) :ELEMENT)
(TYPE APPLYA(ABB ELEMENT) : ELEMENT)
(TYPE RESTRICTION(ABB MENGE) :ABB)
(TYPE PHINULL,PHI:ABB)
(TYPE one:NAT)
(ALL X:ELEMENT ALL B : MENGE EL(X W(B)) AND GLEICH(LENGTH(X) one) IMPL EL(X B))
(ALL A,B:MENGE ALL F:ABB ALL X:ELEMENT BIJEKTIV(F A B) AND EL(X B) IMPL EINDEUTIG(URBILD(X F)))
(ALL X:ELEMENT  ALL CHI:ABB  ALL A,B:MENGE  
     EL(X B) AND BIJEKTIV(RESTRICTION(CHI A) A B) AND EINDEUTIG(URBILD(X RESTRICTION(CHI A)))
     IMPL EINDEUTIG(URBILD(X CHI)))
 
(ALL X:ELEMENT  ALL A,B:MENGE  
     EL(X W(B))
     AND GLEICH(LENGTH(X) one)
     AND BIJEKTIV(PHINULL A B)
     AND HOMOMORPH(PHI W(A) W(B))
     AND RESTRICTION(PHI A) = PHINULL
     IMPL EINDEUTIG(URBILD(X PHI)))