;;; -*- Mode: LISP; Package: MKRP; Syntax: Common-lisp -*-
(* PROBLEM 58)
(*)
(* ONE DAY ALICE
MET THE BROTHERS %.)
(* THEY MADE THE FOLLOWING STATEMENTS:)
(*)
(* FIRSTONE/ TODAY IS NOT SUNDAY.)
(* SECONDONE / TODAY IS MONDAY.)
(* FIRSTONE
/ TWEEDLEDEE WILL LIE TOMORROW.)
(* SECONDONE / THE LION LIED YESTERDAY.)
(*)
(* (1) WHAT DAY IS IT.)
(* (2) WHICH OF THE TWO IS TWEEDLEDUM.)
(* (3) WHETHER TWEEDLEDUM IS LIKE THE LION OR THE UNICORN %.)
(*)
(*)
(* FORMALIZING THE PROBLEM IN FIRST ORDER LOGIC)
(*)
(TYPE 
FIRSTONE,SECONDONE :PERSON)
(TYPE LION,UNICORN:ANIMAL)
(* LIKE (X Y) MEANS :
THE LYING-BEHAVIOR OF X IS LIKE THE ANIMAL Y.)
(ALL X:PERSON LIKE (X LION) OR LIKE (X UNICORN))
(ALL X:PERSON NOT (LIKE (X LION) AND
LIKE (X UNICORN)))
(*)
(ALL X:DAYS MO (X) EQV (NOT TU (X) AND NOT WE (X) AND NOT TH (X) AND NOT FR (X) AND NOT SA (X) AND NOT
SU (X)))
(ALL X:DAYS TU (X) EQV (NOT MO (X) AND NOT WE (X) AND NOT TH (X) AND NOT FR (X) AND NOT SA (X) AND NOT SU (X)))
(ALL X:DAYS WE (X) EQV (NOT MO (X) AND NOT TU (X) AND NOT TH (X) AND NOT FR (X) AND NOT SA (X) AND NOT SU (X)))
(ALL X:DAYS TH (X) EQV (NOT MO (X) AND NOT TU (X) AND NOT WE (X) AND NOT FR (X) AND NOT SA (X) AND NOT SU (X)))
(ALL X:DAYS FR (X) EQV (NOT MO (X) AND NOT TU (X) AND NOT WE (X) AND NOT TH (X) AND NOT SA (X) AND NOT SU (X)))
(ALL X:DAYS SA (X) EQV (NOT MO (X) AND NOT TU (X) AND NOT WE (X) AND NOT TH (X) AND NOT FR (X) AND NOT SU (X)))
(ALL X:DAYS SU (X) EQV (NOT MO (X) AND NOT TU (X) AND NOT WE (X) AND NOT TH (X) AND NOT FR (X) AND NOT SA (X)))
(*)
(TYPE TOMORROW (DAYS) :DAYS)
(ALL X:DAYS MO (TOMORROW (X)) EQV SU (X))
(ALL X:DAYS TU (TOMORROW (X)) EQV MO
(X))
(ALL X:DAYS WE (TOMORROW (X)) EQV
TU (X))
(ALL X:DAYS TH (TOMORROW (X))
EQV WE (X))
(ALL X:DAYS FR (TOMORROW
(X)) EQV TH (X))
(ALL X:DAYS SA (TOMORROW
(X)) EQV FR (X))
(ALL X:DAYS SU (TOMORROW
(X)) EQV SA (X))
(*)
(TYPE YESTERDAY (DAYS) :DAYS)
(ALL X:DAYS MO (YESTERDAY (X)) EQV TU (X))
(ALL X:DAYS TU (YESTERDAY (X)) EQV WE (X))
(ALL X:DAYS WE (YESTERDAY (X)) EQV TH (X))
(ALL X:DAYS TH (YESTERDAY (X)) EQV FR (X))
(ALL X:DAYS FR (YESTERDAY (X)) EQV SA (X))
(ALL X:DAYS SA (YESTERDAY (X)) EQV SU
(X))
(ALL X:DAYS SU (YESTERDAY (X))
EQV MO (X))
(*)
(ALL
X:DAYS MEMBER (X LYING-DAYS (LION)) EQV (MO (X) OR TU (X) OR WE (X)))
(ALL X:DAYS MEMBER (X LYING-DAYS
(UNICORN)) EQV (TH (X) OR FR (X) OR SA (X)))
(*)
(ALL X:PERSON ALL Y:ANIMAL LIKE
(X Y) IMPL (ALL Z:DAYS (MEMBER (Z LYING-DAYS (Y)) EQV MEMBER (Z LYING-DAYS (X)))))
(ALL
X:PERSON ALL Y:ANIMAL ((EX Z:DAYS (MEMBER (Z LYING-DAYS (X)) AND MEMBER (Z LYING-DAYS (Y)))) IMPL LIKE (X Y)))
(*)
(* TODAY-IS-NOSU (X Y) MEANS X COULD STATE AT DAY Y:TODAY IS NOT
SUNDAY.)
(ALL X: PERSON ALL Y:DAYS TODAY-IS-NOSU (X Y) EQV (MEMBER (Y LYING-DAYS (X)) AND SU
(Y) OR NOT MEMBER (Y LYING-DAYS (X)) AND NOT SU (Y)))
(* TODAY-IS-MO (X Y) MEANS: X COULD STATE AT DAY Y: TODAY IS MONDAY.)
(ALL X:
PERSON ALL Y:DAYS TODAY-IS-MO (X Y) EQV (MEMBER (Y LYING-DAYS (X)) AND NOT MO (X) OR NOT MEMBER (Y LYING-DAYS (X))
AND MO (X)))
(* LION-LIED (X Y Z) MEANS:
X COULD SAY AT DAY Y: THE LION LIES AT THE DAY Z.)
(ALL X:PERSON ALL Y,Z: DAYS LION-LIED (X Y
Z) EQV (MEMBER (Y LYING-DAYS (X)) AND NOT MEMBER (Z LYING-DAYS (LION)) OR NOT MEMBER (Y LYING-DAYS (X)) AND MEMBER
(Z LYING-DAYS (LION))))
(* TOM-LD-DEE (X Y Z) MEANS: X COULD SAY AT DAY Y: TWEEDLEDEE LIES TOMORROW.)
(ALL X,Z:PERSON ALL Y:DAYS NOT MEMBER (Y LYING-DAYS (X)) AND TWEEDLEDEE (Z) AND MEMBER (TOMORROW (Y) LYING-DAYS
(Z)) IMPL TOM-LD-DEE (X Y Z))
(ALL X,Z:PERSON ALL
Y:DAYS NOT MEMBER (Y LYING-DAYS (X)) AND TWEEDLEDEE (X) AND MEMBER (TOMORROW (Y) LYING-DAYS (X)) IMPL TOM-LD-DEE
(X Y Z))
(ALL X,Z:PERSON ALL Y:DAYS MEMBER (Y
LYING-DAYS (X)) AND TWEEDLEDEE (X) AND MEMBER (TOMORROW (Y) LYING-DAYS (X)) IMPL NOT TOM-LD-DEE (X Y Z))
(ALL X,Z:PERSON ALL Y:DAYS MEMBER (Y LYING-DAYS (X)) AND TWEEDLEDEE
(Z) AND MEMBER (TOMORROW (Y) LYING-DAYS (Z)) IMPL NOT TOM-LD-DEE (X Y Z))
(ALL X,Z:PERSON ALL Y:DAYS MEMBER (Y LYING-DAYS (X)) AND TWEEDLEDEE (Z) AND NOT MEMBER
(TOMORROW (Y) LYING-DAYS (Z)) IMPL TOM-LD-DEE (X Y Z))
(ALL X,Z:PERSON ALL Y:DAYS MEMBER (Y LYING-DAYS (X)) AND TWEEDLEDEE (X) AND NOT MEMBER (TOMORROW (Y) LYING-DAYS
(X)) IMPL TOM-LD-DEE (X Y Z))
(ALL X,Z:PERSON ALL
Y:DAYS NOT MEMBER (Y LYING-DAYS (X)) AND TWEEDLEDEE (X) AND NOT MEMBER (TOMORROW (Y) LYING-DAYS (X)) IMPL NOT TOM-LD-DEE
(X Y Z))
(ALL X,Z:PERSON ALL Y:DAYS
NOT MEMBER (Y LYING-DAYS (X)) AND TWEEDLEDEE (Z) AND NOT MEMBER (TOMORROW (Y) LYING-DAYS (Z)) IMPL NOT TOM-LD-DEE
(X Y Z))
(TYPE 
MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRYDAY,SATURDAY,SUNDAY: DAYS)
(MO (MONDAY))
(TU (TUESDAY))
(WE (WEDNESDAY))
(TH (THURSDAY))
(FR (FRYDAY))
(SA (SATURDAY))
(SU (SUNDAY))
(ALL X:PERSON TWEEDLEDUM (X)
EQV NOT TWEEDLEDEE (X))
(TWEEDLEDEE
(FIRSTONE) AND TWEEDLEDUM (SECONDONE) OR TWEEDLEDUM (FIRSTONE) AND TWEEDLEDEE (SECONDONE))

(EX X:DAYS TODAY-IS-NOSU (FIRSTONE X) AND TODAY-IS-MO (SECONDONE X)
AND TOM-LD-DEE (FIRSTONE X SECONDONE) AND LION-LIED (SECONDONE X YESTERDAY (X)) AND TWEEDLEDUM (FIRSTONE) AND LIKE
(FIRSTONE LION))