;;; -*- Mode: LISP; Package: MKRP; Syntax: Common-lisp -*-
(* PROBLEM 94)
(* HERE IS AN ELEGANTLY SIMPLE ONE INVOLVING JUST TWO INHABITANTS,A AND B.)
(* JUST ONE OF THEM IS A WEREWOLF.THEY MAKE THE FOLLOWING STATEMENTS:)
(* A:THE WEREWOLF IS A
KNIGHT.)
(* B:THE WEREWOLF IS A KNAVE.)
(* WHICH ONE WOULD YOU SELECT FOR YOUR TRAVELING COMPANION?)
(*)
(* THE FUNCTION STATE AND THE PREDICATES KNIGHT,KNAVE,WEREWOLF AND
TRUTH)
(* MEAN THE SAME AS DESCRIBED IN THE PROBLEMS 88 - 93)
(* WE DEFINE THE FOLLOWING NEW PREDICATES:)
(* STATE.W.I.K (X) ...THE STATEMENT X TELLS THAT IF A PERSON IS A WEREWOLF)
(* THEN HE IS A KNIGHT.)
(* STATE.W.I.KNAVE (X) ...THE STATEMENT X TELLS THAT IF A PERSON IS A WEREWOLF)
(* THEN HE IS A KNAVE.)
(*)
(* DECLARATIONS)
(*)
(TYPE A,B : PERSON)
(TYPE STATE (PERSON) :STATEMENT)
(TYPE WEREWOLF (PERSON))
(TYPE KNIGHT (PERSON))
(TYPE KNAVE (PERSON))
(TYPE TRUTH
(STATEMENT))
(TYPE STATE.W.I.K (STATEMENT))
(TYPE STATE.W.I.KNAVE (STATEMENT))
(*)
(* ONLY ONE OF THE PERSONS A AND B IS A WEREWOLF)
(*)
(WEREWOLF
(A) OR WEREWOLF (B))
(NOT (WEREWOLF (A) AND WEREWOLF (B)))
(*)
(* A KNIGHT ALWAYS SAYS THE TRUTH AND A KNAVE ALWAYS
LIES)
(*)
(ALL X : PERSON TRUTH (STATE (X)) EQV KNIGHT (X))
(ALL X : PERSON NOT (TRUTH (STATE (X))) EQV KNAVE (X))
(*)
(* IMPLICATIONS ABOUT STATEMENTS:)
(*)
(ALL X : STATEMENT STATE.W.I.K (X) AND TRUTH (X) IMPL ((WEREWOLF (A) IMPL KNIGHT (A)) AND (WEREWOLF
(B) IMPL KNIGHT (B))))
(ALL X : STATEMENT STATE.W.I.K (X) AND NOT (TRUTH (X)) IMPL NOT ((WEREWOLF
(A) IMPL KNIGHT (A)) AND (WEREWOLF (B) IMPL KNIGHT (B))))
(ALL X : STATEMENT
STATE.W.I.KNAVE (X) AND TRUTH (X) IMPL ((WEREWOLF (A) IMPL KNAVE (A)) AND (WEREWOLF (B) IMPL KNAVE (B))))
(ALL X : STATEMENT STATE.W.I.KNAVE (X) AND NOT (TRUTH (X)) IMPL NOT ((WEREWOLF (A) IMPL KNAVE (A)) AND (WEREWOLF (B) IMPL KNAVE (B))))
(*)
(* ACTUAL STATEMENTS:)
(*)
(STATE.W.I.K (STATE (A)))
(STATE.W.I.KNAVE (STATE
(B)))

(NOT (WEREWOLF (B)))