;;; -*- Mode: Lisp; Syntax: Common-lisp; Package: MKRP -*-

(ALL X KNAZI (X) IMPL (BREISE (X) IMPL PLANDIEREN (X)))
(ALL X KNAZI (X) AND PLITZE (X) IMPL DEFFISKNASE (X))
(ALL X KNAZI (X) AND JERPEN (X) IMPL FRALIEREN (X))
(ALL X KNAZI (X) AND DEFFISKNASE (X) IMPL BEDRAUST (X))
(ALL X KNAZI (X) AND QUISTELN (X) IMPL JERPEN (X))
(ALL X KNAZI (X) AND NOT BREISE (X) IMPL NOT BEDRAUST (X))
(ALL X PNUNK (X) IMPL KNAZI (X) AND QUISTELN (X))
(NOT (EX X KNAZI (X) AND PLANDIEREN (X) AND FRALIEREN (X)))

(NOT (EX X PNUNK (X) AND PLITZE (X)))