;;; -*- Package: MKRP; Mode: LISP; Syntax: Common-lisp -*-
(SORT MENGE,ELEMENT,VERKN:ANY)
(TYPE W(MENGE) :MENGE)
(TYPE CONC:VERKN)
(TYPE APPLY(VERKN ELEMENT ELEMENT) :ELEMENT)
(TYPE APPLYABB(MENGE ELEMENT) :ELEMENT)
(TYPE INVERS(MENGE) :MENGE)
(ALL A,B,ABB:MENGE  ALL PHI:VERKN  ALL X,Y:ELEMENT  
     HOMOMORPH(A B ABB) AND EL(X A) AND EL(Y A) AND HG(A PHI) AND HG(B PHI)
     IMPL APPLYABB(ABB APPLY(PHI X Y)) = APPLY(PHI APPLYABB(ABB X) APPLYABB(ABB Y)))
(ALL A,B,F:MENGE         ISOMORPH(A B F)
     IMPL     HOMOMORPH(A B F)
     AND HOMOMORPH(B A INVERS(F))
     AND BIJEKTIV(A B F)
     AND BIJEKTIV(B A INVERS(F)))
(ALL A,B,ABB:MENGE  ALL X:ELEMENT  
     BIJEKTIV(A B ABB) AND EL(X A) IMPL APPLYABB(INVERS(ABB) APPLYABB(ABB X)) = X AND EL(APPLYABB(ABB X) B))
(ALL A,B,ABB:MENGE  ALL X:ELEMENT  
     BIJEKTIV(A B ABB) AND EL(X B)
     IMPL APPLYABB(ABB APPLYABB(INVERS(ABB) X)) = X AND EL(APPLYABB(INVERS(ABB) X) A))
(ALL ALPHABET:MENGE HG(W(ALPHABET) CONC))
(ALL X,S,T:ELEMENT ALL Y:MENGE NOT(BUCHSTABE(X Y)) OR NOT(X = APPLY(CONC S T)))
(ALL X:ELEMENT ALL Y:MENGE BUCHSTABE(X Y) IMPL EL(X W(Y)))
(ALL Y:MENGE  ALL X:ELEMENT 
     EL(X W(Y)) IMPL(BUCHSTABE(X Y) OR(EX S,T:ELEMENT X = APPLY(CONC S T) AND EL(S W(Y)) AND EL(T W(Y)))))
 
(ALL A,B,F:MENGE ALL X:ELEMENT BUCHSTABE(X A) AND ISOMORPH(W(A) W(B) F) IMPL BUCHSTABE(APPLYABB(F X) B))
 
 
 
 
