;;; -*- Mode: LISP; Package: MKRP; Syntax: Common-lisp -*-
(* SMULLYAN, CHAPTER 8, PROBLEM 125)
(* ANOTHER TIME I WAS VISITING A DIFFERENT ISLAND OF
KNIGHTS,)
(* KNAVES, AND NORMALS.)
(ALL X KNIGHT (X) IMPL NOT KNAVE (X))
(ALL X KNAVE (X) IMPL NOT NORMAL (X))
(ALL X NORMAL (X) IMPL NOT KNIGHT (X))
(ALL X,Y KNIGHT (X) AND ANSWER (X Y) IMPL T (Y))
(ALL X,Y KNAVE (X) AND ANSWER (X Y) IMPL
NOT T (Y))
(ALL X KNIGHT (X) OR KNAVE (X) OR NORMAL (X))
(* IT WAS RUMORED THAT THERE WAS GOLD ON THE ISLAND, AND I)
(* WANTED TO FIND
OUT WHETHER THERE WAS. THE KING OF THE ISLAND,)
(* WHO WAS A KNIGHT, GRACIOUSLY INTRODUCED ME
TO THREE OF THE)
(* NATIVES, A, B, C, AND TOLD ME THAT AT MOST ONE OF THEM WAS)
(* NORMAL.)
(((KNIGHT (A) OR KNAVE (A)) AND (KNIGHT (B) OR KNAVE (B))) OR ((KNIGHT (A) OR KNAVE
(A)) AND (KNIGHT (C) OR KNAVE (C))) OR ((KNIGHT (B) OR KNAVE (B)) AND (KNIGHT (C) OR KNAVE (C))))
(* I WAS ALLOWED TO ASK TWO YES-NO QUESTIONS TO WHICHEVER ONES)
(* I WISHED.)
(T (YES1) EQV QUESTION1)
(T (NO1) EQV NOT
QUESTION1)
(T (YES2-A) EQV QUESTION2-A)
(T (NO2-A) EQV NOT QUESTION2-A)
(T (YES2-B) EQV QUESTION2-B)
(T (NO2-B)
EQV NOT QUESTION2-B)

(* IS THERE A WAY OF FINDING OUT IN TWO QUESTIONS WHETHER THERE)
(* IS GOLD ON THE ISLAND?)
((QUESTION1 EQV (KNIGHT (A) EQV NORMAL (B))) IMPL ((QUESTION2-A EQV (KNIGHT (C) EQV 
THERE-IS-GOLD-ON-THE-ISLAND)) AND (QUESTION2-B EQV (KNIGHT (B) EQV THERE-IS-GOLD-ON-THE-ISLAND)) IMPL (ANSWER (A
YES1) IMPL ((ANSWER (C YES2-A) IMPL THERE-IS-GOLD-ON-THE-ISLAND) AND (ANSWER (C NO2-A) IMPL NOT 
THERE-IS-GOLD-ON-THE-ISLAND))) AND (ANSWER (A NO1) IMPL ((ANSWER (B YES2-B) IMPL THERE-IS-GOLD-ON-THE-ISLAND) AND
(ANSWER (B NO2-B) IMPL NOT THERE-IS-GOLD-ON-THE-ISLAND)))))