;;; -*- Package: MKRP; Base: 10; Mode: LISP; Syntax: Common-lisp -*-
(PREP-PROBLEM.SPECIFICATION (QUOTE ((E (MON MO) AND E (TUE TU) AND E (WED WE) AND E (THU TH) AND E (FRI FR) AND E (SAT SA) AND E (SUN SU)) (ALL X : MO E (X LL)) (ALL X : TU E (X LL)) (ALL X : WE E (X LL)) (ALL X : TH NOT E (X LL)) (ALL X : FR NOT E (X LL)) (ALL X : SA NOT E (X LL)) (ALL X : SU NOT E (X LL)) (ALL X : MO NOT E (X LU)) (ALL X : TU NOT E (X LU)) (ALL X : WE NOT E (X LU)) (ALL X : TH E (X LU)) (ALL X : FR E (X LU)) (ALL X : SA E (X LU)) (ALL X : SU NOT E (X LU)) (ALL X : MO E (X D)) (ALL X : TU E (X D)) (ALL X : WE E (X D)) (ALL X : TH E (X D)) (ALL X : FR E (X D)) (ALL X : SA E (X D)) (ALL X : SU E (X D)) (ALL X : LL E (X D)) (ALL X : LU E (X D)) (ALL X : MO E (YESTER (X) SU)) (ALL X : TU E (YESTER (X) MO)) (ALL X : WE E (YESTER (X) TU)) (ALL X : TH E (YESTER (X) WE)) (ALL X : FR E (YESTER (X) TH)) (ALL X : SA E (YESTER (X) FR)) (ALL X : SU E (YESTER (X) SA)) (ALL X,Y : D (E (X LL) OR NOT LIES (LION X Y) OR E (Y LL))) (ALL X : D (ALL Y : LL (E (X LL) OR LIES (LION X Y)))) (ALL X,Y : LL (NOT LIES (LION X Y))) (ALL Y : D (ALL X : LL (LIES (LION X Y) OR E (Y LL)))) (ALL X,Y : D (E (X LU) OR NOT LIES (UNICORN X Y) OR E (Y LU))) (ALL X : D (ALL Y : LU (E (X LU) OR LIES (UNICORN X Y)))) (ALL X,Y : LU (NOT LIES (UNICORN X Y))) (ALL Y : D (ALL X : LU (LIES (UNICORN X Y) OR E (Y LU)))))) (QUOTE ((AND (+ 4 (5 6) NIL) (AND (+ 4 (7 8) NIL) (AND (+ 4 (9 10) NIL) (AND (+ 4 (11 12) NIL) (AND (+ 4 (13 14) NIL) (AND (+ 4 (15 16) NIL) (+ 4 (17 18) NIL))))))) (ALL 19 (+ 4 (19 20) NIL)) (ALL 21 (+ 4 (21 20) NIL)) (ALL 22 (+ 4 (22 20) NIL)) (ALL 23 (NOT (+ 4 (23 20) NIL))) (ALL 24 (NOT (+ 4 (24 20) NIL))) (ALL 25 (NOT (+ 4 (25 20) NIL))) (ALL 26 (NOT (+ 4 (26 20) NIL))) (ALL 27 (NOT (+ 4 (27 28) NIL))) (ALL 29 (NOT (+ 4 (29 28) NIL))) (ALL 30 (NOT (+ 4 (30 28) NIL))) (ALL 31 (+ 4 (31 28) NIL)) (ALL 32 (+ 4 (32 28) NIL)) (ALL 33 (+ 4 (33 28) NIL)) (ALL 34 (NOT (+ 4 (34 28) NIL))) (ALL 35 (+ 4 (35 36) NIL)) (ALL 37 (+ 4 (37 36) NIL)) (ALL 38 (+ 4 (38 36) NIL)) (ALL 39 (+ 4 (39 36) NIL)) (ALL 40 (+ 4 (40 36) NIL)) (ALL 41 (+ 4 (41 36) NIL)) (ALL 42 (+ 4 (42 36) NIL)) (ALL 43 (+ 4 (43 36) NIL)) (ALL 44 (+ 4 (44 36) NIL)) (ALL 45 (+ 4 ((46 45) 18) NIL)) (ALL 47 (+ 4 ((46 47) 6) NIL)) (ALL 48 (+ 4 ((46 48) 8) NIL)) (ALL 49 (+ 4 ((46 49) 10) NIL)) (ALL 50 (+ 4 ((46 50) 12) NIL)) (ALL 51 (+ 4 ((46 51) 14) NIL)) (ALL 52 (+ 4 ((46 52) 16) NIL)) (ALL 54 (ALL 53 (OR (+ 4 (53 20) NIL) (OR (NOT (+ 56 (55 53 54) NIL)) (+ 4 (54 20) NIL))))) (ALL 57 (ALL 58 (OR (+ 4 (57 20) NIL) (+ 56 (55 57 58) NIL)))) (ALL 60 (ALL 59 (NOT (+ 56 (55 59 60) NIL)))) (ALL 61 (ALL 62 (OR (+ 56 (55 62 61) NIL) (+ 4 (61 20) NIL)))) (ALL 64 (ALL 63 (OR (+ 4 (63 28) NIL) (OR (NOT (+ 56 (65 63 64) NIL)) (+ 4 (64 28) NIL))))) (ALL 66 (ALL 67 (OR (+ 4 (66 28) NIL) (+ 56 (65 66 67) NIL)))) (ALL 69 (ALL 68 (NOT (+ 56 (65 68 69) NIL)))) (ALL 70 (ALL 71 (OR (+ 56 (65 71 70) NIL) (+ 4 (70 28) NIL)))))) (QUOTE ((EX X : D (LIES (LION X YESTER (YESTER (X))) AND LIES (UNICORN X YESTER (YESTER (X))))))) (QUOTE ((EX 72 (AND (+ 56 (55 72 (46 (46 72))) NIL) (+ 56 (65 72 (46 (46 72))) NIL))))) (QUOTE ("Edit:     Axioms and Theorems edited: 19-JUN,1992 16:05 ")) (PROGN(PROGN (DT-RESET))

(PROG ((ADDRLIST
        '(319580 319585 319590 319595 319600 319605 319610 319615 319620 319625 319630 319635
          319640 319645 319650 319655 319670 319675 319680 319685 319690 319695 319700 319705
          319710 319715 319729 319734 319739 319744 319749 319754 319759 319764 319769 319774
          319779 319784 319789 319794 319799 319804 319809 319814 319819 319824 319829 319834
          319839 319844 319849 319854 319859 319864 319869 319874 319879 319884 319889 319894
          319899 319904 319909 319914 319919 319924 319929 319934 319949 319954 319969 319984
          319999))
       (DATALIST
        '(15 "TRUE" NIL NIL NIL (DEFINED) NIL ((- 0 (POSITIVE))) ((+ 0 (NEGATIVE)))
          ((+ 0 (NIL))) ((- 0 (NIL))) NIL NIL (DT*ST-KIND NIL) PREDICATE 15 "FALSE" NIL NIL
          NIL (DEFINED) NIL ((- 1 (POSITIVE))) ((+ 1 (NEGATIVE))) ((+ 1 (NIL))) ((- 1 (NIL)))
          NIL NIL (DT*ST-KIND NIL) PREDICATE 15 "=" NIL NIL (ANY ANY)
          (DEFINED SYMMETRIC REFLEXIVE SYMMETRIC REFLEXIVE) NIL ((- 2 (POSITIVE . SYMMETRIC)))
          ((+ 2 (NEGATIVE . SYMMETRIC))) ((+ 2 (NIL . SYMMETRIC))) ((- 2 (NIL . SYMMETRIC)))
          NIL NIL (DT*ST-KIND NIL) PREDICATE 5 ANY "OMEGA" (DT*ST-KIND NIL) CONSTANT 15 "E"
          NIL NIL (ANY ANY) (DEFINED) NIL ((- 4 (POSITIVE))) ((+ 4 (NEGATIVE))) ((+ 4 (NIL)))
          ((- 4 (NIL))) NIL NIL (DT*ST-KIND NIL) PREDICATE 5 ANY "MON" (DT*ST-KIND NIL)
          CONSTANT 5 ANY "MO" (DT*ST-KIND NIL) CONSTANT 5 ANY "TUE" (DT*ST-KIND NIL) CONSTANT
          5 ANY "TU" (DT*ST-KIND NIL) CONSTANT 5 ANY "WED" (DT*ST-KIND NIL) CONSTANT 5 ANY
          "WE" (DT*ST-KIND NIL) CONSTANT 5 ANY "THU" (DT*ST-KIND NIL) CONSTANT 5 ANY "TH"
          (DT*ST-KIND NIL) CONSTANT 5 ANY "FRI" (DT*ST-KIND NIL) CONSTANT 5 ANY "FR"
          (DT*ST-KIND NIL) CONSTANT 5 ANY "SAT" (DT*ST-KIND NIL) CONSTANT 5 ANY "SA"
          (DT*ST-KIND NIL) CONSTANT 5 ANY "SUN" (DT*ST-KIND NIL) CONSTANT 5 ANY "SU"
          (DT*ST-KIND NIL) CONSTANT 5 6 NIL (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 ANY
          "LL" (DT*ST-KIND NIL) CONSTANT 5 8 NIL (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5
          10 NIL (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 12 NIL
          (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 14 NIL (ST*DATA NIL DT*ST-KIND SYS-VAR)
          VARIABLE 5 16 NIL (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 18 NIL
          (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 6 NIL (ST*DATA NIL DT*ST-KIND SYS-VAR)
          VARIABLE 5 ANY "LU" (DT*ST-KIND NIL) CONSTANT 5 8 NIL
          (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 10 NIL (ST*DATA NIL DT*ST-KIND SYS-VAR)
          VARIABLE 5 12 NIL (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 14 NIL
          (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 16 NIL (ST*DATA NIL DT*ST-KIND SYS-VAR)
          VARIABLE 5 18 NIL (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 6 NIL
          (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 ANY "D" (DT*ST-KIND NIL) CONSTANT 5 8
          NIL (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 10 NIL
          (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 12 NIL (ST*DATA NIL DT*ST-KIND SYS-VAR)
          VARIABLE 5 14 NIL (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 16 NIL
          (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 18 NIL (ST*DATA NIL DT*ST-KIND SYS-VAR)
          VARIABLE 5 20 NIL (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 28 NIL
          (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 6 NIL (ST*DATA NIL DT*ST-KIND SYS-VAR)
          VARIABLE 14 "YESTER" NIL ANY (ANY) NIL NIL NIL NIL NIL 1 ANY (DT*ST-KIND NIL)
          FUNCTION 5 8 NIL (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 10 NIL
          (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 12 NIL (ST*DATA NIL DT*ST-KIND SYS-VAR)
          VARIABLE 5 14 NIL (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 16 NIL
          (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 18 NIL (ST*DATA NIL DT*ST-KIND SYS-VAR)
          VARIABLE 5 36 NIL (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 36 NIL
          (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 ANY "LION" (DT*ST-KIND NIL) CONSTANT 15
          "LIES" NIL NIL (ANY ANY ANY) NIL NIL ((- 56 (POSITIVE))) ((+ 56 (NEGATIVE)))
          ((+ 56 (NIL))) ((- 56 (NIL))) NIL NIL (DT*ST-KIND NIL) PREDICATE 5 36 NIL
          (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 20 NIL (ST*DATA NIL DT*ST-KIND SYS-VAR)
          VARIABLE 5 20 NIL (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 20 NIL
          (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 36 NIL (ST*DATA NIL DT*ST-KIND SYS-VAR)
          VARIABLE 5 20 NIL (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 36 NIL
          (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 36 NIL (ST*DATA NIL DT*ST-KIND SYS-VAR)
          VARIABLE 5 ANY "UNICORN" (DT*ST-KIND NIL) CONSTANT 5 36 NIL
          (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 28 NIL (ST*DATA NIL DT*ST-KIND SYS-VAR)
          VARIABLE 5 28 NIL (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 28 NIL
          (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 36 NIL (ST*DATA NIL DT*ST-KIND SYS-VAR)
          VARIABLE 5 28 NIL (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE 5 36 NIL
          (ST*DATA NIL DT*ST-KIND SYS-VAR) VARIABLE))
       (INCREMENT (- MEM*SIZE 320000))
       COUNTER1)
      (MEM-RESET)
      (COND ((> MEM*SIZE 320000)
             (SETQ COUNTER1 73)
             (MAPC #'(LAMBDA (RADDR)
                       (SETF (AREF MEM*MEMORY (DECF COUNTER1))
                              (COND ((EQL RADDR 'ATP.MEMORY.NIL) RADDR)
                                    ((EQL 'END RADDR) RADDR)
                                    ((OR (EQL RADDR 0)
                                         (MINUSP RADDR))
                                     RADDR)
                                    (T (+ RADDR INCREMENT)))))
                   ADDRLIST)
             (SETQ COUNTER1 MEM*SIZE)
             (MAPC #'(LAMBDA (DATA) (SETF (AREF MEM*MEMORY (DECF COUNTER1)) DATA)) DATALIST))
            (T (UNLESS (= MEM*SIZE 320000)
                 (MEM-INITIALIZE 320000))
               (SETQ COUNTER1 73)
               (MAPC #'(LAMBDA (RADDR) (SETF (AREF MEM*MEMORY (DECF COUNTER1)) RADDR))
                     ADDRLIST)
               (SETQ COUNTER1 MEM*SIZE)
               (MAPC #'(LAMBDA (DATA) (SETF (AREF MEM*MEMORY (DECF COUNTER1)) DATA)) DATALIST))
            )
      (SETQ MEM*NEXT.RADR (IF (> MEM*SIZE 320000) (+ 319575 INCREMENT) 319575))
      (SETQ MEM*NEXT.VADR 73
            MEM*REST (- MEM*NEXT.RADR MEM*NEXT.VADR -1)
            MEM*FIRST.REUSABLE.VADR NIL
            MEM*LAST.REUSABLE.VADR NIL))

(PROGN (SETQ DT*SORT.ALL (QUOTE (ANY))) (SETQ DT*SORT.NR (QUOTE 2)) (SETQ DT*SORT.PROPERTIES (QUOTE (DT*MAX.SUBSORTS DT*LEAST.SUPERSORTS DT*TRANSITIVE.CLOSURE DT*INVERSE.TRANSITIVE.CLOSURE DT*MINIMAL.SUBSORTS DT*DIRECT.SUBSORTS DT*DIRECT.SUPERSORTS DT*DISJOINT.SORTS DT*COMPLETION.SORT))) (SETQ DT*SORT.COMMON.COMPUTE.FLAG (QUOTE NIL)) (SETQ DT*ELEMENT.PREDICATE (QUOTE 4)) (SETQ DT*OMEGA.CONSTANT (QUOTE 3)) (SETQ DT*VARIABLE.COUNTER (QUOTE 0)) (SETQ DT*CONSTANT.COUNTER (QUOTE 0)) (SETQ DT*CONSTANT.ALL (QUOTE (65 55 36 28 20 18 17 16 15 14 13 12 11 10 9 8 7 6 5 3))) (SETQ DT*ABBREVIATIONS (QUOTE NIL)) (SETQ DT*FUNCTION.COUNTER (QUOTE 0)) (SETQ DT*FUNCTION.ALL (QUOTE (46))) (SETQ DT*FUNCTION.ADMISSIBLE.THEORIES (QUOTE (ASSOCIATIVE))) (SETQ DT*FUNCTION.ACTUAL.THEORIES (QUOTE NIL)) (SETQ DT*FUNCTION.WITH.ARGUMENT.SYMMETRIES (QUOTE NIL)) (SETQ DT*FUNCTION.COMPONENTS (QUOTE (PNAME ATTRIBUTES MAX.RANGE.SORT MAX.DOMAIN.SORTS MIN.RANGE.SORTS SORT.LIST SORT.LIST.INVERSE SORT.TREE.CALC ARGUMENT.SYMMETRIES ARITY G.L.B.OF.RANGES))) (SETQ DT*PREDICATE.ADMISSABLE.ATTRIBUTES (QUOTE (SYMMETRIC DEFINED REFLEXIVE))) (SETQ DT*PREDICATE.COUNTER (QUOTE 0)) (SETQ DT*EQUALITY.SYMBOLS (QUOTE ("=" ":=" "=:" ":=:"))) (SETQ DT*EQUALITY.PREDICATES (QUOTE (2))) (SETQ DT*NONEQUALITY.PREDICATES (QUOTE (56 4 1 0))) (SETQ DT*PREDICATE.ALL (QUOTE (56 4 2 1 0))) (SETQ DT*PREDICATE.WITH.ATTRIBUTES (QUOTE NIL)) (SETQ DT*PREDICATE.COMPONENTS (QUOTE (PNAME POSITIVE.OCCURRENCES NEGATIVE.OCCURRENCES DOMAINSORTS ATTRIBUTES REFL.CLAUSE +ROTHERSIDES -ROTHERSIDES +SOTHERSIDES -SOTHERSIDES +TOTHERSIDES -TOTHERSIDES))) (SETQ DT*TRUE.PREDICATE (QUOTE 0)) (SETQ DT*FALSE.PREDICATE (QUOTE 1)) (SETQ DT*UNI.CREATES.VARIABLES (QUOTE NIL)) (SETQ DT*SIGN.MINUS.SYMBOLS (QUOTE (- --))) (SETQ DT*SIGN.PLUS.SYMBOLS (QUOTE (+ ++))) (SETQ DT*SYMBOL.KINDS (QUOTE (CONSTANT.ALL FUNCTION.ALL PREDICATE.ALL)))) 
(PROGN) 
(PROGN (PROGN)) 
(PROGN (PROGN (SETF (GET (QUOTE ANY) (QUOTE DT*SORT.NUMBER)) (QUOTE 1)) (SETF (GET (QUOTE ANY) (QUOTE DT*DIRECT.SUBSORTS)) (QUOTE NIL)) (SETF (GET (QUOTE ANY) (QUOTE DT*TRANSITIVE.CLOSURE)) (QUOTE (ANY))) (SETF (GET (QUOTE ANY) (QUOTE DT*MAX.SUBSORTS)) (QUOTE ((ANY ANY)))) (SETF (GET (QUOTE ANY) (QUOTE DT*MINIMAL.SUBSORTS)) (QUOTE (ANY))) (SETF (GET (QUOTE ANY) (QUOTE DT*DIRECT.SUPERSORTS)) (QUOTE NIL)) (SETF (GET (QUOTE ANY) (QUOTE DT*INVERSE.TRANSITIVE.CLOSURE)) (QUOTE (ANY))))) ))