;;; -*- Mode: LISP; Package: MKRP; Syntax: Common-lisp -*-
(PORTRAIT (GOLD) OR PORTRAIT (LEAD) OR PORTRAIT (SILVER))
(NOT (PORTRAIT (GOLD) AND PORTRAIT (LEAD) OR PORTRAIT (GOLD) AND PORTRAIT (SILVER) OR PORTRAIT (SILVER) AND PORTRAIT
(LEAD)))
(ALL X,Y INSCRIPTION (X Y) AND TRUTH (X) IMPL PORTRAIT (Y))
(ALL X,Y INSCRIPTION (X Y) AND NOT TRUTH (X) IMPL NOT PORTRAIT (X))
(ALL X,Y 
NEGATIVE.INSCRIPTION (X Y) AND TRUTH (X) IMPL NOT PORTRAIT (X))
(ALL X,Y NEGATIVE.INSCRIPTION (X Y) AND NOT TRUTH (X) IMPL PORTRAIT (X))
(TRUTH (SILVER) OR TRUTH (GOLD) OR TRUTH (LEAD))
(NOT TRUTH (SILVER) OR
NOT TRUTH (GOLD) OR NOT TRUTH (LEAD))
(NEGATIVE.INSCRIPTION (GOLD SILVER))
(NEGATIVE.INSCRIPTION (SILVER SILVER))
(INSCRIPTION (LEAD LEAD))

(PORTRAIT (GOLD))